In [ ]:
import pandas as pd
import numpy as np

## Real GDP

In [ ]:
df_real_gdp = pd.read_excel('GDP real (2000 onwards).xlsx')
print("DataFrame 'df_real_gdp' loaded successfully.")
df_real_gdp

DataFrame 'df_real_gdp' loaded successfully.

,Gross Domestic Product - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 298,Unnamed: 299,Unnamed: 300,Unnamed: 301,Unnamed: 302,Unnamed: 303,Unnamed: 304,Unnamed: 305,Unnamed: 306,Unnamed: 307
0,Next Rpt Date: 29 Jan '26,Billions of 2000 PHP,Real,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,National Statistical Coordination Board,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,01/31/2025,...,12/29/2000,11/30/2000,10/31/2000,09/29/2000,08/31/2000,07/31/2000,06/30/2000,05/31/2000,04/28/2000,03/31/2000
4,Gross Domestic Product,5528.834473,5528.834473,5528.834473,5843.036621,5843.036621,5843.036621,5475.077637,5475.077637,5475.077637,...,1892.884888,1892.884888,1892.884888,1709.412964,1709.412964,1709.412964,1729.789429,1729.789429,1729.789429,1653.296021
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Final Consumption Expenditure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Households,4033.096436,4033.096436,4033.096436,3953.57373,3953.57373,3953.57373,4069.803223,4069.803223,4069.803223,...,1465.297729,1465.297729,1465.297729,1313.248291,1313.248291,1313.248291,1339.474609,1339.474609,1339.474609,1238.391235
8,Government,827.191345,827.191345,827.191345,1019.939697,1019.939697,1019.939697,871.001648,871.001648,871.001648,...,195.842377,195.842377,195.842377,212.40741,212.40741,212.40741,224.339264,224.339264,224.339264,196.144226
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Trade Balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Goods,1029.294067,1029.294067,1029.294067,811.434326,811.434326,811.434326,733.459167,733.459167,733.459167,...,364.655273,364.655273,364.655273,417.863983,417.863983,417.863983,339.635315,339.635315,339.635315,328.847351
13,Services,634.777649,634.777649,634.777649,736.799255,736.799255,736.799255,857.097229,857.097229,857.097229,...,90.986794,90.986794,90.986794,77.809105,77.809105,77.809105,71.266228,71.266228,71.266228,78.950966
14,Imports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Goods,1637.675049,1637.675049,1637.675049,1731.071045,1731.071045,1731.071045,1659.263306,1659.263306,1659.263306,...,426.493408,426.493408,426.493408,456.58017,456.58017,456.58017,388.911713,388.911713,388.911713,383.772461
16,Services,570.257996,570.257996,570.257996,458.076141,458.076141,458.076141,576.975525,576.975525,576.975525,...,143.669693,143.669693,143.669693,85.110657,85.110657,85.110657,104.278831,104.278831,104.278831,114.483788
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Capital Formation,1186.144043,1186.144043,1186.144043,1528.849854,1528.849854,1528.849854,1204.467407,1204.467407,1204.467407,...,339.957764,339.957764,339.957764,245.992325,245.992325,245.992325,252.277359,252.277359,252.277359,295.296417
19,Fixed Capital Formation,1202.80957,1202.80957,1202.80957,1558.530396,1558.530396,1558.530396,1201.714844,1201.714844,1201.714844,...,342.144196,342.144196,342.144196,305.714691,305.714691,305.714691,310.028839,310.028839,310.028839,319.796326
20,Construction,748.607056,748.607056,748.607056,1082.751465,1082.751465,1082.751465,706.514221,706.514221,706.514221,...,210.044418,210.044418,210.044418,202.191833,202.191833,202.191833,185.19043,185.19043,185.19043,198.22496
21,Durable Equipment,321.306854,321.306854,321.306854,348.805389,348.805389,348.805389,368.828735,368.828735,368.828735,...,62.085239,62.085239,62.085239,65.171745,65.171745,65.171745,75.126015,75.126015,75.126015,68.143753
22,Breeding Stock & Orchard Development,86.650627,86.650627,86.650627,92.595695,92.595695,92.595695,89.241585,89.241585,89.241585,...,65.369713,65.369713,65.369713,34.000961,34.000961,34.000961,45.938812,45.938812,45.938812,48.959869
23,Intellectual Property Products,46.245102,46.245102,46.245102,34.377819,34.377819,34.377819,37.130322,37.130322,37.130322,...,4.644812,4.644812,4.644812,4.35017,4.35017,4.35017,3.77358,3.77358,3.77358,4.467733
24,Changes in Inventories,-16.89366,-16.89366,-16.89366,-29.934818,-29.934818,-29.934818,2.667663,2.667663,2.667663,...,-2.401253,-2.401253,-2.401253,-60.832428,-60.832428,-60.832428,-58.455471,-58.455471,-58.455471,-24.773746
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_real_gdp = df_real_gdp.iloc[[3, 4], 1:]
print("DataFrame 'df_real_gdp' modified to include only rows 3 and 4, and exclude the first column.")
df_real_gdp

DataFrame 'df_real_gdp' modified to include only rows 3 and 4, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 298,Unnamed: 299,Unnamed: 300,Unnamed: 301,Unnamed: 302,Unnamed: 303,Unnamed: 304,Unnamed: 305,Unnamed: 306,Unnamed: 307
3,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,01/31/2025,12/31/2024,...,12/29/2000,11/30/2000,10/31/2000,09/29/2000,08/31/2000,07/31/2000,06/30/2000,05/31/2000,04/28/2000,03/31/2000
4,5528.834473,5528.834473,5528.834473,5843.036621,5843.036621,5843.036621,5475.077637,5475.077637,5475.077637,6193.631348,...,1892.884888,1892.884888,1892.884888,1709.412964,1709.412964,1709.412964,1729.789429,1729.789429,1729.789429,1653.296021

In [ ]:
# Transpose rows and columns
gdp_df = df_real_gdp.T
# Rename the columns from the original row indices (3 and 4) to 'Date' and 'Real GDP'
gdp_df.rename(columns={3: 'Date', 4: 'Real GDP'}, inplace=True)

# Convert 'Date' column to datetime objects
gdp_df['Date'] = pd.to_datetime(gdp_df['Date'])
# Convert 'Real GDP' column to numeric, coercing errors to NaN
gdp_df['Real GDP'] = pd.to_numeric(gdp_df['Real GDP'], errors='coerce')
# Drop rows with NaN values in 'Real GDP' column that might have resulted from conversion errors
gdp_df = gdp_df.dropna(subset=['Real GDP'])

# Reset index, as the old column names (e.g., 'FactSet', 'Unnamed: 2') are no longer relevant as an index
gdp_df = gdp_df.reset_index(drop=True)

print("DataFrame 'gdp_df' created successfully with 'Date' and 'Real GDP' columns.")

DataFrame 'gdp_df' created successfully with 'Date' and 'Real GDP' columns.

In [ ]:
gdp_df

          Date     Real GDP
0   2025-09-30  5528.834473
1   2025-08-29  5528.834473
2   2025-07-31  5528.834473
3   2025-06-30  5843.036621
4   2025-05-30  5843.036621
..         ...          ...
302 2000-07-31  1709.412964
303 2000-06-30  1729.789429
304 2000-05-31  1729.789429
305 2000-04-28  1729.789429
306 2000-03-31  1653.296021

[307 rows x 2 columns]

In [ ]:
gdp_df['Date'] = (gdp_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'gdp_df' updated to the first day of the next month.") #justification is from comparing CPI values of CEIC and Factset
gdp_df.head()
gdp_df.tail()

Dates in 'gdp_df' updated to the first day of the next month.

          Date     Real GDP
302 2000-08-01  1709.412964
303 2000-07-01  1729.789429
304 2000-06-01  1729.789429
305 2000-05-01  1729.789429
306 2000-04-01  1653.296021

## CPI

In [ ]:
df_consumer_price = pd.read_excel('consumer price [levels] (1981 onwards).xlsx')
print("DataFrame 'df_consumer_price' loaded successfully.")
df_consumer_price

DataFrame 'df_consumer_price' loaded successfully.

,Consumer Prices - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 531,Unnamed: 532,Unnamed: 533,Unnamed: 534,Unnamed: 535,Unnamed: 536,Unnamed: 537,Unnamed: 538,Unnamed: 539,Unnamed: 540
0,Last Rpt Date: 06 Jan '26,Index Level - 2012 = 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,12/31/2025,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,...,10/30/1981,09/30/1981,08/31/1981,07/31/1981,06/30/1981,05/29/1981,04/30/1981,03/31/1981,02/27/1981,01/30/1981
4,Total,130,128.899994,128.600006,128.5,128.5,127.699997,127.300003,127.199997,127.300003,...,6.557027,6.509512,6.461998,6.461998,6.319454,6.224424,6.224424,6.176909,6.176909,6.129395
5,Food & Non-Alcoholic Beverages,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
6,Alcoholic Beverages & Tobacco,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
7,Clothing & Footwear,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
8,"Housing, Water, Electricity, Gas & Other Fuels",-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9,"Furnishing, Household Equipment & Routine Main...",-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
10,Health,127.599998,127.300003,127.099998,127,126.800003,126.300003,125.900002,125.699997,125.400002,...,-,-,-,-,-,-,-,-,-,-
11,Transport,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
12,Communication,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
13,Recreation & Culture,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
14,Education,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
15,Restaurants & Miscellaneous Goods & Services,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_consumer_price = df_consumer_price.iloc[[3, 4], 1:]
print("DataFrame 'df_consumer_price' modified to include only rows 3 and 4, and exclude the first column.")
df_consumer_price

DataFrame 'df_consumer_price' modified to include only rows 3 and 4, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 531,Unnamed: 532,Unnamed: 533,Unnamed: 534,Unnamed: 535,Unnamed: 536,Unnamed: 537,Unnamed: 538,Unnamed: 539,Unnamed: 540
3,12/31/2025,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/30/1981,09/30/1981,08/31/1981,07/31/1981,06/30/1981,05/29/1981,04/30/1981,03/31/1981,02/27/1981,01/30/1981
4,130,128.899994,128.600006,128.5,128.5,127.699997,127.300003,127.199997,127.300003,127.800003,...,6.557027,6.509512,6.461998,6.461998,6.319454,6.224424,6.224424,6.176909,6.176909,6.129395

In [ ]:
# Transpose rows and columns
cpi_df = df_consumer_price.T
# Rename the columns from the original row indices (3 and 4) to 'Date' and 'CPI'
cpi_df.rename(columns={3: 'Date', 4: 'CPI'}, inplace=True)

# Convert 'Date' column to datetime objects
cpi_df['Date'] = pd.to_datetime(cpi_df['Date'])
# Convert 'CPI' column to numeric, coercing errors to NaN
cpi_df['CPI'] = pd.to_numeric(cpi_df['CPI'], errors='coerce')
# Drop rows with NaN values in 'CPI' column that might have resulted from conversion errors
cpi_df = cpi_df.dropna(subset=['CPI'])

# Reset index, as the old column names (e.g., 'FactSet', 'Unnamed: 2') are no longer relevant as an index
cpi_df = cpi_df.reset_index(drop=True)

print("DataFrame 'cpi_df' created successfully with 'Date' and 'CPI' columns.")

DataFrame 'cpi_df' created successfully with 'Date' and 'CPI' columns.

In [ ]:
cpi_df

          Date         CPI
0   2025-12-31  130.000000
1   2025-11-28  128.899994
2   2025-10-31  128.600006
3   2025-09-30  128.500000
4   2025-08-29  128.500000
..         ...         ...
535 1981-05-29    6.224424
536 1981-04-30    6.224424
537 1981-03-31    6.176909
538 1981-02-27    6.176909
539 1981-01-30    6.129395

[540 rows x 2 columns]

In [ ]:
cpi_df['Date'] = (cpi_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'cpi_df' updated to the first day of the next month.") #justification is from comparing CPI values of CEIC and Factset
cpi_df.head()
cpi_df.tail()

Dates in 'cpi_df' updated to the first day of the next month.

          Date       CPI
535 1981-06-01  6.224424
536 1981-05-01  6.224424
537 1981-04-01  6.176909
538 1981-03-01  6.176909
539 1981-02-01  6.129395

# Wholesale Prices

In [ ]:
df_wholesale_prices = pd.read_excel('wholesale prices [levels] (1998 onwards).xlsx')
print("DataFrame 'df_wholesale_prices' loaded successfully.")
df_wholesale_prices

DataFrame 'df_wholesale_prices' loaded successfully.

,Wholesale Prices - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330,Unnamed: 331,Unnamed: 332,Unnamed: 333,Unnamed: 334,Unnamed: 335
0,Index Level - 1998 = 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/30/1998,09/30/1998,08/31/1998,07/31/1998,06/30/1998,05/29/1998,04/30/1998,03/31/1998,02/27/1998,01/30/1998
4,All Items,144,143.5,143.5,142.399994,143.300003,143,143.100006,143.399994,142.5,...,46.152122,45.299946,45.030834,44.851429,44.80658,44.627174,44.133808,43.774994,43.685291,43.191925
5,Food,158.800003,158.199997,158,157,156.800003,157.100006,157,157.199997,157,...,53.620956,51.771957,51.566513,51.155624,51.41243,51.206985,50.48793,49.563431,48.58757,48.176682
6,Beverages & Tobacco,238.399994,238.300003,237.899994,237.800003,237.699997,238.199997,238.199997,236.199997,235.100006,...,56.595844,56.595844,56.53981,56.203594,56.091526,56.091526,55.194958,55.082886,54.858746,54.52253
7,"Crude Materials, Inedible Except Fuels",236.199997,232.699997,242.699997,212.800003,266.399994,251.5,260.700012,267,234.5,...,54.698704,51.98138,51.780098,52.031704,51.075607,48.811172,46.446095,45.439678,44.835827,44.684868
8,"Mineral Fuels, Lubricants & Related Materials",148.699997,145.199997,144.399994,142.899994,143,141,138.5,140.600006,142.600006,...,15.627993,15.873137,15.428812,15.290918,15.076416,15.091738,14.907879,15.045774,16.072317,15.765886
9,"Chemicals, incl. Animal & Vegetable Oils/Fats",149.600006,148.800003,149.199997,145.300003,150.199997,148.600006,150.100006,151,146.100006,...,53.983227,53.616352,53.092243,52.987423,52.725368,52.044025,50.681343,50.471699,50.366875,49.842766
10,Manufactured Goods Classified Chiefly by Material,130.199997,130.100006,130.100006,130.100006,130.300003,130.300003,130.199997,130.300003,130.199997,...,59.202591,59.026039,58.672943,58.731792,58.790642,58.672943,58.672943,58.90834,58.790642,58.202148
11,Machinery & Transport Equipment,116,115.900002,115.900002,115.800003,115.800003,115.800003,115.699997,115.699997,115.599998,...,66.862747,65.294121,65.294121,65.359474,65.359474,65.22876,65.032677,64.379082,64.379082,63.137257
12,Miscellaneous Manufactured Articles,115.099998,115,114.599998,114.5,114.5,114.400002,114.400002,114.599998,114.5,...,52.868904,52.144672,52.144672,51.679096,51.472172,51.420441,51.21352,50.799671,50.799671,50.334095
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_wholesale_prices = df_wholesale_prices.iloc[[3, 4], 1:]
print("DataFrame 'df_wholesale_prices' modified to include only rows 3 and 4, and exclude the first column.")
df_wholesale_prices

DataFrame 'df_wholesale_prices' modified to include only rows 3 and 4, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330,Unnamed: 331,Unnamed: 332,Unnamed: 333,Unnamed: 334,Unnamed: 335
3,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,...,10/30/1998,09/30/1998,08/31/1998,07/31/1998,06/30/1998,05/29/1998,04/30/1998,03/31/1998,02/27/1998,01/30/1998
4,144,143.5,143.5,142.399994,143.300003,143,143.100006,143.399994,142.5,141.800003,...,46.152122,45.299946,45.030834,44.851429,44.80658,44.627174,44.133808,43.774994,43.685291,43.191925

In [ ]:
# Transpose rows and columns
wholesale_prices_df = df_wholesale_prices.T

# Rename the columns from the original row indices (3 and 4) to 'Date' and 'Wholesale Price'
wholesale_prices_df.rename(columns={3: 'Date', 4: 'Wholesale Price'}, inplace=True)

# Convert 'Date' column to datetime objects
wholesale_prices_df['Date'] = pd.to_datetime(wholesale_prices_df['Date'])

# Convert 'Wholesale Price' column to numeric, coercing errors to NaN
wholesale_prices_df['Wholesale Price'] = pd.to_numeric(wholesale_prices_df['Wholesale Price'], errors='coerce')

# Drop rows with NaN values in 'Wholesale Price' column that might have resulted from conversion errors
wholesale_prices_df = wholesale_prices_df.dropna(subset=['Wholesale Price'])

# Reset index, as the old column names (e.g., 'FactSet', 'Unnamed: 2') are no longer relevant as an index
wholesale_prices_df = wholesale_prices_df.reset_index(drop=True)

print("DataFrame 'wholesale_prices_df' created successfully with 'Date' and 'Wholesale Price' columns.")
wholesale_prices_df.head()

DataFrame 'wholesale_prices_df' created successfully with 'Date' and 'Wholesale Price' columns.

        Date  Wholesale Price
0 2025-11-28       144.000000
1 2025-10-31       143.500000
2 2025-09-30       143.500000
3 2025-08-29       142.399994
4 2025-07-31       143.300003

In [ ]:
wholesale_prices_df['Date'] = (wholesale_prices_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'wholesale_prices_df' updated to the first day of the next month.")
wholesale_prices_df

Dates in 'wholesale_prices_df' updated to the first day of the next month.

          Date  Wholesale Price
0   2025-12-01       144.000000
1   2025-11-01       143.500000
2   2025-10-01       143.500000
3   2025-09-01       142.399994
4   2025-08-01       143.300003
..         ...              ...
330 1998-06-01        44.627174
331 1998-05-01        44.133808
332 1998-04-01        43.774994
333 1998-03-01        43.685291
334 1998-02-01        43.191925

[335 rows x 2 columns]

# Industrial Production

In [ ]:
df_industrial_production = pd.read_excel('industrial production [levels] (1998 onwards).xlsx')
print("DataFrame 'df_industrial_production' loaded successfully.")
df_industrial_production

DataFrame 'df_industrial_production' loaded successfully.

,Industrial Production - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330,Unnamed: 331,Unnamed: 332,Unnamed: 333,Unnamed: 334,Unnamed: 335
0,Index Level - 2000 = 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/30/1998,09/30/1998,08/31/1998,07/31/1998,06/30/1998,05/29/1998,04/30/1998,03/31/1998,02/27/1998,01/30/1998
4,Total Manufacturing,100.048134,102.761719,97.322502,100.351433,101.363564,98.934433,99.385788,95.567711,97.262245,...,40.353806,43.702553,40.381947,41.507576,40.747776,37.905563,36.526669,41.001041,39.200035,39.200035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Transport Equipment,100.35965,101.710892,100.647606,102.184959,107.947914,101.671143,108.694351,93.185173,97.567848,...,-,-,-,-,-,-,-,-,-,-
60,Furniture & Fixtures,77.937149,99.679497,89.128105,89.175262,92.234245,84.395287,85.221703,88.743958,81.065575,...,-,-,-,-,-,-,-,-,-,-
61,Miscellaneous Manufactures,95.392693,98.061951,96.370804,93.747185,101.53067,91.593658,87.516914,85.497772,91.121758,...,-,-,-,-,-,-,-,-,-,-
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_industrial_production = df_industrial_production.iloc[[3, 4], 1:]
print("DataFrame 'df_industrial_production' modified to include only rows 3 and 4, and exclude the first column.")

# Transpose rows and columns
industrial_production_df = df_industrial_production.T

# Rename the columns from the original row indices (3 and 4) to 'Date' and 'Industrial Production'
industrial_production_df.rename(columns={3: 'Date', 4: 'Industrial Production'}, inplace=True)

# Convert 'Date' column to datetime objects
industrial_production_df['Date'] = pd.to_datetime(industrial_production_df['Date'])

# Convert 'Industrial Production' column to numeric, coercing errors to NaN
industrial_production_df['Industrial Production'] = pd.to_numeric(industrial_production_df['Industrial Production'], errors='coerce')

# Drop rows with NaN values in 'Industrial Production' column that might have resulted from conversion errors
industrial_production_df = industrial_production_df.dropna(subset=['Industrial Production'])

# Reset index, as the old column names are no longer relevant as an index
industrial_production_df = industrial_production_df.reset_index(drop=True)

print("DataFrame 'industrial_production_df' created successfully with 'Date' and 'Industrial Production' columns.")
industrial_production_df

DataFrame 'df_industrial_production' modified to include only rows 3 and 4, and exclude the first column.
DataFrame 'industrial_production_df' created successfully with 'Date' and 'Industrial Production' columns.

          Date  Industrial Production
0   2025-11-28             100.048134
1   2025-10-31             102.761719
2   2025-09-30              97.322502
3   2025-08-29             100.351433
4   2025-07-31             101.363564
..         ...                    ...
330 1998-05-29              37.905563
331 1998-04-30              36.526669
332 1998-03-31              41.001041
333 1998-02-27              39.200035
334 1998-01-30              39.200035

[335 rows x 2 columns]

In [ ]:
industrial_production_df['Date'] = (industrial_production_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'industrial_production_df' updated to the first day of the next month.")
industrial_production_df

Dates in 'industrial_production_df' updated to the first day of the next month.

          Date  Industrial Production
0   2025-12-01             100.048134
1   2025-11-01             102.761719
2   2025-10-01              97.322502
3   2025-09-01             100.351433
4   2025-08-01             101.363564
..         ...                    ...
330 1998-06-01              37.905563
331 1998-05-01              36.526669
332 1998-04-01              41.001041
333 1998-03-01              39.200035
334 1998-02-01              39.200035

[335 rows x 2 columns]

# International Trade

In [ ]:
df_international_trade = pd.read_excel('international trade [levels _ peso] (1957 onwards).xlsx')
print("DataFrame 'df_international_trade' loaded successfully.")
df_international_trade

DataFrame 'df_international_trade' loaded successfully.

,International Trade - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 818,Unnamed: 819,Unnamed: 820,Unnamed: 821,Unnamed: 822,Unnamed: 823,Unnamed: 824,Unnamed: 825,Unnamed: 826,Unnamed: 827
0,Next Rpt Date: 27 Jan '26,Millions of PHP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/31/1957,09/30/1957,08/30/1957,07/31/1957,06/28/1957,05/31/1957,04/30/1957,03/29/1957,02/28/1957,01/31/1957
4,Merchandise Exports,406979.75,434670.96875,416821.9375,407190.40625,417984.75,398221.28125,406874.84375,385384.9375,388416.125,...,46.459946,56.559937,69.689919,78.779907,90.899902,79.789902,83.829903,68.679924,77.769913,89.889908
5,Total Agro-Based Products,38.767395,34.957291,36.403126,32.980213,35.009666,33.063004,33.726799,33.82019,33.680981,...,-,-,-,-,-,-,-,-,-,-
6,Agro-Based Products,34.308033,29.991625,32.498081,29.181683,30.927877,29.526373,29.900633,29.982359,29.060038,...,-,-,-,-,-,-,-,-,-,-
7,Other Agro-Based Products,4.459361,4.965667,3.905048,3.798532,4.081789,3.536629,3.826165,3.837832,4.620944,...,-,-,-,-,-,-,-,-,-,-
8,Forest Products,0.953157,1.187217,0.990797,1.005461,1.030481,1.006683,0.974296,0.860394,1.053072,...,-,-,-,-,-,-,-,-,-,-
9,Mineral Products,19.20364,34.232555,40.319332,41.607933,50.455936,40.804333,38.454617,27.322866,28.262423,...,-,-,-,-,-,-,-,-,-,-
10,Petroleum Products,1.52901,1.379792,1.263275,1.301776,1.170201,0.884157,1.388821,1.512734,1.442943,...,-,-,-,-,-,-,-,-,-,-
11,Manufactures,339.158234,351.43335,329.016907,320.534241,322.792786,311.823914,320.099762,310.092438,305.321869,...,-,-,-,-,-,-,-,-,-,-
12,Electronic Products,247.128021,243.975739,230.589523,221.289322,223.195953,219.134521,213.941269,193.682327,208.881348,...,-,-,-,-,-,-,-,-,-,-
13,Other Electronics,16.397207,18.657089,17.950289,17.204729,17.766142,17.710144,18.769569,15.534924,18.495953,...,-,-,-,-,-,-,-,-,-,-
14,Garments,2.863732,3.316683,3.675226,3.762587,4.841889,3.401132,3.35261,2.910637,2.86442,...,-,-,-,-,-,-,-,-,-,-
15,Textile Yarns/Fabrics,1.48944,1.820355,1.566703,1.60582,1.660134,1.295905,1.29023,1.210572,1.356639,...,-,-,-,-,-,-,-,-,-,-
16,Footwear,0.522524,1.112847,0.523466,1.162138,0.780442,0.646079,1.315243,0.562826,0.31385,...,-,-,-,-,-,-,-,-,-,-
17,Travel Goods and Handbags,2.923531,3.16632,2.265491,2.835859,3.458008,2.589133,2.366997,2.480123,2.175512,...,-,-,-,-,-,-,-,-,-,-
18,Wood Manufactures,0.295208,0.359784,0.300757,0.25404,0.253756,0.308873,0.309483,0.258852,0.321562,...,-,-,-,-,-,-,-,-,-,-
19,Furniture & Fixtures,2.351536,2.003347,2.115344,2.099196,1.732446,1.391418,1.160528,1.173259,2.275243,...,-,-,-,-,-,-,-,-,-,-
20,Chemicals,8.197504,8.789334,9.135223,8.692462,8.494653,7.95387,9.891904,10.59715,9.493729,...,-,-,-,-,-,-,-,-,-,-
21,Non-metallic Mineral Manufactures,2.020819,2.464172,2.032197,2.277422,1.868075,1.929193,1.808524,1.488006,1.894392,...,-,-,-,-,-,-,-,-,-,-
22,Machinery & Transport Equipment,18.676359,24.865314,19.044273,20.779119,16.961792,17.093733,15.992776,12.631465,12.350611,...,-,-,-,-,-,-,-,-,-,-
23,Processed Food and Beverages,7.027369,7.552898,7.385726,7.111601,7.463407,5.824203,6.176148,6.517013,6.663319,...,-,-,-,-,-,-,-,-,-,-
24,Iron & Steel,0.334144,0.45652,0.869499,1.096613,0.568229,1.922578,0.752496,0.880832,1.7709,...,-,-,-,-,-,-,-,-,-,-
25,"Baby Carr., Toys, Games and sporting goods",0.873365,1.272949,1.340271,1.651681,1.850027,1.670732,1.273721,0.896332,1.114691,...,-,-,-,-,-,-,-,-,-,-
26,"Basketwork, Wickerwork and Other Articles of P...",0.122373,0.199657,0.161835,0.156717,0.119377,0.12578,0.127015,0.132982,0.176699,...,-,-,-,-,-,-,-,-,-,-
27,"Misc. Manufactured Articles, n.e.s",3.107624,0.364571,3.351944,3.004906,3.838806,3.516071,4.122149,4.009086,3.895917,...,-,-,-,-,-,-,-,-,-,-
28,Other Manufactures,24.827496,27.774624,26.70912,25.550024,27.939655,25.310558,37.449108,55.126057,31.277075,...,-,-,-,-,-,-,-,-,-,-
29,Special Transactions,7.368317,8.199382,7.573718,6.192049,6.749471,8.180247,10.783597,9.709459,8.651526,...,-,-,-,-,-,-,-,-,-,-
30,Re-Export,0.867326,0.973875,1.426494,0.999991,0.172058,0.134106,0.139331,0.076285,0.068887,...,-,-,-,-,-,-,-,-,-,-
31,Merchandise Imports,613973.0625,679404.9375,684380.125,634966.375,669526.125,645985,608916.25,611109.375,647409.5,...,119.179855,124.229858,107.059875,128.269852,127.259865,131.299835,119.179863,111.099876,81.809914,118.169884
32,Capital Goods,185.299667,195.095062,215.744064,185.135666,194.791245,209.387955,164.579956,186.227295,181.381546,...,-,-,-,-,-,-,-,-,-,-
33,Raw Materials & Intermediate Goods,232.385513,243.996979,236.829239,218.408157,238.616928,206.619553,220.838974,208.526398,224.7789,...,-,-,-,-,-,-,-,-,-,-
34,Unprocessed Raw Materials,17.211552,23.504702,20.302738,16.861683,18.97184,14.983668,22.721376,13.992345,19.115288,...,-,-,-,-,-,-,-,-,-,-
35,Semi-processed Raw Materials,215.173965,220.492279,21.652651,201.546478,219.645081,191.635895,198.117599,194.534058,205.66362,...,-,-,-,-,-,-,-,-,-,-
36,"Mineral Fuels, Lubricant & Related Materials",6.242945,7.911544,7.341563,67.393761,75.280045,78.977722,65.140907,61.435295,74.969162,...,-,-,-,-,-,-,-,-,-,-
37,"Coal, Coke",10.007606,11.113941,0.963506,11.462886,9.372374,11.377962,12.493628,12.145379,10.947418,...,-,-,-,-,-,-,-,-,-,-
38,Petroleum Crude,10.304665,15.97123,14.312759,7.282759,8.531246,10.031859,10.233994,8.598335,15.726325,...,-,-,-,-,-,-,-,-,-,-
39,Others,42.11718,52.030273,49.467804,48.648117,57.376427,57.567898,42.413284,40.691578,48.295418,...,-,-,-,-,-,-,-,-,-,-
40,Consumer Goods,130.986588,134.338181,136.213791,131.995087,136.123856,121.206772,135.799057,123.429314,131.82254,...,-,-,-,-,-,-,-,-,-,-
41,Durable,66.437737,70.716583,71.00074,65.698265,70.879303,60.586227,67.746658,59.203342,66.557083,...,-,-,-,-,-,-,-,-,-,-
42,Passenger Cars & Motorized Cycle,33.657265,37.49358,33.49004,33.557102,34.786549,29.069395,36.834499,28.216856,35.094254,...,-,-,-,-,-,-,-,-,-,-
43,Home Appliances,5.590669,4.312653,6.326922,5.863803,6.004975,5.881817,5.628808,6.516794,6.227349,...,-,-,-,-,-,-,-,-,-,-
44,Miscellaneous Manufactures,27.1898,28.910349,31.183779,26.277357,30.087784,25.635015,25.283352,24.46969,25.235476,...,-,-,-,-,-,-,-,-,-,-
45,Non-durable,64.548851,63.621601,65.213058,66.296822,65.244545,60.620544,68.052399,64.225967,65.265465,...,-,-,-,-,-,-,-,-,-,-
46,Food & Live Animals Chiefly For Food,55.567848,5.600452,57.76104,59.689293,57.981472,53.856209,61.645802,58.131344,59.514137,...,-,-,-,-,-,-,-,-,-,-
47,Beverages & Tobacco Mfture.,3.590288,3.322658,3.470198,2.8307,2.819349,2.573246,2.596502,2.400032,2.005407,...,-,-,-,-,-,-,-,-,-,-
48,"Articles of Apparel, Accessories",0.539071,4.294417,3.981821,3.776826,4.443725,4.19109,3.810098,3.694593,3.745918,...,-,-,-,-,-,-,-,-,-,-
49,Special Transactions,2.872092,2.230613,2.722884,3.01189,2.648027,2.443506,2.094317,2.284496,2.346786,...,-,-,-,-,-,-,-,-,-,-
50,Articles Temporarily Imported & Exported,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
51,Others,2.872092,2.230613,2.722884,3.01189,2.648027,2.443506,2.094317,2.284496,2.346786,...,-,-,-,-,-,-,-,-,-,-
52,Merchandise Trade Balance,-0.207015,-0.24476,-0.26758,-0.227765,-0.251545,-0.247785,-0.202031,-0.225747,-0.259011,...,-,-,-,-,-,-,-,-,-,-
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Notes: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Classification by SITC Commodity Groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_international_trade = df_international_trade.iloc[[3, 4, 31], 1:]
print("DataFrame 'df_international_trade' modified to include only rows 3, 4, and 31, and exclude the first column.")
df_international_trade.head()

DataFrame 'df_international_trade' modified to include only rows 3, 4, and 31, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 818,Unnamed: 819,Unnamed: 820,Unnamed: 821,Unnamed: 822,Unnamed: 823,Unnamed: 824,Unnamed: 825,Unnamed: 826,Unnamed: 827
3,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,...,10/31/1957,09/30/1957,08/30/1957,07/31/1957,06/28/1957,05/31/1957,04/30/1957,03/29/1957,02/28/1957,01/31/1957
4,406979.75,434670.96875,416821.9375,407190.40625,417984.75,398221.28125,406874.84375,385384.9375,388416.125,394115.84375,...,46.459946,56.559937,69.689919,78.779907,90.899902,79.789902,83.829903,68.679924,77.769913,89.889908
31,613973.0625,679404.9375,684380.125,634966.375,669526.125,645985,608916.25,611109.375,647409.5,566823,...,119.179855,124.229858,107.059875,128.269852,127.259865,131.299835,119.179863,111.099876,81.809914,118.169884

In [ ]:
international_trade_df = df_international_trade.T
international_trade_df.rename(columns={3: 'Date', 4: 'Intl Trade Merch Exports', 31: 'Intl Trade Merch Imports'}, inplace=True)

international_trade_df['Date'] = pd.to_datetime(international_trade_df['Date'])
international_trade_df['Intl Trade Merch Exports'] = pd.to_numeric(international_trade_df['Intl Trade Merch Exports'], errors='coerce')
international_trade_df['Intl Trade Merch Imports'] = pd.to_numeric(international_trade_df['Intl Trade Merch Imports'], errors='coerce')

international_trade_df.dropna(subset=['Intl Trade Merch Exports', 'Intl Trade Merch Imports'], inplace=True)
international_trade_df = international_trade_df.reset_index(drop=True)

print("DataFrame 'international_trade_df' processed successfully with 'Date', 'Intl Trade Merch Exports', and 'Intl Trade Merch Imports' columns.")
international_trade_df.head()

DataFrame 'international_trade_df' processed successfully with 'Date', 'Intl Trade Merch Exports', and 'Intl Trade Merch Imports' columns.

        Date  Intl Trade Merch Exports  Intl Trade Merch Imports
0 2025-11-28              406979.75000               613973.0625
1 2025-10-31              434670.96875               679404.9375
2 2025-09-30              416821.93750               684380.1250
3 2025-08-29              407190.40625               634966.3750
4 2025-07-31              417984.75000               669526.1250

In [ ]:
international_trade_df['Date'] = (international_trade_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'international_trade_df' updated to the first day of the next month.")
international_trade_df

Dates in 'international_trade_df' updated to the first day of the next month.

          Date  Intl Trade Merch Exports  Intl Trade Merch Imports
0   2025-12-01             406979.750000             613973.062500
1   2025-11-01             434670.968750             679404.937500
2   2025-10-01             416821.937500             684380.125000
3   2025-09-01             407190.406250             634966.375000
4   2025-08-01             417984.750000             669526.125000
..         ...                       ...                       ...
822 1957-06-01                 79.789902                131.299835
823 1957-05-01                 83.829903                119.179863
824 1957-04-01                 68.679924                111.099876
825 1957-03-01                 77.769913                 81.809914
826 1957-02-01                 89.889908                118.169884

[827 rows x 3 columns]

# FX Rate

In [ ]:
df_fx_rate = pd.read_excel('pesodollar.xlsx', header=None)

# Data starts from the 7th row (index 6).
# - 2nd column (index 1) contains the year
# - 3rd column (index 2) contains the month
# - 4th column (index 3) contains the FX rate values
df_working = df_fx_rate.iloc[6:, [1, 2, 3]].copy()
df_working.columns = ['Year', 'Month', 'FX Rate']

# The 'Year' column has NaNs that need to be forward-filled.
df_working['Year'] = df_working['Year'].ffill()

# Drop rows where 'Month' or 'FX_Rate' are NaN, as these are not complete data entries.
df_working = df_working.dropna(subset=['Month', 'FX Rate']).copy()

# Convert month names to numerical representation.
month_mapping = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
    'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
}
df_working['Month_Num'] = df_working['Month'].map(month_mapping)

# Ensure 'Year' is integer type for date creation.
df_working['Year'] = df_working['Year'].astype(int)

# Create the 'Date' column combining 'Year', 'Month_Num', and setting the day to 1.
# Rename columns to 'year' and 'month' as pd.to_datetime expects these lowercase names
# when passed a DataFrame with date components.
df_working['Date'] = pd.to_datetime(
    df_working[['Year', 'Month_Num']].assign(day=1).rename(
        columns={'Year': 'year', 'Month_Num': 'month'}
    )
)

# Select the final desired columns: 'Date' as the 1st and 'FX_Rate' as the 2nd.
df_fx_rate_cleaned = df_working[['Date', 'FX Rate']].copy()

print("Cleaned and processed DataFrame 'df_fx_rate_cleaned'")

print("\nDataFrame Info:")
df_fx_rate_cleaned.info()

Cleaned and processed DataFrame 'df_fx_rate_cleaned'

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 972 entries, 7 to 978
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     972 non-null    datetime64[ns]
 1   FX Rate  972 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 22.8+ KB

/tmp/ipykernel_176/1617850978.py:11: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_working['Year'] = df_working['Year'].ffill()

In [ ]:
df_fx_rate_cleaned

          Date    FX Rate
7   1945-01-01          2
8   1945-02-01          2
9   1945-03-01          2
10  1945-04-01          2
11  1945-05-01          2
..         ...        ...
974 2025-08-01  57.252526
975 2025-09-01  57.250091
976 2025-10-01  58.298409
977 2025-11-01   58.91355
978 2025-12-01  58.848833

[972 rows x 2 columns]

# merge all new df

In [ ]:
main_df = gdp_df
main_df = pd.merge(main_df, cpi_df, on='Date', how='outer')
main_df = pd.merge(main_df, wholesale_prices_df, on='Date', how='outer')
main_df = pd.merge(main_df, industrial_production_df, on='Date', how='outer')
main_df = pd.merge(main_df, international_trade_df, on='Date', how='outer')
main_df = pd.merge(main_df, df_fx_rate_cleaned, on='Date', how='outer')

print("Merged DataFrame 'main_df' created successfully.")
main_df

Merged DataFrame 'main_df' created successfully.

,Date,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
0,1945-01-01,NaN,NaN,NaN,NaN,NaN,NaN,2
1,1945-02-01,NaN,NaN,NaN,NaN,NaN,NaN,2
2,1945-03-01,NaN,NaN,NaN,NaN,NaN,NaN,2
3,1945-04-01,NaN,NaN,NaN,NaN,NaN,NaN,2
4,1945-05-01,NaN,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...,...
968,2025-09-01,5528.834473,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091
969,2025-10-01,5528.834473,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409
970,2025-11-01,NaN,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355
971,2025-12-01,NaN,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833
972,2026-01-01,NaN,130.000000,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Saving df for EDA
main_df.to_csv('withGDP_Macrovars_raw.csv', index=False)
print("DataFrame 'main_df' saved successfully to 'withGDP_Macrovars_raw.csv'.")

DataFrame 'main_df' saved successfully to 'withGDP_Macrovars_raw.csv'.

# merge all new df (without Real GDP)

In [ ]:
main2_df = cpi_df
main2_df = pd.merge(main2_df, wholesale_prices_df, on='Date', how='outer')
main2_df = pd.merge(main2_df, industrial_production_df, on='Date', how='outer')
main2_df = pd.merge(main2_df, international_trade_df, on='Date', how='outer')
main2_df = pd.merge(main2_df, df_fx_rate_cleaned, on='Date', how='outer')

print("Merged DataFrame 'main2_df' created successfully.")
main2_df

Merged DataFrame 'main2_df' created successfully.

,Date,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
0,1945-01-01,NaN,NaN,NaN,NaN,NaN,2
1,1945-02-01,NaN,NaN,NaN,NaN,NaN,2
2,1945-03-01,NaN,NaN,NaN,NaN,NaN,2
3,1945-04-01,NaN,NaN,NaN,NaN,NaN,2
4,1945-05-01,NaN,NaN,NaN,NaN,NaN,2
...,...,...,...,...,...,...,...
968,2025-09-01,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091
969,2025-10-01,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409
970,2025-11-01,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355
971,2025-12-01,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833
972,2026-01-01,130.000000,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Saving df for EDA
main2_df.to_csv('withoutGDP_Macrovars_raw.csv', index=False)
print("DataFrame 'main2_df' saved successfully to 'withoutGDP_Macrovars_raw.csv'.")

DataFrame 'main2_df' saved successfully to 'withoutGDP_Macrovars_raw.csv'.

# transform Yoy

In [ ]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      973 non-null    datetime64[ns]
 1   Real GDP                  307 non-null    float64
 2   CPI                       540 non-null    float64
 3   Wholesale Price           335 non-null    float64
 4   Industrial Production     335 non-null    float64
 5   Intl Trade Merch Exports  827 non-null    float64
 6   Intl Trade Merch Imports  827 non-null    float64
 7   FX Rate                   972 non-null    object
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 60.9+ KB

In [ ]:
cols_to_transform = [
    "Real GDP", "CPI", "Wholesale Price", "Industrial Production",
    "Intl Trade Merch Exports", "Intl Trade Merch Imports", "FX Rate"
]

for c in cols_to_transform:
    # Check if strictly positive (needed for logs)
    if (main_df[c] > 0).all():
        main_df[f"{c}_yoy_log"] = 100 * (np.log(main_df[c]) - np.log(main_df[c].shift(12)))
    else:
        main_df[f"{c}_yoy_pct"] = 100 * (main_df[c] / main_df[c].shift(12) - 1)

In [ ]:
main_df

,Date,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,1945-01-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1945-02-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1945-03-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1945-04-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1945-05-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,2025-09-01,5528.834473,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091,4.002598,1.500791,2.372385,1.886840,5.839883,-0.023116,2.102333
969,2025-10-01,5528.834473,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409,4.002598,1.741882,2.867384,0.973492,18.754169,7.420514,1.74088
970,2025-11-01,NaN,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355,NaN,1.660084,2.646636,1.529212,22.250455,-1.464230,0.372947
971,2025-12-01,NaN,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833,NaN,1.496058,2.710416,-1.386432,21.714685,-1.611572,0.685795
972,2026-01-01,NaN,130.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.801099,NaN,NaN,NaN,NaN,NaN

In [ ]:
main_df.info()
main_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   Real GDP                          307 non-null    float64
 2   CPI                               540 non-null    float64
 3   Wholesale Price                   335 non-null    float64
 4   Industrial Production             335 non-null    float64
 5   Intl Trade Merch Exports          827 non-null    float64
 6   Intl Trade Merch Imports          827 non-null    float64
 7   FX Rate                           972 non-null    object
 8   Real GDP_yoy_pct                  295 non-null    float64
 9   CPI_yoy_pct                       528 non-null    float64
 10  Wholesale Price_yoy_pct           323 non-null    float64
 11  Industrial Production_yoy_pct     323 non-null    float64
 12  Intl Trade Merch Exports_yoy_pct  815 non-null    float64
 13  Intl Trade Merch Imports_yoy_pct  815 non-null    float64
 14  FX Rate_yoy_pct                   960 non-null    object
dtypes: datetime64[ns](1), float64(12), object(2)
memory usage: 114.2+ KB

,Date,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,973,307.000000,540.000000,335.000000,335.000000,827.000000,827.000000,295.000000,528.000000,323.000000,323.000000,815.000000,815.000000
mean,1985-07-01 13:19:10.668036992,3419.298446,59.259109,93.189740,74.139310,95519.991259,128884.015392,5.030131,7.337926,4.469206,9.787777,16.001531,15.744434
min,1945-01-01 00:00:00,1653.296021,6.129395,43.191925,13.077386,46.459946,75.749916,-16.907215,-0.996677,-11.172665,-83.100000,-42.774042,-63.847638
25%,1965-04-01 00:00:00,2325.314209,27.059615,67.277145,61.936256,1196.188538,1643.216126,4.501927,3.103568,2.069859,-2.149256,0.289489,0.526592
50%,1985-07-01 00:00:00,3150.174561,54.261774,99.800003,76.853607,18641.226562,28496.814453,5.919077,5.261762,3.761247,4.947738,11.838300,12.909587
75%,2005-10-01 00:00:00,4437.331055,91.102268,112.649997,87.159279,184366.007812,211525.804688,6.842206,8.430930,6.737991,10.755655,26.973091,28.106789
max,2026-01-01 00:00:00,6193.631348,130.000000,144.000000,108.341713,454896.562500,694898.812500,12.041713,62.804866,21.073226,531.795100,167.088299,145.931977
std,NaN,1242.548460,36.278571,28.549285,18.776608,118155.582241,178227.869211,3.733462,8.420684,3.923869,57.158222,25.677724,23.499341

# YoY for df w/o GDP

In [ ]:
# for df without Real GDP
cols_to_transform = [
    "CPI", "Wholesale Price", "Industrial Production",
    "Intl Trade Merch Exports", "Intl Trade Merch Imports", "FX Rate"
]

for c in cols_to_transform:
    # Check if strictly positive (needed for logs)
    if (main2_df[c] > 0).all():
        main2_df[f"{c}_yoy_log"] = 100 * (np.log(main2_df[c]) - np.log(main2_df[c].shift(12)))
    else:
        main2_df[f"{c}_yoy_pct"] = 100 * (main2_df[c] / main2_df[c].shift(12) - 1)

In [ ]:
main2_df

,Date,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,1945-01-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
1,1945-02-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
2,1945-03-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
3,1945-04-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,1945-05-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,2025-09-01,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091,1.500791,2.372385,1.886840,5.839883,-0.023116,2.102333
969,2025-10-01,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409,1.741882,2.867384,0.973492,18.754169,7.420514,1.74088
970,2025-11-01,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355,1.660084,2.646636,1.529212,22.250455,-1.464230,0.372947
971,2025-12-01,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833,1.496058,2.710416,-1.386432,21.714685,-1.611572,0.685795
972,2026-01-01,130.000000,NaN,NaN,NaN,NaN,NaN,1.801099,NaN,NaN,NaN,NaN,NaN

In [ ]:
main2_df.info()
main2_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   CPI                               540 non-null    float64
 2   Wholesale Price                   335 non-null    float64
 3   Industrial Production             335 non-null    float64
 4   Intl Trade Merch Exports          827 non-null    float64
 5   Intl Trade Merch Imports          827 non-null    float64
 6   FX Rate                           972 non-null    object
 7   CPI_yoy_pct                       528 non-null    float64
 8   Wholesale Price_yoy_pct           323 non-null    float64
 9   Industrial Production_yoy_pct     323 non-null    float64
 10  Intl Trade Merch Exports_yoy_pct  815 non-null    float64
 11  Intl Trade Merch Imports_yoy_pct  815 non-null    float64
 12  FX Rate_yoy_pct                   960 non-null    object
dtypes: datetime64[ns](1), float64(10), object(2)
memory usage: 98.9+ KB

,Date,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,973,540.000000,335.000000,335.000000,827.000000,827.000000,528.000000,323.000000,323.000000,815.000000,815.000000
mean,1985-07-01 13:19:10.668036992,59.259109,93.189740,74.139310,95519.991259,128884.015392,7.337926,4.469206,9.787777,16.001531,15.744434
min,1945-01-01 00:00:00,6.129395,43.191925,13.077386,46.459946,75.749916,-0.996677,-11.172665,-83.100000,-42.774042,-63.847638
25%,1965-04-01 00:00:00,27.059615,67.277145,61.936256,1196.188538,1643.216126,3.103568,2.069859,-2.149256,0.289489,0.526592
50%,1985-07-01 00:00:00,54.261774,99.800003,76.853607,18641.226562,28496.814453,5.261762,3.761247,4.947738,11.838300,12.909587
75%,2005-10-01 00:00:00,91.102268,112.649997,87.159279,184366.007812,211525.804688,8.430930,6.737991,10.755655,26.973091,28.106789
max,2026-01-01 00:00:00,130.000000,144.000000,108.341713,454896.562500,694898.812500,62.804866,21.073226,531.795100,167.088299,145.931977
std,NaN,36.278571,28.549285,18.776608,118155.582241,178227.869211,8.420684,3.923869,57.158222,25.677724,23.499341

# merge with ICLR dataset

## checking dataset with ICLR values

In [ ]:
df_interest_rate = pd.read_csv('interest_rate.csv')
print("DataFrame 'df_interest_rate' loaded successfully.")
df_interest_rate.info()
df_interest_rate

DataFrame 'df_interest_rate' loaded successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATE                      360 non-null    object
 1   INTERBANK CALL LOAN RATE  360 non-null    float64
 2   PAST RATE CHANGE          360 non-null    object
 3   PAST RATE CHANGE CLASS    360 non-null    object
 4   REAL GDP                  359 non-null    float64
 5   CPI                       360 non-null    float64
dtypes: float64(3), object(3)
memory usage: 19.0+ KB

,DATE,INTERBANK CALL LOAN RATE,PAST RATE CHANGE,PAST RATE CHANGE CLASS,REAL GDP,CPI
0,1995-02-01,13.328125,0,SAME,1.633891,34.598607
1,1995-03-01,19.073370,43.11%,INCREASE,1.571302,34.664135
2,1995-04-01,20.375000,6.82%,INCREASE,1.353203,34.795190
3,1995-05-01,11.413690,-43.98%,DECREASE,1.339839,34.991773
4,1995-06-01,9.836310,-13.82%,DECREASE,1.523008,35.253884
...,...,...,...,...,...,...
398,NaN,NaN,NaN,NaN,NaN,NaN
399,NaN,NaN,NaN,NaN,NaN,NaN
400,NaN,NaN,NaN,NaN,NaN,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN
402,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
columns_to_drop = [
    'PAST RATE CHANGE',
    'PAST RATE CHANGE CLASS',
    'REAL GDP',
    'CPI'
]

# Drop the specified columns, ignoring errors if a column is already absent
df_interest_rate.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("Specified columns dropped successfully.")
df_interest_rate.info()

Specified columns dropped successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATE                      360 non-null    object
 1   INTERBANK CALL LOAN RATE  360 non-null    float64
dtypes: float64(1), object(1)
memory usage: 6.4+ KB

In [ ]:
df_interest_rate.isna().sum()

DATE                        43
INTERBANK CALL LOAN RATE    43
dtype: int64

In [ ]:
df_interest_rate[df_interest_rate.isna().any(axis=1)]

    DATE  INTERBANK CALL LOAN RATE
360  NaN                       NaN
361  NaN                       NaN
362  NaN                       NaN
363  NaN                       NaN
364  NaN                       NaN
365  NaN                       NaN
366  NaN                       NaN
367  NaN                       NaN
368  NaN                       NaN
369  NaN                       NaN
370  NaN                       NaN
371  NaN                       NaN
372  NaN                       NaN
373  NaN                       NaN
374  NaN                       NaN
375  NaN                       NaN
376  NaN                       NaN
377  NaN                       NaN
378  NaN                       NaN
379  NaN                       NaN
380  NaN                       NaN
381  NaN                       NaN
382  NaN                       NaN
383  NaN                       NaN
384  NaN                       NaN
385  NaN                       NaN
386  NaN                       NaN
387  NaN                       NaN
388  NaN                       NaN
389  NaN                       NaN
390  NaN                       NaN
391  NaN                       NaN
392  NaN                       NaN
393  NaN                       NaN
394  NaN                       NaN
395  NaN                       NaN
396  NaN                       NaN
397  NaN                       NaN
398  NaN                       NaN
399  NaN                       NaN
400  NaN                       NaN
401  NaN                       NaN
402  NaN                       NaN

In [ ]:
df_interest_rate = df_interest_rate.dropna(how='all')
print("Rows with all NaN values dropped from 'df_interest_rate'.")
df_interest_rate.info()
df_interest_rate

Rows with all NaN values dropped from 'df_interest_rate'.
<class 'pandas.core.frame.DataFrame'>
Index: 360 entries, 0 to 359
Data columns (total 2 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   DATE                      360 non-null    object
 1   INTERBANK CALL LOAN RATE  360 non-null    float64
dtypes: float64(1), object(1)
memory usage: 8.4+ KB

           DATE  INTERBANK CALL LOAN RATE
0    1995-02-01                 13.328125
1    1995-03-01                 19.073370
2    1995-04-01                 20.375000
3    1995-05-01                 11.413690
4    1995-06-01                  9.836310
..          ...                       ...
355  2024-10-01                  6.244332
356  2024-11-01                  6.159405
357  2024-12-01                  6.086828
358  2025-01-01                  5.895856
359  2025-02-01                  5.923455

[360 rows x 2 columns]

In [ ]:
df_interest_rate.rename(columns={'DATE': 'Date'}, inplace=True)
print("Column 'DATE' in df_interest_rate renamed to 'Date'.")

Column 'DATE' in df_interest_rate renamed to 'Date'.

/tmp/ipython-input-672/2188675631.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_interest_rate.rename(columns={'DATE': 'Date'}, inplace=True)

In [ ]:
df_interest_rate['Date'] = pd.to_datetime(df_interest_rate['Date'])
print("Column 'Date' in df_interest_rate converted to datetime.")

Column 'Date' in df_interest_rate converted to datetime.

/tmp/ipython-input-672/707524581.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_interest_rate['Date'] = pd.to_datetime(df_interest_rate['Date'])

## merging

In [ ]:
main_df = pd.merge(df_interest_rate, main_df, on='Date', how='outer')

print("Merged DataFrames successfully.")
main_df.info()
main_df

Merged DataFrames successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE          360 non-null    float64
 2   Real GDP                          307 non-null    float64
 3   CPI                               540 non-null    float64
 4   Wholesale Price                   335 non-null    float64
 5   Industrial Production             335 non-null    float64
 6   Intl Trade Merch Exports          827 non-null    float64
 7   Intl Trade Merch Imports          827 non-null    float64
 8   FX Rate                           972 non-null    object
 9   Real GDP_yoy_pct                  295 non-null    float64
 10  CPI_yoy_pct                       528 non-null    float64
 11  Wholesale Price_yoy_pct           323 non-null    float64
 12  Industrial Production_yoy_pct     323 non-null    float64
 13  Intl Trade Merch Exports_yoy_pct  815 non-null    float64
 14  Intl Trade Merch Imports_yoy_pct  815 non-null    float64
 15  FX Rate_yoy_pct                   960 non-null    object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 121.8+ KB

,Date,INTERBANK CALL LOAN RATE,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,1945-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1945-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1945-03-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1945-04-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1945-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,2025-09-01,NaN,5528.834473,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091,4.002598,1.500791,2.372385,1.886840,5.839883,-0.023116,2.102333
969,2025-10-01,NaN,5528.834473,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409,4.002598,1.741882,2.867384,0.973492,18.754169,7.420514,1.74088
970,2025-11-01,NaN,NaN,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355,NaN,1.660084,2.646636,1.529212,22.250455,-1.464230,0.372947
971,2025-12-01,NaN,NaN,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833,NaN,1.496058,2.710416,-1.386432,21.714685,-1.611572,0.685795
972,2026-01-01,NaN,NaN,130.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.801099,NaN,NaN,NaN,NaN,NaN

In [ ]:
main2_df = pd.merge(df_interest_rate, main2_df, on='Date', how='outer')

print("Merged DataFrames successfully.")
main2_df.info()
main2_df

Merged DataFrames successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE          360 non-null    float64
 2   CPI                               540 non-null    float64
 3   Wholesale Price                   335 non-null    float64
 4   Industrial Production             335 non-null    float64
 5   Intl Trade Merch Exports          827 non-null    float64
 6   Intl Trade Merch Imports          827 non-null    float64
 7   FX Rate                           972 non-null    object
 8   CPI_yoy_pct                       528 non-null    float64
 9   Wholesale Price_yoy_pct           323 non-null    float64
 10  Industrial Production_yoy_pct     323 non-null    float64
 11  Intl Trade Merch Exports_yoy_pct  815 non-null    float64
 12  Intl Trade Merch Imports_yoy_pct  815 non-null    float64
 13  FX Rate_yoy_pct                   960 non-null    object
dtypes: datetime64[ns](1), float64(11), object(2)
memory usage: 106.6+ KB

,Date,INTERBANK CALL LOAN RATE,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,1945-01-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
1,1945-02-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
2,1945-03-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
3,1945-04-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
4,1945-05-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,2025-09-01,NaN,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091,1.500791,2.372385,1.886840,5.839883,-0.023116,2.102333
969,2025-10-01,NaN,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409,1.741882,2.867384,0.973492,18.754169,7.420514,1.74088
970,2025-11-01,NaN,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355,1.660084,2.646636,1.529212,22.250455,-1.464230,0.372947
971,2025-12-01,NaN,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833,1.496058,2.710416,-1.386432,21.714685,-1.611572,0.685795
972,2026-01-01,NaN,130.000000,NaN,NaN,NaN,NaN,NaN,1.801099,NaN,NaN,NaN,NaN,NaN

# drop nulls for df w/ GDP

In [ ]:
print(f"Original shape of main_df: {main_df.shape}")
main_df.dropna(inplace=True)
print(f"New shape of main_df after dropping rows with missing values: {main_df.shape}")
print("Number of nulls per column after dropping rows:")
print(main_df.isna().sum())

Original shape of main_df: (973, 16)
New shape of main_df after dropping rows with missing values: (286, 16)
Number of nulls per column after dropping rows:
Date                                0
INTERBANK CALL LOAN RATE            0
Real GDP                            0
CPI                                 0
Wholesale Price                     0
Industrial Production               0
Intl Trade Merch Exports            0
Intl Trade Merch Imports            0
FX Rate                             0
Real GDP_yoy_pct                    0
CPI_yoy_pct                         0
Wholesale Price_yoy_pct             0
Industrial Production_yoy_pct       0
Intl Trade Merch Exports_yoy_pct    0
Intl Trade Merch Imports_yoy_pct    0
FX Rate_yoy_pct                     0
dtype: int64

In [ ]:
main_df.info()
main_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 286 entries, 675 to 961
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              286 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE          286 non-null    float64
 2   Real GDP                          286 non-null    float64
 3   CPI                               286 non-null    float64
 4   Wholesale Price                   286 non-null    float64
 5   Industrial Production             286 non-null    float64
 6   Intl Trade Merch Exports          286 non-null    float64
 7   Intl Trade Merch Imports          286 non-null    float64
 8   FX Rate                           286 non-null    object
 9   Real GDP_yoy_pct                  286 non-null    float64
 10  CPI_yoy_pct                       286 non-null    float64
 11  Wholesale Price_yoy_pct           286 non-null    float64
 12  Industrial Production_yoy_pct     286 non-null    float64
 13  Intl Trade Merch Exports_yoy_pct  286 non-null    float64
 14  Intl Trade Merch Imports_yoy_pct  286 non-null    float64
 15  FX Rate_yoy_pct                   286 non-null    object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 38.0+ KB

,Date,INTERBANK CALL LOAN RATE,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,286,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000,286.000000
mean,2013-02-18 12:30:12.587412480,4.814960,3421.042120,85.390992,97.391525,77.128905,230591.073563,312802.481015,5.023780,4.151243,4.401892,9.856698,4.861857,8.646121
min,2001-04-01 00:00:00,1.535187,1693.208862,50.080482,52.655579,13.077386,112845.664062,107386.726562,-16.907215,-0.372785,-11.172665,-83.100000,-42.774042,-63.847638
25%,2007-03-08 18:00:00,2.561885,2389.831299,66.673162,79.252476,68.429755,177745.871094,203492.894531,4.501927,2.802864,2.002272,-3.080583,-4.124583,-2.263209
50%,2013-02-15 00:00:00,4.595119,3178.883789,86.561013,100.699997,78.073200,207712.250000,231573.726562,5.944408,3.715112,3.537347,4.501294,3.451880,6.889053
75%,2019-01-24 06:00:00,6.841950,4432.011841,101.869095,112.775002,87.531229,284761.546875,434336.835938,6.842206,5.272010,6.955552,10.248327,13.967313,19.093407
max,2025-02-01 00:00:00,9.875000,6193.631348,128.399994,141.399994,108.341713,454896.562500,694898.812500,12.041713,10.541592,21.073226,531.795100,66.543686,141.991312
std,NaN,2.129587,1179.390804,21.641244,23.868873,16.231371,70702.108898,155232.467720,3.786374,2.129472,4.121004,60.681295,15.003019,19.386737

In [ ]:
main_df

,Date,INTERBANK CALL LOAN RATE,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
675,2001-04-01,9.875000,1693.208862,50.080482,52.655579,58.052792,139221.125000,147322.156250,50.185389,2.414138,7.551018,7.214612,21.064873,13.683626,31.135206,21.843502
676,2001-05-01,9.343750,1786.322144,50.175510,53.059242,49.240318,112845.664062,156004.359375,50.538857,3.268185,7.426241,8.432629,15.650250,2.635522,49.747061,20.888137
677,2001-06-01,9.092187,1786.322144,50.270542,53.418053,53.422508,131307.250000,148478.203125,51.48805,3.268185,7.411171,8.469950,10.694178,7.047290,45.582767,20.725388
678,2001-07-01,9.196023,1786.322144,50.698174,54.359932,56.260426,133000.015625,147393.734375,53.224182,3.268185,7.236184,9.882138,8.655032,-8.622024,38.405294,19.994097
679,2001-08-01,9.264205,1762.583252,51.030777,54.853298,52.974419,138151.718750,153010.750000,51.987696,3.110441,7.400007,9.784558,7.508969,-3.500603,28.565700,15.791568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,2024-10-01,6.244332,5316.054199,126.300003,139.500000,96.384209,350995.625000,637103.750000,57.30087,5.239308,1.937047,1.973682,-6.966527,-8.713099,8.727526,0.901607
958,2024-11-01,6.159405,6193.631348,126.500000,139.800003,101.213943,355557.750000,689500.812500,58.69465,5.252809,2.263543,2.118341,-1.599997,-3.973003,12.816407,5.164532
959,2024-12-01,6.086828,6193.631348,127.000000,140.199997,101.454735,334371.937500,624029.750000,58.448,5.252809,2.502016,2.261117,-4.130874,-3.839992,1.652797,5.145626
960,2025-01-01,5.895856,6193.631348,127.699997,140.899994,99.554054,330899.906250,572714.437500,58.390619,5.252809,2.900886,2.696791,0.079971,2.981743,3.488013,4.320615
961,2025-02-01,5.923455,5475.077637,128.399994,141.399994,99.709747,383804.093750,671522.625000,58.09415,5.379357,2.884608,2.911208,2.836625,14.402545,16.015169,3.619466

# save merged macrovars with GDP, with orig and yoy values

In [ ]:
main_df['FX Rate_yoy_pct'] = pd.to_numeric(main_df['FX Rate_yoy_pct'], errors='coerce')

main_df.to_csv('withGDP_Macrovars_with_orig_and_yoy.csv', index=False)
print("DataFrame 'main_df' saved successfully to 'macrovars_with_orig_and_yoy.csv'.")

DataFrame 'main_df' saved successfully to 'macrovars_with_orig_and_yoy.csv'.

In [ ]:
columns_to_drop = [
    'Real GDP',
    'CPI',
    'Wholesale Price',
    'Industrial Production',
    'Intl Trade Merch Exports',
    'Intl Trade Merch Imports',
    'FX Rate'
]

# Drop the specified columns, ignoring errors if a column is already absent
main_df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("Specified columns dropped successfully.")
main_df.info()

Specified columns dropped successfully.
<class 'pandas.core.frame.DataFrame'>
Index: 286 entries, 675 to 961
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              286 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE          286 non-null    float64
 2   Real GDP_yoy_pct                  286 non-null    float64
 3   CPI_yoy_pct                       286 non-null    float64
 4   Wholesale Price_yoy_pct           286 non-null    float64
 5   Industrial Production_yoy_pct     286 non-null    float64
 6   Intl Trade Merch Exports_yoy_pct  286 non-null    float64
 7   Intl Trade Merch Imports_yoy_pct  286 non-null    float64
 8   FX Rate_yoy_pct                   286 non-null    float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 30.4 KB

In [ ]:
new_columns = {}
for col in main_df.columns:
    # Only rename columns that are numeric (float or int) and end with '_yoy_pct'
    if col.endswith('_yoy_pct') and pd.api.types.is_numeric_dtype(main_df[col]):
        new_columns[col] = col.replace('_yoy_pct', '')
main_df.rename(columns=new_columns, inplace=True)

print("Columns renamed successfully by removing '_yoy_pct' suffix.")
main_df.info()
main_df

Columns renamed successfully by removing '_yoy_pct' suffix.
<class 'pandas.core.frame.DataFrame'>
Index: 286 entries, 675 to 961
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      286 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE  286 non-null    float64
 2   Real GDP                  286 non-null    float64
 3   CPI                       286 non-null    float64
 4   Wholesale Price           286 non-null    float64
 5   Industrial Production     286 non-null    float64
 6   Intl Trade Merch Exports  286 non-null    float64
 7   Intl Trade Merch Imports  286 non-null    float64
 8   FX Rate                   286 non-null    float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 30.4 KB

,Date,INTERBANK CALL LOAN RATE,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
675,2001-04-01,9.875000,2.414138,7.551018,7.214612,21.064873,13.683626,31.135206,21.843502
676,2001-05-01,9.343750,3.268185,7.426241,8.432629,15.650250,2.635522,49.747061,20.888137
677,2001-06-01,9.092187,3.268185,7.411171,8.469950,10.694178,7.047290,45.582767,20.725388
678,2001-07-01,9.196023,3.268185,7.236184,9.882138,8.655032,-8.622024,38.405294,19.994097
679,2001-08-01,9.264205,3.110441,7.400007,9.784558,7.508969,-3.500603,28.565700,15.791568
...,...,...,...,...,...,...,...,...,...
957,2024-10-01,6.244332,5.239308,1.937047,1.973682,-6.966527,-8.713099,8.727526,0.901607
958,2024-11-01,6.159405,5.252809,2.263543,2.118341,-1.599997,-3.973003,12.816407,5.164532
959,2024-12-01,6.086828,5.252809,2.502016,2.261117,-4.130874,-3.839992,1.652797,5.145626
960,2025-01-01,5.895856,5.252809,2.900886,2.696791,0.079971,2.981743,3.488013,4.320615
961,2025-02-01,5.923455,5.379357,2.884608,2.911208,2.836625,14.402545,16.015169,3.619466

# save merged macrovars with GDP

In [ ]:
main_df.to_csv('withGDP_Merged_macrovars.csv', index=False)

# drop nulls for df w/o GDP

In [ ]:
print(f"Original shape of main2_df: {main2_df.shape}")
main2_df.dropna(inplace=True)
print(f"New shape of main2_df after dropping rows with missing values: {main2_df.shape}")
print("Number of nulls per column after dropping rows:")
print(main2_df.isna().sum())

Original shape of main2_df: (973, 14)
New shape of main2_df after dropping rows with missing values: (312, 14)
Number of nulls per column after dropping rows:
Date                                0
INTERBANK CALL LOAN RATE            0
CPI                                 0
Wholesale Price                     0
Industrial Production               0
Intl Trade Merch Exports            0
Intl Trade Merch Imports            0
FX Rate                             0
CPI_yoy_pct                         0
Wholesale Price_yoy_pct             0
Industrial Production_yoy_pct       0
Intl Trade Merch Exports_yoy_pct    0
Intl Trade Merch Imports_yoy_pct    0
FX Rate_yoy_pct                     0
dtype: int64

In [ ]:
main2_df.info()
main2_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 649 to 961
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              312 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE          312 non-null    float64
 2   CPI                               312 non-null    float64
 3   Wholesale Price                   312 non-null    float64
 4   Industrial Production             312 non-null    float64
 5   Intl Trade Merch Exports          312 non-null    float64
 6   Intl Trade Merch Imports          312 non-null    float64
 7   FX Rate                           312 non-null    object
 8   CPI_yoy_pct                       312 non-null    float64
 9   Wholesale Price_yoy_pct           312 non-null    float64
 10  Industrial Production_yoy_pct     312 non-null    float64
 11  Intl Trade Merch Exports_yoy_pct  312 non-null    float64
 12  Intl Trade Merch Imports_yoy_pct  312 non-null    float64
 13  FX Rate_yoy_pct                   312 non-null    object
dtypes: datetime64[ns](1), float64(11), object(2)
memory usage: 36.6+ KB

,Date,INTERBANK CALL LOAN RATE,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,312,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000,312.000000
mean,2012-01-19 12:09:13.846153728,5.289297,82.180266,93.354601,74.619826,222110.046349,295917.635141,4.235783,4.515307,10.066057,6.028632,8.736695
min,1999-02-01 00:00:00,1.535187,45.233982,46.690338,13.077386,89768.156250,87593.679688,-0.372785,-11.172665,-83.100000,-42.774042,-63.847638
25%,2005-07-24 06:00:00,2.641827,61.876002,72.098675,62.880887,168211.968750,190615.324219,2.838111,2.057514,-2.458408,-3.649810,-2.053912
50%,2012-01-16 12:00:00,4.845412,83.925610,99.800003,76.883670,200973.093750,224594.265625,3.743560,3.888674,5.234296,4.589832,6.686217
75%,2018-07-08 18:00:00,7.094531,99.737047,112.099998,86.006660,279855.671875,404289.851562,5.373053,6.900945,10.860629,15.257898,18.643166
max,2025-02-01 00:00:00,15.105903,128.399994,141.399994,108.341713,454896.562500,694898.812500,10.541592,21.073226,531.795100,66.543686,141.991312
std,NaN,2.630692,23.304935,26.499504,17.688394,73621.744280,158895.696575,2.137359,3.983535,58.130508,15.180888,19.118048

In [ ]:
main2_df

,Date,INTERBANK CALL LOAN RATE,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
649,1999-02-01,12.623437,45.424042,46.735191,40.241245,99064.132812,92116.976562,38.7799,10.520235,8.203538,2.656146,9.744673,-23.949043,-4.044113
650,1999-03-01,12.282609,45.424042,46.690338,41.338734,99702.328125,87593.679688,38.910783,9.007978,6.878853,5.455860,11.205000,-15.831138,-0.239111
651,1999-04-01,11.090461,45.281498,46.824894,44.152805,105098.187500,103308.953125,38.241737,7.683616,6.967220,7.687034,9.368142,1.748419,-0.521337
652,1999-05-01,10.122024,45.233982,47.004299,41.282452,89768.156250,99449.031250,37.838476,7.086608,6.504064,13.020029,2.076156,5.168001,-3.711798
653,1999-06-01,9.525568,45.281498,47.138851,43.505569,103932.992188,95836.281250,37.899318,5.771366,5.628134,14.773573,9.614518,-6.975381,-6.1876
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
957,2024-10-01,6.244332,126.300003,139.500000,96.384209,350995.625000,637103.750000,57.30087,1.937047,1.973682,-6.966527,-8.713099,8.727526,0.901607
958,2024-11-01,6.159405,126.500000,139.800003,101.213943,355557.750000,689500.812500,58.69465,2.263543,2.118341,-1.599997,-3.973003,12.816407,5.164532
959,2024-12-01,6.086828,127.000000,140.199997,101.454735,334371.937500,624029.750000,58.448,2.502016,2.261117,-4.130874,-3.839992,1.652797,5.145626
960,2025-01-01,5.895856,127.699997,140.899994,99.554054,330899.906250,572714.437500,58.390619,2.900886,2.696791,0.079971,2.981743,3.488013,4.320615
961,2025-02-01,5.923455,128.399994,141.399994,99.709747,383804.093750,671522.625000,58.09415,2.884608,2.911208,2.836625,14.402545,16.015169,3.619466

# save merged macrovars without GDP, with orig and yoy values

In [ ]:
main2_df['FX Rate_yoy_pct'] = pd.to_numeric(main2_df['FX Rate_yoy_pct'], errors='coerce')

main2_df.to_csv('withoutGDP_Macrovars_with_orig_and_yoy.csv', index=False)
print("DataFrame 'main2_df' saved successfully to 'withoutGDP_Macrovars_with_orig_and_yoy.csv.csv'.")

DataFrame 'main2_df' saved successfully to 'withoutGDP_Macrovars_with_orig_and_yoy.csv.csv'.

In [ ]:
columns_to_drop = [
    'CPI',
    'Wholesale Price',
    'Industrial Production',
    'Intl Trade Merch Exports',
    'Intl Trade Merch Imports',
    'FX Rate'
]

# Drop the specified columns, ignoring errors if a column is already absent
main2_df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("Specified columns dropped successfully.")
main2_df.info()

Specified columns dropped successfully.
<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 649 to 961
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              312 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE          312 non-null    float64
 2   CPI_yoy_pct                       312 non-null    float64
 3   Wholesale Price_yoy_pct           312 non-null    float64
 4   Industrial Production_yoy_pct     312 non-null    float64
 5   Intl Trade Merch Exports_yoy_pct  312 non-null    float64
 6   Intl Trade Merch Imports_yoy_pct  312 non-null    float64
 7   FX Rate_yoy_pct                   312 non-null    float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 30.0 KB

In [ ]:
new_columns = {}
for col in main2_df.columns:
    # Only rename columns that are numeric (float or int) and end with '_yoy_pct'
    if col.endswith('_yoy_pct') and pd.api.types.is_numeric_dtype(main2_df[col]):
        new_columns[col] = col.replace('_yoy_pct', '')
main2_df.rename(columns=new_columns, inplace=True)

print("Columns renamed successfully by removing '_yoy_pct' suffix.")
main2_df.info()
main2_df

Columns renamed successfully by removing '_yoy_pct' suffix.
<class 'pandas.core.frame.DataFrame'>
Index: 312 entries, 649 to 961
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      312 non-null    datetime64[ns]
 1   INTERBANK CALL LOAN RATE  312 non-null    float64
 2   CPI                       312 non-null    float64
 3   Wholesale Price           312 non-null    float64
 4   Industrial Production     312 non-null    float64
 5   Intl Trade Merch Exports  312 non-null    float64
 6   Intl Trade Merch Imports  312 non-null    float64
 7   FX Rate                   312 non-null    float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 30.0 KB

,Date,INTERBANK CALL LOAN RATE,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
649,1999-02-01,12.623437,10.520235,8.203538,2.656146,9.744673,-23.949043,-4.044113
650,1999-03-01,12.282609,9.007978,6.878853,5.455860,11.205000,-15.831138,-0.239111
651,1999-04-01,11.090461,7.683616,6.967220,7.687034,9.368142,1.748419,-0.521337
652,1999-05-01,10.122024,7.086608,6.504064,13.020029,2.076156,5.168001,-3.711798
653,1999-06-01,9.525568,5.771366,5.628134,14.773573,9.614518,-6.975381,-6.187600
...,...,...,...,...,...,...,...,...
957,2024-10-01,6.244332,1.937047,1.973682,-6.966527,-8.713099,8.727526,0.901607
958,2024-11-01,6.159405,2.263543,2.118341,-1.599997,-3.973003,12.816407,5.164532
959,2024-12-01,6.086828,2.502016,2.261117,-4.130874,-3.839992,1.652797,5.145626
960,2025-01-01,5.895856,2.900886,2.696791,0.079971,2.981743,3.488013,4.320615
961,2025-02-01,5.923455,2.884608,2.911208,2.836625,14.402545,16.015169,3.619466

# save merged macrovars without GDP

In [ ]:
main2_df.to_csv('withoutGDP_Merged_macrovars.csv', index=False)