# Preprocessing

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re

In [2]:
# Loadiing the dataset

bsp = pd.read_csv("../00 Original Dataset/speech dataset/bsp_speeches/csv/bsp_speeches_1998_to_March 2020.csv")
bsp.info()
bsp

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 685 entries, 0 to 684
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Title     685 non-null    object
 1   Date      685 non-null    object
 2   Location  651 non-null    object
 3   Occasion  666 non-null    object
 4   Speaker   685 non-null    object
 5   Text      685 non-null    object
 6   Len       685 non-null    int64
 7   Link      685 non-null    object
dtypes: int64(1), object(7)
memory usage: 42.9+ KB

,Title,Date,Location,Occasion,Speaker,Text,Len,Link
0,Staying on Track in 2020: Sustaining Positive ...,03-03-2020,"Dusit Thani Manila, Makati City",The Manila Times 11th Business Forum,"BSP Governor Benjamin E. Diokno, Ph.D.","The Manila Times President and CEO, Mr. Dante ...",2442,https://www.bsp.gov.ph/SitePages/MediaAndResea...
1,Finding Opportunities in a Borderless World,28-02-2020,"El Nido, Palawan",13th Annual FMAP Convention,"BSP Governor Benjamin E. Diokno, Ph.D.",To the officers and members of the Fund Manage...,2672,https://www.bsp.gov.ph/SitePages/MediaAndResea...
2,Gearing up for the Road Ahead: With Foresight ...,27-02-2020,Sofitel Philippine Plaza Hotel,17th Professional Insurance and Financial Advi...,"BSP Governor Benjamin E. Diokno, Ph.D.",Officers and members of the Professional Insur...,2922,https://www.bsp.gov.ph/SitePages/MediaAndResea...
3,A Strong Nation Amid A Slowing and Volatile World,06-02-2020,"Shangri-La at the Fort, Taguig",General Membership Meeting and Economic Briefing,"BSP Governor Benjamin E. Diokno, Ph.D.",Officers and members of the Management Associa...,2177,https://www.bsp.gov.ph/SitePages/MediaAndResea...
4,Welcome Dinner Remarks,31-01-2020,Philippine International Convenion Center,BSP-BI Bilateral Meeting,"BSP Governor Benjamin E. Diokno, Ph.D.","Governor Perry, Deputy Governors, colleagues f...",357,https://www.bsp.gov.ph/SitePages/MediaAndResea...
...,...,...,...,...,...,...,...,...
680,BSP ON ITS 5TH YEAR ANNIVERSARY: MANAGING THE ...,03-07-1998,BSP Cafetorium,NaN,Governor Gabriel Singson,Our 5th anniversary celebrations today follow ...,1043,https://www.bsp.gov.ph/SitePages/MediaAndResea...
681,ON WITH THE ECONOMIC RECOVERY...CAREFULLY,28-05-1998,"Grand Ballroom, Hotel Intercontinental, Makati...",5th Monthly Business Meeting of the Chamber of...,Governor Gabriel Singson,I feel encouraged by the theme you have adopte...,1600,https://www.bsp.gov.ph/SitePages/MediaAndResea...
682,An Update on Recent Economic Developments,22-05-1998,"Peninsula Hotel, Makati City",Asia Society breakfast meeting,Governor Gabriel Singson,"For many months now, developments in Asia have...",1349,https://www.bsp.gov.ph/SitePages/MediaAndResea...
683,The Philippines: From Crisis to Recovery,07-04-1998,New York City,Financial Seminar Plenary Session,Governor Gabriel Singson,The current Asian financial crisis has put a v...,1319,https://www.bsp.gov.ph/SitePages/MediaAndResea...
684,Strategic Issues in Managing Capital Flows: Th...,10-03-1998,"ADB Headquarters, Pasig City",ADB-World Bank Senior Policy Seminar,Governor Gabriel Singson,The importance of implications of the internat...,1768,https://www.bsp.gov.ph/SitePages/MediaAndResea...

In [3]:
# Checking the number of null values for each column

nan_counts = bsp.isna().sum()
nan_counts

Title        0
Date         0
Location    34
Occasion    19
Speaker      0
Text         0
Len          0
Link         0
dtype: int64

In [4]:
print("Rows with missing values:")
bsp[bsp.isnull().any(axis=1)]

Rows with missing values:

,Title,Date,Location,Occasion,Speaker,Text,Len,Link
9,"The Philippine Economy in 2020: Looking Back, ...",09-01-2020,NaN,Rotary Club of Manila General Assembly,"BSP Governor Benjamin E. Diokno, Ph.D.",On behalf of the Bangko Sentral ng Pilipinas (...,3280,https://www.bsp.gov.ph/SitePages/MediaAndResea...
35,Opening Remarks,02-09-2019,NaN,Signing of Memorandum of Understanding between...,"BSP Governor Benjamin E. Diokno, Ph.D.","Prof. Ramayya Krishnan, Dean, Heinz College of...",537,https://www.bsp.gov.ph/SitePages/MediaAndResea...
36,The PH Economy: Sustaining Resilience Amid Unc...,27-08-2019,NaN,Economic Journalists? Association of the Phili...,"BSP Governor Benjamin E. Diokno, Ph.D.","Good morning, ladies and gentlemen. First, let...",1831,https://www.bsp.gov.ph/SitePages/MediaAndResea...
39,The Road to Financial Inclusion and Sustainabl...,16-08-2019,NaN,"Philippine Exporters Confederation, Inc. (PHIL...","BSP Governor Benjamin E. Diokno, Ph.D.","To Chairman Paterno Dizon, Dr. Sergio Ortiz-Lu...",2194,https://www.bsp.gov.ph/SitePages/MediaAndResea...
40,Philippines: Weaving an Unprecedented Growth S...,06-08-2019,NaN,Ayala Economic and Treasury Summit,"BSP Governor Benjamin E. Diokno, Ph.D.","Jaime, Fernando, other senior Ayala officials,...",2733,https://www.bsp.gov.ph/SitePages/MediaAndResea...
48,Sustained Partnerships in Financial Inclusion,18-06-2019,NaN,CMA Press Launch,Gov. Benjamin E. Diokno,"To my colleagues from BSP, partners from the M...",847,https://www.bsp.gov.ph/SitePages/MediaAndResea...
50,Sustaining the Philippine Growth Momentum,06-06-2019,NaN,Rotary Club of Manila Centennial Year,Governor Benjamin E. Diokno,"President Susing Pineda, fellow rotarians, fri...",2209,https://www.bsp.gov.ph/SitePages/MediaAndResea...
51,Ensuring Price Stability through Monetary Policy,17-05-2019,NaN,Breakfast Briefing with the Italian Chamber of...,Governor Benjamin E. Diokno,To the officers and members of the Italian Cha...,1780,https://www.bsp.gov.ph/SitePages/MediaAndResea...
139,Lessons from the Philippines: Financial stabil...,29-06-2017,NaN,NaN,"BSP Governor Amando M. Tetangco, Jr",Read Article,2,https://www.bsp.gov.ph/SitePages/MediaAndResea...
147,Learning from Instabilities to Build a Better ...,23-03-2017,NaN,Testimonial Dinner hosted by the PDS Group,"BSP Governor Amando M. Tetangco, Jr.",I am deeply honored and am very grateful to th...,1279,https://www.bsp.gov.ph/SitePages/MediaAndResea...
165,"Building on progress, Bringing in changes",30-08-2016,NaN,Development Budget Coordination Committee brie...,"Governor Amando M. Tetangco, Jr.","Senator Loren Legarda, chair of the Senate Com...",2131,https://www.bsp.gov.ph/SitePages/MediaAndResea...
167,Asset Management Growth: Recognizing Success a...,21-07-2016,NaN,FMAP 2016 Awards and Fellowship Night,"BSP Governor Amando M. Tetangco, Jr.",I am pleased to join you tonight as we recogni...,1065,https://www.bsp.gov.ph/SitePages/MediaAndResea...
192,Navigating Thru the Waters of Change...and But...,29-09-2015,NaN,2015 Annual Joint General Membership Meeting o...,Governor Amando M. Tetangco Jr.,I hope you share my view that meeting the six ...,2576,https://www.bsp.gov.ph/SitePages/MediaAndResea...
212,Financial Rehabilitation and Insolvency Regime...,17-03-2015,NaN,SharePHIL's Seminar:All You Need to Know About...,"Governor Amando M. Tetangco, Jr.",Good afternoon ladies and gentlemen. Let me be...,2124,https://www.bsp.gov.ph/SitePages/MediaAndResea...
232,Building a Collective Brand for the Banking In...,05-09-2014,NaN,40th anniversary celebration of the Bank Marke...,BSP Governor Amando M. Tetangco Jr.,Congratulations on your 40th anniversary! For ...,2528,https://www.bsp.gov.ph/SitePages/MediaAndResea...
234,Been There and Done That: Why This Would Not B...,20-08-2014,NaN,the50th Anniversary and 65th Foundation Year o...,"Governor Amando M. Tetangco, Jr.","On behalf of the Bangko Sentral ng Pilipinas, ...",1992,https://www.bsp.gov.ph/SitePages/MediaAndResea...
250,Continuing Growth Amidst Recurrent Risks and U...,09-01-2014,NaN,Joint Meeting of the Rotary Club of Manila and...,Governor Amando M. Tetangco Jr.,Rotary Club of Manila (RCM) President Rudy Bed...,2639,https://www.bsp.gov.ph/SitePages/MediaAndResea...
264,Ugaliing mag-impok,01-07-2013,NaN,National Savings Consciousness Week 2013,Joint message of Education Secretary Br Armin ...,(Joint message of Education Secretary Br Armin...,284,https://www.bsp.gov.ph/SitePages/MediaAndResea...
291,Financial Stability and Financial Inclusion: T...,07-02-2012,NaN,Keynote remarks for the session on Financial S...,Governor Amando M. Tetangco Jr.,"Officials of the Asian Development Bank, resou...",1966,https://www.bsp.gov.ph/SitePages/MediaAndResea...
301,The Philippines: Vision Toward Sustained Rapid...,06-01-2011,"Manila Polo Club, McKinley Hall, McKinley Road...",NaN,"Governor Amando M. Tetangco, Jr",Officers and members of the Rotary Club (RC) o...,1975,https://www.bsp.gov.ph/SitePages/MediaAndResea...
302,Remarks for the Foreign Correspondents Associa...,17-11-2010,NaN,Foreign Correspondents Association of the Phil...,"BSP Governor Amando M. Tetangco, Jr.","Good morning, ladies and gentlemen. I am grate...",1420,https://www.bsp.gov.ph/SitePages/MediaAndResea...
305,12th Credit Surety Fund is in Albay,12-08-2010,Legaspi City,NaN,"Governor Amando M. Tetangco, Jr.","Governor Joey Salceda, distinguished leaders o...",746,https://www.bsp.gov.ph/SitePages/MediaAndResea...
320,Moving the Economy Forward Through Banking,12-03-2010,NaN,Annual Convention of the Chamber of Thrift Banks,"Governor Amando M. Tetangco, Jr.","Mr. Pascual M. Garcia III, President of the Ch...",1653,https://www.bsp.gov.ph/SitePages/MediaAndResea...
331,The Philippine Economy: Facing Up to the Chall...,11-08-2009,Shangri-La Makati,NaN,Governor Amando M. Tetangco Jr.,"Executive Director Robert Sears, executives of...",2906,https://www.bsp.gov.ph/SitePages/MediaAndResea...
336,Developing a New Generation of Savers with the...,03-07-2009,NaN,NaN,"Governor Amando M. Tetangco, Jr.","Former BSP Governor Gabriel Singson, Monetary ...",592,https://www.bsp.gov.ph/SitePages/MediaAndResea...
366,Recent Market Volatility: Implication for Phil...,29-09-2008,NaN,Public Hearing of Senate Committee on Banks,"Governor Amando M. Tetangco, Jr.","Mr. Chairman, members of the Committee, Senato...",2757,https://www.bsp.gov.ph/SitePages/MediaAndResea...
370,Closing Remarks,23-08-2008,NaN,BSP's Mid-year Organizational Performance Revi...,"Governor Amando M. Tetangco, Jr.","Members of the Monetary Board, fellow central ...",980,https://www.bsp.gov.ph/SitePages/MediaAndResea...
372,Remarks,23-07-2008,NaN,Foreign Correspondents Association of the Phil...,"Governor Amando M. Tetangco, Jr.",Ladies and gentlemen of the Foreign Correspond...,1567,https://www.bsp.gov.ph/SitePages/MediaAndResea...
377,Bangko Sentral ng Pilipinas @15,03-07-2008,NaN,Anniversary Dinner,"Governor Amando M. Tetangco, Jr.","Senator Angara, Representative Jaime Lopez, fe...",1270,https://www.bsp.gov.ph/SitePages/MediaAndResea...
383,Recent Economic Developments: Challenges and P...,13-02-2008,NaN,Fund Managers Association of the Philippines' ...,"Governor Amando M. Tetangco, Jr.","President PJ Garcia, other officers and member...",2225,https://www.bsp.gov.ph/SitePages/MediaAndResea...
385,The Philippines: MACROECONOMIC OUTLOOK FOR 2008,11-02-2008,NaN,Oath-taking of the officers and directors of t...,"Governor Amando M. Tetangco, Jr.","President Donna Gatdula, other distinguished o...",1702,https://www.bsp.gov.ph/SitePages/MediaAndResea...
390,Pushing Ahead Through Headwinds,03-01-2008,NaN,Regular membership meeting of the Rotary Club ...,"Governor Amando M. Tetangco, Jr.",Distinguished officers and members of the Rota...,2374,https://www.bsp.gov.ph/SitePages/MediaAndResea...
397,BSP's Tulong Barya Para sa Gawad Kalinga,31-07-2007,NaN,NaN,"Governor Amando M. Tetangco, Jr.",Magandang hapon po sa inyong lahat! After lear...,453,https://www.bsp.gov.ph/SitePages/MediaAndResea...
441,"Welcome Remarks For The Meeting On ""Restoring ...",05-06-2006,NaN,"Meeting Room, Executive Business Center, BSP","Governor Amando M. Tetangco, Jr.","Mrs. Narda Camacho, Dr. Ester Ogena, and Mrs. ...",297,https://www.bsp.gov.ph/SitePages/MediaAndResea...
529,Christmas Message,18-12-2003,PICC,NaN,Governor Rafael Buenaventura,"Good afternoon, fellow workers at the Bangko S...",518,https://www.bsp.gov.ph/SitePages/MediaAndResea...
551,Official Launch and Inauguration of The PICC F...,03-07-2003,"PICC, Manila",NaN,Governor Rafael Buenaventura,"Secretary Gordon, special guests, friends, lad...",357,https://www.bsp.gov.ph/SitePages/MediaAndResea...
560,The First Citibank Microentreprenuer of the Ye...,19-11-2002,"Metropolitan Museum, BSP Complex, Manila",NaN,Governor Rafael Buenaventura,Magandang hapon po sa inyong lahat. I must say...,1168,https://www.bsp.gov.ph/SitePages/MediaAndResea...
634,Moving The Financial Markets Forward,20-11-2000,NaN,Joint General Membership Meeting ACI Philippines,Governor Rafael Buenaventura,I. Introduction Officers and members of ACI Ph...,1884,https://www.bsp.gov.ph/SitePages/MediaAndResea...
637,An Update on the Monetary Situation,30-10-2000,"Canadian Chamber of Commerce, Shangri-La Hotel...",NaN,Governor Rafael Buenaventura,It is always a pleasure to break bread with th...,1420,https://www.bsp.gov.ph/SitePages/MediaAndResea...
638,An Update on the Foreign Exchange Situation,26-10-2000,"Makati Business Club, Dusit Nikko Hotel, Makat...",NaN,Governor Rafael Buenaventura,I take great pleasure in joining the officers ...,1377,https://www.bsp.gov.ph/SitePages/MediaAndResea...
641,The Philippines: Recent Economic Development a...,06-09-2000,"Rotary Club of Makati, Makati City",NaN,Governor Rafael Buenaventura,"Introduction Ladies and gentlemen, good mornin...",1576,https://www.bsp.gov.ph/SitePages/MediaAndResea...
644,Closing Address: SEACEN Workshop on Concepts a...,07-07-2000,"Ilustrado, Intramuros, Manila",NaN,Governor Rafael Buenaventura,"Monetary Board member Vicente B. Valdepeñas, J...",670,https://www.bsp.gov.ph/SitePages/MediaAndResea...
646,The BSP in the New Millennium,03-07-2000,NaN,7th Anniversary of the Bangko Sentral ng Pilip...,Governor Rafael Buenaventura,This is a special day for me. This is the firs...,1013,https://www.bsp.gov.ph/SitePages/MediaAndResea...
647,BSP Dividend Remittance fir 1999: P2.97 Billion,03-07-2000,"Malacañang Palace, Manila",NaN,Governor Rafael Buenaventura,"Mr. President, it is my immense privilege to p...",548,https://www.bsp.gov.ph/SitePages/MediaAndResea...
648,The Philippines: Recent Economic Developments,23-06-2000,"Hong Kong and Shanghai Corporation, Shangri-La...",NaN,Governor Rafael Buenaventura,"Ladies and gentlemen, good afternoon. It is in...",1777,https://www.bsp.gov.ph/SitePages/MediaAndResea...
649,Speaking Notes,14-06-2000,"Greenhills Walking Corporation, Restaurante La...",NaN,Governor Rafael Buenaventura,Today I would like to offer my views on some o...,1264,https://www.bsp.gov.ph/SitePages/MediaAndResea...
651,Open Conference on Corporate Governance,29-05-2000,"Institute of Corporate Directors, Peninsula Ho...",NaN,Governor Rafael Buenaventura,"Distinguished officers, fellow professionals, ...",752,https://www.bsp.gov.ph/SitePages/MediaAndResea...
674,The Philippine Economy: Turning the Corner,17-08-1999,NaN,NaN,Governor Rafael Buenaventura,Introduction Officers and members of the Manil...,1941,https://www.bsp.gov.ph/SitePages/MediaAndResea...
680,BSP ON ITS 5TH YEAR ANNIVERSARY: MANAGING THE ...,03-07-1998,BSP Cafetorium,NaN,Governor Gabriel Singson,Our 5th anniversary celebrations today follow ...,1043,https://www.bsp.gov.ph/SitePages/MediaAndResea...

In [5]:
# Replacing missing values with "unknown"

bsp.fillna("unknown", inplace=True)

print("Rows with 'unknown' value after replacement:")
bsp[bsp.eq("unknown").any(axis=1)]

Rows with 'unknown' value after replacement:

,Title,Date,Location,Occasion,Speaker,Text,Len,Link
9,"The Philippine Economy in 2020: Looking Back, ...",09-01-2020,unknown,Rotary Club of Manila General Assembly,"BSP Governor Benjamin E. Diokno, Ph.D.",On behalf of the Bangko Sentral ng Pilipinas (...,3280,https://www.bsp.gov.ph/SitePages/MediaAndResea...
35,Opening Remarks,02-09-2019,unknown,Signing of Memorandum of Understanding between...,"BSP Governor Benjamin E. Diokno, Ph.D.","Prof. Ramayya Krishnan, Dean, Heinz College of...",537,https://www.bsp.gov.ph/SitePages/MediaAndResea...
36,The PH Economy: Sustaining Resilience Amid Unc...,27-08-2019,unknown,Economic Journalists? Association of the Phili...,"BSP Governor Benjamin E. Diokno, Ph.D.","Good morning, ladies and gentlemen. First, let...",1831,https://www.bsp.gov.ph/SitePages/MediaAndResea...
39,The Road to Financial Inclusion and Sustainabl...,16-08-2019,unknown,"Philippine Exporters Confederation, Inc. (PHIL...","BSP Governor Benjamin E. Diokno, Ph.D.","To Chairman Paterno Dizon, Dr. Sergio Ortiz-Lu...",2194,https://www.bsp.gov.ph/SitePages/MediaAndResea...
40,Philippines: Weaving an Unprecedented Growth S...,06-08-2019,unknown,Ayala Economic and Treasury Summit,"BSP Governor Benjamin E. Diokno, Ph.D.","Jaime, Fernando, other senior Ayala officials,...",2733,https://www.bsp.gov.ph/SitePages/MediaAndResea...
48,Sustained Partnerships in Financial Inclusion,18-06-2019,unknown,CMA Press Launch,Gov. Benjamin E. Diokno,"To my colleagues from BSP, partners from the M...",847,https://www.bsp.gov.ph/SitePages/MediaAndResea...
50,Sustaining the Philippine Growth Momentum,06-06-2019,unknown,Rotary Club of Manila Centennial Year,Governor Benjamin E. Diokno,"President Susing Pineda, fellow rotarians, fri...",2209,https://www.bsp.gov.ph/SitePages/MediaAndResea...
51,Ensuring Price Stability through Monetary Policy,17-05-2019,unknown,Breakfast Briefing with the Italian Chamber of...,Governor Benjamin E. Diokno,To the officers and members of the Italian Cha...,1780,https://www.bsp.gov.ph/SitePages/MediaAndResea...
139,Lessons from the Philippines: Financial stabil...,29-06-2017,unknown,unknown,"BSP Governor Amando M. Tetangco, Jr",Read Article,2,https://www.bsp.gov.ph/SitePages/MediaAndResea...
147,Learning from Instabilities to Build a Better ...,23-03-2017,unknown,Testimonial Dinner hosted by the PDS Group,"BSP Governor Amando M. Tetangco, Jr.",I am deeply honored and am very grateful to th...,1279,https://www.bsp.gov.ph/SitePages/MediaAndResea...
165,"Building on progress, Bringing in changes",30-08-2016,unknown,Development Budget Coordination Committee brie...,"Governor Amando M. Tetangco, Jr.","Senator Loren Legarda, chair of the Senate Com...",2131,https://www.bsp.gov.ph/SitePages/MediaAndResea...
167,Asset Management Growth: Recognizing Success a...,21-07-2016,unknown,FMAP 2016 Awards and Fellowship Night,"BSP Governor Amando M. Tetangco, Jr.",I am pleased to join you tonight as we recogni...,1065,https://www.bsp.gov.ph/SitePages/MediaAndResea...
192,Navigating Thru the Waters of Change...and But...,29-09-2015,unknown,2015 Annual Joint General Membership Meeting o...,Governor Amando M. Tetangco Jr.,I hope you share my view that meeting the six ...,2576,https://www.bsp.gov.ph/SitePages/MediaAndResea...
212,Financial Rehabilitation and Insolvency Regime...,17-03-2015,unknown,SharePHIL's Seminar:All You Need to Know About...,"Governor Amando M. Tetangco, Jr.",Good afternoon ladies and gentlemen. Let me be...,2124,https://www.bsp.gov.ph/SitePages/MediaAndResea...
232,Building a Collective Brand for the Banking In...,05-09-2014,unknown,40th anniversary celebration of the Bank Marke...,BSP Governor Amando M. Tetangco Jr.,Congratulations on your 40th anniversary! For ...,2528,https://www.bsp.gov.ph/SitePages/MediaAndResea...
234,Been There and Done That: Why This Would Not B...,20-08-2014,unknown,the50th Anniversary and 65th Foundation Year o...,"Governor Amando M. Tetangco, Jr.","On behalf of the Bangko Sentral ng Pilipinas, ...",1992,https://www.bsp.gov.ph/SitePages/MediaAndResea...
250,Continuing Growth Amidst Recurrent Risks and U...,09-01-2014,unknown,Joint Meeting of the Rotary Club of Manila and...,Governor Amando M. Tetangco Jr.,Rotary Club of Manila (RCM) President Rudy Bed...,2639,https://www.bsp.gov.ph/SitePages/MediaAndResea...
264,Ugaliing mag-impok,01-07-2013,unknown,National Savings Consciousness Week 2013,Joint message of Education Secretary Br Armin ...,(Joint message of Education Secretary Br Armin...,284,https://www.bsp.gov.ph/SitePages/MediaAndResea...
291,Financial Stability and Financial Inclusion: T...,07-02-2012,unknown,Keynote remarks for the session on Financial S...,Governor Amando M. Tetangco Jr.,"Officials of the Asian Development Bank, resou...",1966,https://www.bsp.gov.ph/SitePages/MediaAndResea...
301,The Philippines: Vision Toward Sustained Rapid...,06-01-2011,"Manila Polo Club, McKinley Hall, McKinley Road...",unknown,"Governor Amando M. Tetangco, Jr",Officers and members of the Rotary Club (RC) o...,1975,https://www.bsp.gov.ph/SitePages/MediaAndResea...
302,Remarks for the Foreign Correspondents Associa...,17-11-2010,unknown,Foreign Correspondents Association of the Phil...,"BSP Governor Amando M. Tetangco, Jr.","Good morning, ladies and gentlemen. I am grate...",1420,https://www.bsp.gov.ph/SitePages/MediaAndResea...
305,12th Credit Surety Fund is in Albay,12-08-2010,Legaspi City,unknown,"Governor Amando M. Tetangco, Jr.","Governor Joey Salceda, distinguished leaders o...",746,https://www.bsp.gov.ph/SitePages/MediaAndResea...
320,Moving the Economy Forward Through Banking,12-03-2010,unknown,Annual Convention of the Chamber of Thrift Banks,"Governor Amando M. Tetangco, Jr.","Mr. Pascual M. Garcia III, President of the Ch...",1653,https://www.bsp.gov.ph/SitePages/MediaAndResea...
331,The Philippine Economy: Facing Up to the Chall...,11-08-2009,Shangri-La Makati,unknown,Governor Amando M. Tetangco Jr.,"Executive Director Robert Sears, executives of...",2906,https://www.bsp.gov.ph/SitePages/MediaAndResea...
336,Developing a New Generation of Savers with the...,03-07-2009,unknown,unknown,"Governor Amando M. Tetangco, Jr.","Former BSP Governor Gabriel Singson, Monetary ...",592,https://www.bsp.gov.ph/SitePages/MediaAndResea...
366,Recent Market Volatility: Implication for Phil...,29-09-2008,unknown,Public Hearing of Senate Committee on Banks,"Governor Amando M. Tetangco, Jr.","Mr. Chairman, members of the Committee, Senato...",2757,https://www.bsp.gov.ph/SitePages/MediaAndResea...
370,Closing Remarks,23-08-2008,unknown,BSP's Mid-year Organizational Performance Revi...,"Governor Amando M. Tetangco, Jr.","Members of the Monetary Board, fellow central ...",980,https://www.bsp.gov.ph/SitePages/MediaAndResea...
372,Remarks,23-07-2008,unknown,Foreign Correspondents Association of the Phil...,"Governor Amando M. Tetangco, Jr.",Ladies and gentlemen of the Foreign Correspond...,1567,https://www.bsp.gov.ph/SitePages/MediaAndResea...
377,Bangko Sentral ng Pilipinas @15,03-07-2008,unknown,Anniversary Dinner,"Governor Amando M. Tetangco, Jr.","Senator Angara, Representative Jaime Lopez, fe...",1270,https://www.bsp.gov.ph/SitePages/MediaAndResea...
383,Recent Economic Developments: Challenges and P...,13-02-2008,unknown,Fund Managers Association of the Philippines' ...,"Governor Amando M. Tetangco, Jr.","President PJ Garcia, other officers and member...",2225,https://www.bsp.gov.ph/SitePages/MediaAndResea...
385,The Philippines: MACROECONOMIC OUTLOOK FOR 2008,11-02-2008,unknown,Oath-taking of the officers and directors of t...,"Governor Amando M. Tetangco, Jr.","President Donna Gatdula, other distinguished o...",1702,https://www.bsp.gov.ph/SitePages/MediaAndResea...
390,Pushing Ahead Through Headwinds,03-01-2008,unknown,Regular membership meeting of the Rotary Club ...,"Governor Amando M. Tetangco, Jr.",Distinguished officers and members of the Rota...,2374,https://www.bsp.gov.ph/SitePages/MediaAndResea...
397,BSP's Tulong Barya Para sa Gawad Kalinga,31-07-2007,unknown,unknown,"Governor Amando M. Tetangco, Jr.",Magandang hapon po sa inyong lahat! After lear...,453,https://www.bsp.gov.ph/SitePages/MediaAndResea...
441,"Welcome Remarks For The Meeting On ""Restoring ...",05-06-2006,unknown,"Meeting Room, Executive Business Center, BSP","Governor Amando M. Tetangco, Jr.","Mrs. Narda Camacho, Dr. Ester Ogena, and Mrs. ...",297,https://www.bsp.gov.ph/SitePages/MediaAndResea...
529,Christmas Message,18-12-2003,PICC,unknown,Governor Rafael Buenaventura,"Good afternoon, fellow workers at the Bangko S...",518,https://www.bsp.gov.ph/SitePages/MediaAndResea...
551,Official Launch and Inauguration of The PICC F...,03-07-2003,"PICC, Manila",unknown,Governor Rafael Buenaventura,"Secretary Gordon, special guests, friends, lad...",357,https://www.bsp.gov.ph/SitePages/MediaAndResea...
560,The First Citibank Microentreprenuer of the Ye...,19-11-2002,"Metropolitan Museum, BSP Complex, Manila",unknown,Governor Rafael Buenaventura,Magandang hapon po sa inyong lahat. I must say...,1168,https://www.bsp.gov.ph/SitePages/MediaAndResea...
634,Moving The Financial Markets Forward,20-11-2000,unknown,Joint General Membership Meeting ACI Philippines,Governor Rafael Buenaventura,I. Introduction Officers and members of ACI Ph...,1884,https://www.bsp.gov.ph/SitePages/MediaAndResea...
637,An Update on the Monetary Situation,30-10-2000,"Canadian Chamber of Commerce, Shangri-La Hotel...",unknown,Governor Rafael Buenaventura,It is always a pleasure to break bread with th...,1420,https://www.bsp.gov.ph/SitePages/MediaAndResea...
638,An Update on the Foreign Exchange Situation,26-10-2000,"Makati Business Club, Dusit Nikko Hotel, Makat...",unknown,Governor Rafael Buenaventura,I take great pleasure in joining the officers ...,1377,https://www.bsp.gov.ph/SitePages/MediaAndResea...
641,The Philippines: Recent Economic Development a...,06-09-2000,"Rotary Club of Makati, Makati City",unknown,Governor Rafael Buenaventura,"Introduction Ladies and gentlemen, good mornin...",1576,https://www.bsp.gov.ph/SitePages/MediaAndResea...
644,Closing Address: SEACEN Workshop on Concepts a...,07-07-2000,"Ilustrado, Intramuros, Manila",unknown,Governor Rafael Buenaventura,"Monetary Board member Vicente B. Valdepeñas, J...",670,https://www.bsp.gov.ph/SitePages/MediaAndResea...
646,The BSP in the New Millennium,03-07-2000,unknown,7th Anniversary of the Bangko Sentral ng Pilip...,Governor Rafael Buenaventura,This is a special day for me. This is the firs...,1013,https://www.bsp.gov.ph/SitePages/MediaAndResea...
647,BSP Dividend Remittance fir 1999: P2.97 Billion,03-07-2000,"Malacañang Palace, Manila",unknown,Governor Rafael Buenaventura,"Mr. President, it is my immense privilege to p...",548,https://www.bsp.gov.ph/SitePages/MediaAndResea...
648,The Philippines: Recent Economic Developments,23-06-2000,"Hong Kong and Shanghai Corporation, Shangri-La...",unknown,Governor Rafael Buenaventura,"Ladies and gentlemen, good afternoon. It is in...",1777,https://www.bsp.gov.ph/SitePages/MediaAndResea...
649,Speaking Notes,14-06-2000,"Greenhills Walking Corporation, Restaurante La...",unknown,Governor Rafael Buenaventura,Today I would like to offer my views on some o...,1264,https://www.bsp.gov.ph/SitePages/MediaAndResea...
651,Open Conference on Corporate Governance,29-05-2000,"Institute of Corporate Directors, Peninsula Ho...",unknown,Governor Rafael Buenaventura,"Distinguished officers, fellow professionals, ...",752,https://www.bsp.gov.ph/SitePages/MediaAndResea...
674,The Philippine Economy: Turning the Corner,17-08-1999,unknown,unknown,Governor Rafael Buenaventura,Introduction Officers and members of the Manil...,1941,https://www.bsp.gov.ph/SitePages/MediaAndResea...
680,BSP ON ITS 5TH YEAR ANNIVERSARY: MANAGING THE ...,03-07-1998,BSP Cafetorium,unknown,Governor Gabriel Singson,Our 5th anniversary celebrations today follow ...,1043,https://www.bsp.gov.ph/SitePages/MediaAndResea...

In [6]:
# Checking the unique values of the 'Speaker' column

bsp['Speaker'].unique()

array(['BSP Governor Benjamin E. Diokno, Ph.D.',
       'Governor Benjamin E. Diokno', 'BSP Governor Benjamin E. Diokno',
       'Gov. Benjamin E. Diokno', 'BSP Governor Benjamin Diokno',
       'Former BSP Governor Amando M. Tetangco Jr.',
       'BSP OIC Maria Almasara Cyd N. Tuano-Amador',
       'BSP Governor Nestor A. Espenilla, Jr., as delivered by BSP Deputy Governor Chuchi G. Fonacier',
       'Governor Nestor A. Espenilla, Jr. delivered by Officer-in-Charge Chuchi G. Fonacier',
       'Governor Nestor A. Espenilla, Jr., as delivered by Deputy Governor Diwa C. Guinigundo',
       'BSP Governor Nestor A. Espenilla, Jr., as delivered by Deputy Governor Chuchi G. Fonacier,',
       'Governor Nestor A. Espenilla, Jr., as delivered by MBM Peter B. Favila',
       'Governor Nestor A. Espenilla, Jr. delivered by Deputy Governor Maria Almasara Cyd N. Tuano-Amador',
       'Deputy Governor Chuchi G. Fonancier, FSS on behalf of Governor Nestor A. Espenilla, Jr.',
       'BSP Governor Nestor A. Espenilla, Jr.',
       'Deputy Governor Chuchi G. Fonacier',
       'Governor Nestor A. Espenilla, Jr.',
       'Officer-In-Charge Maria Almasara Cyd N. Tua?o-Amador',
       'BSP Deputy Governor Chuchi G. Fonacier on behalf of Governor Nestor A. Espenilla, Jr.',
       'by Governor Nestor A. Espenilla, Jr.,',
       'Deputy Governor Chuchi G. Fonacier on behalf of Governor Nestor A. Espenilla, Jr.',
       'BSP Gov. Nestor A. Espenilla, Jr.', 'Nestor A. Espenilla, Jr.',
       'Former BSP Governor Amando M. Tetangco, Jr.',
       'BSP Governor Amando M. Tetangco, Jr',
       'Governor Amando M. Tetangco, Jr.',
       'BSP Governor Amando M. Tetangco, Jr.',
       'BSP Gov. Amando M. Tetangco, Jr.',
       'Bangko Sentral ng Pilipinas Governor Amando M. Tetangco, Jr.',
       'Governor Amando M. Tetangco Jr.',
       'Governor Amando M. Tetangco, Jr',
       'BSP Gov Amando M. Tetangco, Jr.',
       'BSP Governor Amando M. Tetangco Jr.',
       'Gov. Amando M. Tetangco, Jr.',
       'Governor Governor Amando M. Tetangco, Jr.',
       'Joint message of Education Secretary Br Armin Luistro FSC and BSP Governor Amando Tetangco, Jr.',
       'Gov. Amando M. Tetangco, Jr', 'Gov. Amando M. Tetangco Jr.',
       'Governor Amando A. Tetangco, Jr',
       'Officer-In-Charge Diwa C. Guinigundo',
       'Governor. Amando M. Tetangco, Jr.',
       'Governor Amando Tetangco, Jr.', 'Governor Amando M. Tetangco,Jr.',
       'Deputy Governor Diwa C. Guinigundo',
       'Governor Rafael Buenaventura', 'Deputy Governor Alberto V. Reyes',
       'Governor Gabriel Singson'], dtype=object)

### Standardize Speaker Column

In [7]:
def process_speaker_data(df):
    raw_speakers = df['Speaker'].copy()

    # STAGE 1: ROLE EXTRACTION
    def extract_role_at_time(s):
        s = str(s).lower()
        # 1. Handle "delivered by" (Author is at the start)
        base_text = s.split('delivered')[0] if 'delivered' in s else s
        # 2. Handle "on behalf of" (Author is at the end)
        base_text = base_text.split('on behalf of')[-1] if 'on behalf of' in base_text else base_text
        
        if 'former' in base_text: return 'Former Governor'
        if 'oic' in base_text or 'officer-in-charge' in base_text: return 'Officer-in-Charge'
        if 'deputy governor' in base_text: return 'Deputy Governor'
        if 'governor' in base_text or 'gov.' in base_text: return 'Governor'
        return 'Other'

    df['Role'] = raw_speakers.apply(extract_role_at_time)

    # STAGE 2: SPEAKER NAME CLEANING
    def get_clean_part(s):
        s = str(s).lower()
        part = s.split('delivered')[0] if 'delivered' in s else s
        part = part.split('on behalf of')[-1] if 'on behalf of' in part else part
        part = part.split(' and ')[-1] if 'joint message' in part else part
        return part.strip()

    clean_names = raw_speakers.apply(get_clean_part)

    # Stripping Titles
    titles_pattern = r'|'.join([
        r'^bsp\s+', r'^gov\.\s+', r'^governor\s+', r'^deputy\s+governor\s+', 
        r'^officer-in-charge\s+', r'^oic\s+', r'^former\s+', r'^mbm\s+',
        r'^bangko\s+sentral\s+ng\s+pilipinas\s+governor\s+', r'^by\s+',
        r'^\.\s*', r',\s*ph\.d\.?$', r',\s*as$'
    ])
    clean_names = clean_names.str.replace(titles_pattern, '', regex=True, flags=re.IGNORECASE).str.strip()

    # Final Unified Mapping
    def finalize_author_name(name):
        n = str(name).lower()
        if 'diokno' in n: return 'Benjamin E. Diokno'
        if 'tetangco' in n: return 'Amando M. Tetangco, Jr.'
        if 'espenilla' in n: return 'Nestor A. Espenilla, Jr.'
        if 'tuano-amador' in n or 'tua?o-amador' in n: return 'Maria Almasara Cyd N. Tuano-Amador'
        if 'guinigundo' in n: return 'Diwa C. Guinigundo'
        if 'buenaventura' in n: return 'Rafael Buenaventura'
        if 'singson' in n: return 'Gabriel Singson'
        return name.title()

    df['Speaker'] = clean_names.apply(finalize_author_name)

    # STAGE 3: SURNAME EXTRACTION
    suffixes = ['jr', 'jr.', 'ph.d', 'ph.d.', 'iii', 'ii', 'fss', 'as']
    
    def extract_surname(name):
        if not name: return None
        # Replace comma with space to catch "Tetangco,Jr"
        parts = str(name).replace(',', ' ').split()
        for word in reversed(parts):
            if word.lower().strip('.') not in suffixes:
                return word
        return parts[-1]

    df['last_name'] = df['Speaker'].apply(extract_surname)
    
    return df

bsp = process_speaker_data(bsp)
print(bsp[['Speaker', 'Role', 'last_name']].drop_duplicates())

                                Speaker               Role     last_name
0                    Benjamin E. Diokno           Governor        Diokno
57              Amando M. Tetangco, Jr.    Former Governor      Tetangco
58   Maria Almasara Cyd N. Tuano-Amador  Officer-in-Charge  Tuano-Amador
59             Nestor A. Espenilla, Jr.           Governor     Espenilla
73                   Chuchi G. Fonacier    Deputy Governor      Fonacier
108            Nestor A. Espenilla, Jr.              Other     Espenilla
139             Amando M. Tetangco, Jr.           Governor      Tetangco
208             Amando M. Tetangco, Jr.              Other      Tetangco
337                  Diwa C. Guinigundo  Officer-in-Charge    Guinigundo
466                  Diwa C. Guinigundo    Deputy Governor    Guinigundo
470                 Rafael Buenaventura           Governor  Buenaventura
477                    Alberto V. Reyes    Deputy Governor         Reyes
672                     Gabriel Singson           Governor       Singson

In [9]:
# Set pandas to show the full content of every cell
pd.set_option('display.max_colwidth', None)

# Filter for the 'Other' instances again
manual_lookup = bsp[bsp['Role'] == 'Other'][['Date', 'Speaker', 'Role', 'Link']]

print("Speeches requiring manual role verification:")
display(manual_lookup)

# Reset the option back to default
pd.reset_option('display.max_colwidth')

Speeches requiring manual role verification:

,Date,Speaker,Role,Link
108,21-11-2017,"Nestor A. Espenilla, Jr.",Other,https://www.bsp.gov.ph/SitePages/MediaAndResearch/SpeechesDisp.aspx?ItemId=574
208,20-05-2015,"Amando M. Tetangco, Jr.",Other,https://www.bsp.gov.ph/SitePages/MediaAndResearch/SpeechesDisp.aspx?ItemId=478

In [10]:
# Fix Role value after browsing the net
bsp.loc[108, 'Role'] = 'Governor' 
bsp.loc[208, 'Role'] = 'Governor'

# Verify that no 'Other' roles remain
print(bsp['Role'].value_counts())

Role
Governor             677
Officer-in-Charge      3
Deputy Governor        3
Former Governor        2
Name: count, dtype: int64

In [11]:
bsp.groupby('last_name').size()

last_name
Buenaventura    204
Diokno           57
Espenilla        77
Fonacier          1
Guinigundo        2
Reyes             1
Singson          10
Tetangco        331
Tuano-Amador      2
dtype: int64

In [12]:
# Extracting the year components of the 'Date' column and storing it to the new column called 'year'

bsp['Date'] = pd.to_datetime(bsp['Date'], dayfirst=True)
bsp['year'] = bsp['Date'].dt.year
bsp.head()

,Title,Date,Location,Occasion,Speaker,Text,Len,Link,Role,last_name,year
0,Staying on Track in 2020: Sustaining Positive ...,2020-03-03,"Dusit Thani Manila, Makati City",The Manila Times 11th Business Forum,Benjamin E. Diokno,"The Manila Times President and CEO, Mr. Dante ...",2442,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2020
1,Finding Opportunities in a Borderless World,2020-02-28,"El Nido, Palawan",13th Annual FMAP Convention,Benjamin E. Diokno,To the officers and members of the Fund Manage...,2672,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2020
2,Gearing up for the Road Ahead: With Foresight ...,2020-02-27,Sofitel Philippine Plaza Hotel,17th Professional Insurance and Financial Advi...,Benjamin E. Diokno,Officers and members of the Professional Insur...,2922,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2020
3,A Strong Nation Amid A Slowing and Volatile World,2020-02-06,"Shangri-La at the Fort, Taguig",General Membership Meeting and Economic Briefing,Benjamin E. Diokno,Officers and members of the Management Associa...,2177,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2020
4,Welcome Dinner Remarks,2020-01-31,Philippine International Convenion Center,BSP-BI Bilateral Meeting,Benjamin E. Diokno,"Governor Perry, Deputy Governors, colleagues f...",357,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2020

In [13]:
# Checking speeches with the same text

bsp[bsp.duplicated(subset='Text', keep=False)]

,Title,Date,Location,Occasion,Speaker,Text,Len,Link,Role,last_name,year
29,The Philippine Economy: Sustaining Resilience ...,2019-09-24,"Fairmont Hotel, Makati",Philippines Investment Forum (Euromoney),Benjamin E. Diokno,"Mr. Tony Shale, Euromoney executives, colleagu...",2414,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2019
30,The Philippine Economy: Sustaining Resilience ...,2019-09-24,"Fairmont Hotel, Makati",Philippines Investment Forum (Euromoney),Benjamin E. Diokno,"Mr. Tony Shale, Euromoney executives, colleagu...",2414,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2019
55,Policy Continuity and Institutional Independence,2019-03-08,BSP Executive Business Center,Press Conference,Benjamin E. Diokno,Good morning. I am happy to be with you all to...,922,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2019
56,Policy Continuity and Institutional Independence,2019-03-08,BSP Executive Business Center,Press Conference held at the BSP Executive Bus...,Benjamin E. Diokno,Good morning. I am happy to be with you all to...,922,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Diokno,2019
98,"Continuity Plus-Plus, Staying Ahead of the Curves",2018-01-19,"Fort San Antonio Abad, Bangko Sentral ng Pilip...",Annual Reception for the Banking Community,"Nestor A. Espenilla, Jr.",Good evening. It is my honor and pleasure to w...,1244,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Espenilla,2018
99,"Continuity Plus Plus, Staying Ahead of the Curves",2018-01-19,"Fort San Antonio Abad, Bangko Sentral ng Pilip...",Annual Reception for the Banking Community,"Nestor A. Espenilla, Jr.",Good evening. It is my honor and pleasure to w...,1244,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Espenilla,2018
308,Moving Central Banking Forward Through the Leg...,2010-07-27,"Executive Business Center, BSP",Launching of the Legal Book on RA 7653,"Amando M. Tetangco, Jr.",The honorable members of the judicial and the ...,728,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Tetangco,2010
310,Moving Central Banking Forward Through the Leg...,2010-07-27,"Executive Business Center, BSP",Book Launching of the Legal Book on RA 7653,"Amando M. Tetangco, Jr.",The honorable members of the judicial and the ...,728,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Tetangco,2010
556,Strengthening Links with Our Partners at PNP,2003-01-13,"Camp Crame, Quezon City","Flag Raising Ceremony, Philippine National Police",Rafael Buenaventura,Introduction Good morning ladies and gentlemen...,1785,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Buenaventura,2003
557,New Year's Message 2003,2003-01-10,"Fort San Antonio Abad, BSP Complex, Manila",Annual Reception for the Banking Community,Rafael Buenaventura,"Good evening ladies and gentlemen... Tonight, ...",1019,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Buenaventura,2003
586,Keynote Address,2002-03-14,"Bangko Sentral ng Pilipinas, Manila","Annual Meeting, Philippine Economic Society",Rafael Buenaventura,Introduction Good morning ladies and gentlemen...,1785,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Buenaventura,2002
587,Remarks,2002-01-11,"Bangko Sentral ng Pilipinas, Manila",Annual Reception for the Banking Community,Rafael Buenaventura,"Good evening ladies and gentlemen... Tonight, ...",1019,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Buenaventura,2002

In [14]:
# After checking those speeches with the official bsp website, we
# Drop duplicate speeches based on exact text matches (keeping the first occurrence)
bsp.drop_duplicates(subset='Text', keep='first', inplace=True)

# Resetting the index
bsp.reset_index(drop=True, inplace=True)

### Identify and Drop Nearly Identical Speeches (Cosine Similarity)

There are some speeches that are not exact duplicates but are nearly identical in content (e.g., matching >98.5%). We drop the later occurrences of these speeches for two main reasons:

1. **Data Quality / Upload Errors:** Some instances are clearly administrative errors on the BSP website (e.g., a 2002 speech re-uploaded as a 2003 speech).
2. **Information Innovation:** Even when a Governor intentionally reiterates the exact same speech to a new audience days later, the financial market has already absorbed the 'surprise' or 'information innovation' from the first delivery. Keeping the duplicate risks double-counting the market's reaction to the same policy signal.

We use Cosine Similarity based on word frequencies to identify and drop these near-duplicates.

In [15]:
import re
import math
from collections import Counter

# Tokenization and Cosine Similarity functions
def get_words(text):
    return re.findall(r'\w+', str(text).lower())

def cosine_similarity(counter1, counter2):
    intersection = set(counter1.keys()) & set(counter2.keys())
    numerator = sum([counter1[x] * counter2[x] for x in intersection])
    
    sum1 = sum([counter1[x]**2 for x in counter1.keys()])
    sum2 = sum([counter2[x]**2 for x in counter2.keys()])
    denominator = math.sqrt(sum1) * math.sqrt(sum2)
    
    if not denominator:
        return 0.0
    return float(numerator) / denominator

# Tokenize all texts
texts = bsp['Text'].fillna('')
counters = [Counter(get_words(t)) for t in texts]

threshold = 0.985
indices_to_drop = set()

print("Finding nearly identical speeches...")
for i in range(len(counters)):
    if i in indices_to_drop: continue
    len_i = sum(counters[i].values())
    if len_i == 0: continue
    
    for j in range(i + 1, len(counters)):
        if j in indices_to_drop: continue
        len_j = sum(counters[j].values())
        if len_j == 0: continue
        
        if abs(len_i - len_j) / max(len_i, len_j) > 0.2:
            continue
            
        sim = cosine_similarity(counters[i], counters[j])
        if sim > threshold:
            print(f'Near duplicate found (sim={sim:.4f}):')
            print(f'  Keep: Index {i} - "{bsp.iloc[i]["Title"]}" ({bsp.iloc[i]["Date"]})')
            print(f'  Drop: Index {j} - "{bsp.iloc[j]["Title"]}" ({bsp.iloc[j]["Date"]})\n')
            indices_to_drop.add(j)
            
# Drop the identified near-duplicates
bsp = bsp.drop(index=list(indices_to_drop))
bsp.reset_index(drop=True, inplace=True)
print(f"Dropped {len(indices_to_drop)} nearly identical speeches. Remaining: {len(bsp)}")

Finding nearly identical speeches...
Near duplicate found (sim=0.9910):
  Keep: Index 30 - "One Team, One Goal: Resilient Partnership Towards Inclusive Economic Growth" (2019-09-17 00:00:00)
  Drop: Index 32 - "One Team, One Goal: Resilient Partnership Towards Inclusive Economic Growth" (2019-09-13 00:00:00)

Near duplicate found (sim=0.9892):
  Keep: Index 42 - "Governor's Message during Media Launch of New Generation Banknotes bearing Gov. Diokno's Signature" (2019-07-03 00:00:00)
  Drop: Index 43 - "Governor's Message" (2019-07-03 00:00:00)

Near duplicate found (sim=1.0000):
  Keep: Index 97 - "Generativity" (2018-01-17 00:00:00)
  Drop: Index 98 - "Generativity 1" (2018-01-17 00:00:00)

Near duplicate found (sim=0.9873):
  Keep: Index 481 - "Building a Coalition of the Willing for a Progressive Philippine Financial System" (2004-11-13 00:00:00)
  Drop: Index 484 - "Laying the Foundation for a Progressive Financial System" (2004-10-20 00:00:00)

Near duplicate found (sim=0.9871):
  Keep: Index 608 - "Policy Thrusts and Prospects in an Uncertain Global Economic Environment" (2001-05-17 00:00:00)
  Drop: Index 610 - "Current Thrusts in Monetary Policy and Financial Supervision and Regulation" (2001-05-08 00:00:00)

Dropped 5 nearly identical speeches. Remaining: 674

In [16]:
# Checking speeches with the same text

bsp[bsp.duplicated(subset='Text', keep=False)]

Empty DataFrame
Columns: [Title, Date, Location, Occasion, Speaker, Text, Len, Link, Role, last_name, year]
Index: []

In [17]:
bsp['Len'].describe()

count     674.000000
mean     1365.639466
std       668.286789
min         2.000000
25%       805.500000
50%      1347.500000
75%      1842.500000
max      3674.000000
Name: Len, dtype: float64

In [18]:
# Checking the speech with len 2

bsp[bsp['Len'] == 2]

,Title,Date,Location,Occasion,Speaker,Text,Len,Link,Role,last_name,year
133,Lessons from the Philippines: Financial stabil...,2017-06-29,unknown,unknown,"Amando M. Tetangco, Jr.",Read Article,2,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Tetangco,2017

In [19]:
bsp = bsp[bsp['Len'] != 2]

In [20]:
bsp.loc[132:134]

,Title,Date,Location,Occasion,Speaker,Text,Len,Link,Role,last_name,year
132,Continuing the Voyage of Excellence to a Brigh...,2017-07-03,"BSP Assembly Hall, BSP Complex, Manila",24th Anniversary Program of the Bangko Sentral...,"Nestor A. Espenilla, Jr.","Outgoing Governor Amando M. Tetangco, Jr.; dis...",2122,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Espenilla,2017
134,Financial Education and Consumer Protection: T...,2017-06-06,"Assembly Hall, BSP",Launch of Wealth Watch Book II,"Amando M. Tetangco, Jr.",Thank you for joining us at the launching of t...,1061,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Tetangco,2017

In [21]:
# Resetting the index

bsp.reset_index(drop=True, inplace=True)
bsp.loc[132:134]

,Title,Date,Location,Occasion,Speaker,Text,Len,Link,Role,last_name,year
132,Continuing the Voyage of Excellence to a Brigh...,2017-07-03,"BSP Assembly Hall, BSP Complex, Manila",24th Anniversary Program of the Bangko Sentral...,"Nestor A. Espenilla, Jr.","Outgoing Governor Amando M. Tetangco, Jr.; dis...",2122,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Espenilla,2017
133,Financial Education and Consumer Protection: T...,2017-06-06,"Assembly Hall, BSP",Launch of Wealth Watch Book II,"Amando M. Tetangco, Jr.",Thank you for joining us at the launching of t...,1061,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Tetangco,2017
134,"Running the Race, Fighting the Good Fight",2017-06-06,"Rizal Ballroom, Shangri-la Makati",Joint General Assembly of MART with ACI Phils....,"Amando M. Tetangco, Jr.",Twenty six (26) days. That is what my ENDO cou...,2041,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Governor,Tetangco,2017

In [22]:
bsp['Len'].describe()

count     673.000000
mean     1367.665676
std       666.708769
min       171.000000
25%       810.000000
50%      1349.000000
75%      1843.000000
max      3674.000000
Name: Len, dtype: float64

In [23]:
# Creating an index column

bsp['index'] = bsp.index

In [26]:
# Reorder the dataframe
new_order = [
    'index', 'Title', 'Date', 'Location', 'Occasion', 
    'Speaker', 'Role', 'Text', 'Len', 'Link', 'last_name', 'year'
]

bsp = bsp[new_order]

In [27]:
bsp.info()
bsp

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   index      673 non-null    int64
 1   Title      673 non-null    object
 2   Date       673 non-null    datetime64[ns]
 3   Location   673 non-null    object
 4   Occasion   673 non-null    object
 5   Speaker    673 non-null    object
 6   Role       673 non-null    object
 7   Text       673 non-null    object
 8   Len        673 non-null    int64
 9   Link       673 non-null    object
 10  last_name  673 non-null    object
 11  year       673 non-null    int32
dtypes: datetime64[ns](1), int32(1), int64(2), object(8)
memory usage: 60.6+ KB

,index,Title,Date,Location,Occasion,Speaker,Role,Text,Len,Link,last_name,year
0,0,Staying on Track in 2020: Sustaining Positive ...,2020-03-03,"Dusit Thani Manila, Makati City",The Manila Times 11th Business Forum,Benjamin E. Diokno,Governor,"The Manila Times President and CEO, Mr. Dante ...",2442,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Diokno,2020
1,1,Finding Opportunities in a Borderless World,2020-02-28,"El Nido, Palawan",13th Annual FMAP Convention,Benjamin E. Diokno,Governor,To the officers and members of the Fund Manage...,2672,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Diokno,2020
2,2,Gearing up for the Road Ahead: With Foresight ...,2020-02-27,Sofitel Philippine Plaza Hotel,17th Professional Insurance and Financial Advi...,Benjamin E. Diokno,Governor,Officers and members of the Professional Insur...,2922,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Diokno,2020
3,3,A Strong Nation Amid A Slowing and Volatile World,2020-02-06,"Shangri-La at the Fort, Taguig",General Membership Meeting and Economic Briefing,Benjamin E. Diokno,Governor,Officers and members of the Management Associa...,2177,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Diokno,2020
4,4,Welcome Dinner Remarks,2020-01-31,Philippine International Convenion Center,BSP-BI Bilateral Meeting,Benjamin E. Diokno,Governor,"Governor Perry, Deputy Governors, colleagues f...",357,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Diokno,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
668,668,BSP ON ITS 5TH YEAR ANNIVERSARY: MANAGING THE ...,1998-07-03,BSP Cafetorium,unknown,Gabriel Singson,Governor,Our 5th anniversary celebrations today follow ...,1043,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Singson,1998
669,669,ON WITH THE ECONOMIC RECOVERY...CAREFULLY,1998-05-28,"Grand Ballroom, Hotel Intercontinental, Makati...",5th Monthly Business Meeting of the Chamber of...,Gabriel Singson,Governor,I feel encouraged by the theme you have adopte...,1600,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Singson,1998
670,670,An Update on Recent Economic Developments,1998-05-22,"Peninsula Hotel, Makati City",Asia Society breakfast meeting,Gabriel Singson,Governor,"For many months now, developments in Asia have...",1349,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Singson,1998
671,671,The Philippines: From Crisis to Recovery,1998-04-07,New York City,Financial Seminar Plenary Session,Gabriel Singson,Governor,The current Asian financial crisis has put a v...,1319,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Singson,1998
672,672,Strategic Issues in Managing Capital Flows: Th...,1998-03-10,"ADB Headquarters, Pasig City",ADB-World Bank Senior Policy Seminar,Gabriel Singson,Governor,The importance of implications of the internat...,1768,https://www.bsp.gov.ph/SitePages/MediaAndResea...,Singson,1998

In [28]:
# Saving the updated dataset, with the additional columns, into a new csv file

bsp.to_csv('../00 Cleaned Dataset/01 speech dataset/bsp_speech_dataset.csv', index=False)