In [1]:
import pandas as pd
import numpy as np

## Real GDP

In [2]:
df_real_gdp = pd.read_excel('../00 Original Dataset/econ dataset/GDP real (2000 onwards).xlsx')
print("DataFrame 'df_real_gdp' loaded successfully.")
df_real_gdp

DataFrame 'df_real_gdp' loaded successfully.

,Gross Domestic Product - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 298,Unnamed: 299,Unnamed: 300,Unnamed: 301,Unnamed: 302,Unnamed: 303,Unnamed: 304,Unnamed: 305,Unnamed: 306,Unnamed: 307
0,Next Rpt Date: 29 Jan '26,Billions of 2000 PHP,Real,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,National Statistical Coordination Board,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,01/31/2025,...,12/29/2000,11/30/2000,10/31/2000,09/29/2000,08/31/2000,07/31/2000,06/30/2000,05/31/2000,04/28/2000,03/31/2000
4,Gross Domestic Product,5528.834473,5528.834473,5528.834473,5843.036621,5843.036621,5843.036621,5475.077637,5475.077637,5475.077637,...,1892.884888,1892.884888,1892.884888,1709.412964,1709.412964,1709.412964,1729.789429,1729.789429,1729.789429,1653.296021
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Final Consumption Expenditure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Households,4033.096436,4033.096436,4033.096436,3953.57373,3953.57373,3953.57373,4069.803223,4069.803223,4069.803223,...,1465.297729,1465.297729,1465.297729,1313.248291,1313.248291,1313.248291,1339.474609,1339.474609,1339.474609,1238.391235
8,Government,827.191345,827.191345,827.191345,1019.939697,1019.939697,1019.939697,871.001648,871.001648,871.001648,...,195.842377,195.842377,195.842377,212.40741,212.40741,212.40741,224.339264,224.339264,224.339264,196.144226
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Trade Balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Goods,1029.294067,1029.294067,1029.294067,811.434326,811.434326,811.434326,733.459167,733.459167,733.459167,...,364.655273,364.655273,364.655273,417.863983,417.863983,417.863983,339.635315,339.635315,339.635315,328.847351
13,Services,634.777649,634.777649,634.777649,736.799255,736.799255,736.799255,857.097229,857.097229,857.097229,...,90.986794,90.986794,90.986794,77.809105,77.809105,77.809105,71.266228,71.266228,71.266228,78.950966
14,Imports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Goods,1637.675049,1637.675049,1637.675049,1731.071045,1731.071045,1731.071045,1659.263306,1659.263306,1659.263306,...,426.493408,426.493408,426.493408,456.58017,456.58017,456.58017,388.911713,388.911713,388.911713,383.772461
16,Services,570.257996,570.257996,570.257996,458.076141,458.076141,458.076141,576.975525,576.975525,576.975525,...,143.669693,143.669693,143.669693,85.110657,85.110657,85.110657,104.278831,104.278831,104.278831,114.483788
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Capital Formation,1186.144043,1186.144043,1186.144043,1528.849854,1528.849854,1528.849854,1204.467407,1204.467407,1204.467407,...,339.957764,339.957764,339.957764,245.992325,245.992325,245.992325,252.277359,252.277359,252.277359,295.296417
19,Fixed Capital Formation,1202.80957,1202.80957,1202.80957,1558.530396,1558.530396,1558.530396,1201.714844,1201.714844,1201.714844,...,342.144196,342.144196,342.144196,305.714691,305.714691,305.714691,310.028839,310.028839,310.028839,319.796326
20,Construction,748.607056,748.607056,748.607056,1082.751465,1082.751465,1082.751465,706.514221,706.514221,706.514221,...,210.044418,210.044418,210.044418,202.191833,202.191833,202.191833,185.19043,185.19043,185.19043,198.22496
21,Durable Equipment,321.306854,321.306854,321.306854,348.805389,348.805389,348.805389,368.828735,368.828735,368.828735,...,62.085239,62.085239,62.085239,65.171745,65.171745,65.171745,75.126015,75.126015,75.126015,68.143753
22,Breeding Stock & Orchard Development,86.650627,86.650627,86.650627,92.595695,92.595695,92.595695,89.241585,89.241585,89.241585,...,65.369713,65.369713,65.369713,34.000961,34.000961,34.000961,45.938812,45.938812,45.938812,48.959869
23,Intellectual Property Products,46.245102,46.245102,46.245102,34.377819,34.377819,34.377819,37.130322,37.130322,37.130322,...,4.644812,4.644812,4.644812,4.35017,4.35017,4.35017,3.77358,3.77358,3.77358,4.467733
24,Changes in Inventories,-16.89366,-16.89366,-16.89366,-29.934818,-29.934818,-29.934818,2.667663,2.667663,2.667663,...,-2.401253,-2.401253,-2.401253,-60.832428,-60.832428,-60.832428,-58.455471,-58.455471,-58.455471,-24.773746
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_real_gdp = df_real_gdp.iloc[[3, 4], 1:]
print("DataFrame 'df_real_gdp' modified to include only rows 3 and 4, and exclude the first column.")
df_real_gdp

DataFrame 'df_real_gdp' modified to include only rows 3 and 4, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 298,Unnamed: 299,Unnamed: 300,Unnamed: 301,Unnamed: 302,Unnamed: 303,Unnamed: 304,Unnamed: 305,Unnamed: 306,Unnamed: 307
3,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,01/31/2025,12/31/2024,...,12/29/2000,11/30/2000,10/31/2000,09/29/2000,08/31/2000,07/31/2000,06/30/2000,05/31/2000,04/28/2000,03/31/2000
4,5528.834473,5528.834473,5528.834473,5843.036621,5843.036621,5843.036621,5475.077637,5475.077637,5475.077637,6193.631348,...,1892.884888,1892.884888,1892.884888,1709.412964,1709.412964,1709.412964,1729.789429,1729.789429,1729.789429,1653.296021

In [4]:
# Transpose rows and columns
gdp_df = df_real_gdp.T
# Rename the columns from the original row indices (3 and 4) to 'Date' and 'Real GDP'
gdp_df.rename(columns={3: 'Date', 4: 'Real GDP'}, inplace=True)

# Convert 'Date' column to datetime objects
gdp_df['Date'] = pd.to_datetime(gdp_df['Date'])
# Convert 'Real GDP' column to numeric, coercing errors to NaN
gdp_df['Real GDP'] = pd.to_numeric(gdp_df['Real GDP'], errors='coerce')
# Drop rows with NaN values in 'Real GDP' column that might have resulted from conversion errors
gdp_df = gdp_df.dropna(subset=['Real GDP'])

# Reset index, as the old column names (e.g., 'FactSet', 'Unnamed: 2') are no longer relevant as an index
gdp_df = gdp_df.reset_index(drop=True)

print("DataFrame 'gdp_df' created successfully with 'Date' and 'Real GDP' columns.")

DataFrame 'gdp_df' created successfully with 'Date' and 'Real GDP' columns.

In [5]:
gdp_df

          Date     Real GDP
0   2025-09-30  5528.834473
1   2025-08-29  5528.834473
2   2025-07-31  5528.834473
3   2025-06-30  5843.036621
4   2025-05-30  5843.036621
..         ...          ...
302 2000-07-31  1709.412964
303 2000-06-30  1729.789429
304 2000-05-31  1729.789429
305 2000-04-28  1729.789429
306 2000-03-31  1653.296021

[307 rows x 2 columns]

In [6]:
gdp_df['Date'] = (gdp_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'gdp_df' updated to the first day of the next month.") #justification is from comparing CPI values of CEIC and Factset
gdp_df.head()
gdp_df.tail()

Dates in 'gdp_df' updated to the first day of the next month.

          Date     Real GDP
302 2000-08-01  1709.412964
303 2000-07-01  1729.789429
304 2000-06-01  1729.789429
305 2000-05-01  1729.789429
306 2000-04-01  1653.296021

## CPI

In [7]:
df_consumer_price = pd.read_excel('../00 Original Dataset/econ dataset/consumer price [levels] (1981 onwards).xlsx')
print("DataFrame 'df_consumer_price' loaded successfully.")
df_consumer_price

DataFrame 'df_consumer_price' loaded successfully.

,Consumer Prices - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 531,Unnamed: 532,Unnamed: 533,Unnamed: 534,Unnamed: 535,Unnamed: 536,Unnamed: 537,Unnamed: 538,Unnamed: 539,Unnamed: 540
0,Last Rpt Date: 06 Jan '26,Index Level - 2012 = 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,12/31/2025,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,...,10/30/1981,09/30/1981,08/31/1981,07/31/1981,06/30/1981,05/29/1981,04/30/1981,03/31/1981,02/27/1981,01/30/1981
4,Total,130,128.899994,128.600006,128.5,128.5,127.699997,127.300003,127.199997,127.300003,...,6.557027,6.509512,6.461998,6.461998,6.319454,6.224424,6.224424,6.176909,6.176909,6.129395
5,Food & Non-Alcoholic Beverages,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
6,Alcoholic Beverages & Tobacco,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
7,Clothing & Footwear,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
8,"Housing, Water, Electricity, Gas & Other Fuels",-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9,"Furnishing, Household Equipment & Routine Main...",-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
10,Health,127.599998,127.300003,127.099998,127,126.800003,126.300003,125.900002,125.699997,125.400002,...,-,-,-,-,-,-,-,-,-,-
11,Transport,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
12,Communication,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
13,Recreation & Culture,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
14,Education,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
15,Restaurants & Miscellaneous Goods & Services,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_consumer_price = df_consumer_price.iloc[[3, 4], 1:]
print("DataFrame 'df_consumer_price' modified to include only rows 3 and 4, and exclude the first column.")
df_consumer_price

DataFrame 'df_consumer_price' modified to include only rows 3 and 4, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 531,Unnamed: 532,Unnamed: 533,Unnamed: 534,Unnamed: 535,Unnamed: 536,Unnamed: 537,Unnamed: 538,Unnamed: 539,Unnamed: 540
3,12/31/2025,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/30/1981,09/30/1981,08/31/1981,07/31/1981,06/30/1981,05/29/1981,04/30/1981,03/31/1981,02/27/1981,01/30/1981
4,130,128.899994,128.600006,128.5,128.5,127.699997,127.300003,127.199997,127.300003,127.800003,...,6.557027,6.509512,6.461998,6.461998,6.319454,6.224424,6.224424,6.176909,6.176909,6.129395

In [9]:
# Transpose rows and columns
cpi_df = df_consumer_price.T
# Rename the columns from the original row indices (3 and 4) to 'Date' and 'CPI'
cpi_df.rename(columns={3: 'Date', 4: 'CPI'}, inplace=True)

# Convert 'Date' column to datetime objects
cpi_df['Date'] = pd.to_datetime(cpi_df['Date'])
# Convert 'CPI' column to numeric, coercing errors to NaN
cpi_df['CPI'] = pd.to_numeric(cpi_df['CPI'], errors='coerce')
# Drop rows with NaN values in 'CPI' column that might have resulted from conversion errors
cpi_df = cpi_df.dropna(subset=['CPI'])

# Reset index, as the old column names (e.g., 'FactSet', 'Unnamed: 2') are no longer relevant as an index
cpi_df = cpi_df.reset_index(drop=True)

print("DataFrame 'cpi_df' created successfully with 'Date' and 'CPI' columns.")

DataFrame 'cpi_df' created successfully with 'Date' and 'CPI' columns.

In [10]:
cpi_df

          Date         CPI
0   2025-12-31  130.000000
1   2025-11-28  128.899994
2   2025-10-31  128.600006
3   2025-09-30  128.500000
4   2025-08-29  128.500000
..         ...         ...
535 1981-05-29    6.224424
536 1981-04-30    6.224424
537 1981-03-31    6.176909
538 1981-02-27    6.176909
539 1981-01-30    6.129395

[540 rows x 2 columns]

In [11]:
cpi_df['Date'] = (cpi_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'cpi_df' updated to the first day of the next month.") #justification is from comparing CPI values of CEIC and Factset
cpi_df

Dates in 'cpi_df' updated to the first day of the next month.

          Date         CPI
0   2026-01-01  130.000000
1   2025-12-01  128.899994
2   2025-11-01  128.600006
3   2025-10-01  128.500000
4   2025-09-01  128.500000
..         ...         ...
535 1981-06-01    6.224424
536 1981-05-01    6.224424
537 1981-04-01    6.176909
538 1981-03-01    6.176909
539 1981-02-01    6.129395

[540 rows x 2 columns]

# Wholesale Prices

In [12]:
df_wholesale_prices = pd.read_excel('../00 Original Dataset/econ dataset/wholesale prices [levels] (1998 onwards).xlsx')
print("DataFrame 'df_wholesale_prices' loaded successfully.")
df_wholesale_prices

DataFrame 'df_wholesale_prices' loaded successfully.

,Wholesale Prices - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330,Unnamed: 331,Unnamed: 332,Unnamed: 333,Unnamed: 334,Unnamed: 335
0,Index Level - 1998 = 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/30/1998,09/30/1998,08/31/1998,07/31/1998,06/30/1998,05/29/1998,04/30/1998,03/31/1998,02/27/1998,01/30/1998
4,All Items,144,143.5,143.5,142.399994,143.300003,143,143.100006,143.399994,142.5,...,46.152122,45.299946,45.030834,44.851429,44.80658,44.627174,44.133808,43.774994,43.685291,43.191925
5,Food,158.800003,158.199997,158,157,156.800003,157.100006,157,157.199997,157,...,53.620956,51.771957,51.566513,51.155624,51.41243,51.206985,50.48793,49.563431,48.58757,48.176682
6,Beverages & Tobacco,238.399994,238.300003,237.899994,237.800003,237.699997,238.199997,238.199997,236.199997,235.100006,...,56.595844,56.595844,56.53981,56.203594,56.091526,56.091526,55.194958,55.082886,54.858746,54.52253
7,"Crude Materials, Inedible Except Fuels",236.199997,232.699997,242.699997,212.800003,266.399994,251.5,260.700012,267,234.5,...,54.698704,51.98138,51.780098,52.031704,51.075607,48.811172,46.446095,45.439678,44.835827,44.684868
8,"Mineral Fuels, Lubricants & Related Materials",148.699997,145.199997,144.399994,142.899994,143,141,138.5,140.600006,142.600006,...,15.627993,15.873137,15.428812,15.290918,15.076416,15.091738,14.907879,15.045774,16.072317,15.765886
9,"Chemicals, incl. Animal & Vegetable Oils/Fats",149.600006,148.800003,149.199997,145.300003,150.199997,148.600006,150.100006,151,146.100006,...,53.983227,53.616352,53.092243,52.987423,52.725368,52.044025,50.681343,50.471699,50.366875,49.842766
10,Manufactured Goods Classified Chiefly by Material,130.199997,130.100006,130.100006,130.100006,130.300003,130.300003,130.199997,130.300003,130.199997,...,59.202591,59.026039,58.672943,58.731792,58.790642,58.672943,58.672943,58.90834,58.790642,58.202148
11,Machinery & Transport Equipment,116,115.900002,115.900002,115.800003,115.800003,115.800003,115.699997,115.699997,115.599998,...,66.862747,65.294121,65.294121,65.359474,65.359474,65.22876,65.032677,64.379082,64.379082,63.137257
12,Miscellaneous Manufactured Articles,115.099998,115,114.599998,114.5,114.5,114.400002,114.400002,114.599998,114.5,...,52.868904,52.144672,52.144672,51.679096,51.472172,51.420441,51.21352,50.799671,50.799671,50.334095
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_wholesale_prices = df_wholesale_prices.iloc[[3, 4], 1:]
print("DataFrame 'df_wholesale_prices' modified to include only rows 3 and 4, and exclude the first column.")
df_wholesale_prices

DataFrame 'df_wholesale_prices' modified to include only rows 3 and 4, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330,Unnamed: 331,Unnamed: 332,Unnamed: 333,Unnamed: 334,Unnamed: 335
3,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,...,10/30/1998,09/30/1998,08/31/1998,07/31/1998,06/30/1998,05/29/1998,04/30/1998,03/31/1998,02/27/1998,01/30/1998
4,144,143.5,143.5,142.399994,143.300003,143,143.100006,143.399994,142.5,141.800003,...,46.152122,45.299946,45.030834,44.851429,44.80658,44.627174,44.133808,43.774994,43.685291,43.191925

In [14]:
# Transpose rows and columns
wholesale_prices_df = df_wholesale_prices.T

# Rename the columns from the original row indices (3 and 4) to 'Date' and 'Wholesale Price'
wholesale_prices_df.rename(columns={3: 'Date', 4: 'Wholesale Price'}, inplace=True)

# Convert 'Date' column to datetime objects
wholesale_prices_df['Date'] = pd.to_datetime(wholesale_prices_df['Date'])

# Convert 'Wholesale Price' column to numeric, coercing errors to NaN
wholesale_prices_df['Wholesale Price'] = pd.to_numeric(wholesale_prices_df['Wholesale Price'], errors='coerce')

# Drop rows with NaN values in 'Wholesale Price' column that might have resulted from conversion errors
wholesale_prices_df = wholesale_prices_df.dropna(subset=['Wholesale Price'])

# Reset index, as the old column names (e.g., 'FactSet', 'Unnamed: 2') are no longer relevant as an index
wholesale_prices_df = wholesale_prices_df.reset_index(drop=True)

print("DataFrame 'wholesale_prices_df' created successfully with 'Date' and 'Wholesale Price' columns.")
wholesale_prices_df.head()

DataFrame 'wholesale_prices_df' created successfully with 'Date' and 'Wholesale Price' columns.

        Date  Wholesale Price
0 2025-11-28       144.000000
1 2025-10-31       143.500000
2 2025-09-30       143.500000
3 2025-08-29       142.399994
4 2025-07-31       143.300003

In [15]:
wholesale_prices_df['Date'] = (wholesale_prices_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'wholesale_prices_df' updated to the first day of the next month.")
wholesale_prices_df

Dates in 'wholesale_prices_df' updated to the first day of the next month.

          Date  Wholesale Price
0   2025-12-01       144.000000
1   2025-11-01       143.500000
2   2025-10-01       143.500000
3   2025-09-01       142.399994
4   2025-08-01       143.300003
..         ...              ...
330 1998-06-01        44.627174
331 1998-05-01        44.133808
332 1998-04-01        43.774994
333 1998-03-01        43.685291
334 1998-02-01        43.191925

[335 rows x 2 columns]

# Industrial Production

In [16]:
df_industrial_production = pd.read_excel('../00 Original Dataset/econ dataset/industrial production [levels] (1998 onwards).xlsx')
print("DataFrame 'df_industrial_production' loaded successfully.")
df_industrial_production

DataFrame 'df_industrial_production' loaded successfully.

,Industrial Production - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 326,Unnamed: 327,Unnamed: 328,Unnamed: 329,Unnamed: 330,Unnamed: 331,Unnamed: 332,Unnamed: 333,Unnamed: 334,Unnamed: 335
0,Index Level - 2000 = 100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/30/1998,09/30/1998,08/31/1998,07/31/1998,06/30/1998,05/29/1998,04/30/1998,03/31/1998,02/27/1998,01/30/1998
4,Total Manufacturing,100.048134,102.761719,97.322502,100.351433,101.363564,98.934433,99.385788,95.567711,97.262245,...,40.353806,43.702553,40.381947,41.507576,40.747776,37.905563,36.526669,41.001041,39.200035,39.200035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,Transport Equipment,100.35965,101.710892,100.647606,102.184959,107.947914,101.671143,108.694351,93.185173,97.567848,...,-,-,-,-,-,-,-,-,-,-
60,Furniture & Fixtures,77.937149,99.679497,89.128105,89.175262,92.234245,84.395287,85.221703,88.743958,81.065575,...,-,-,-,-,-,-,-,-,-,-
61,Miscellaneous Manufactures,95.392693,98.061951,96.370804,93.747185,101.53067,91.593658,87.516914,85.497772,91.121758,...,-,-,-,-,-,-,-,-,-,-
62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,Note: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_industrial_production = df_industrial_production.iloc[[3, 4], 1:]
print("DataFrame 'df_industrial_production' modified to include only rows 3 and 4, and exclude the first column.")

# Transpose rows and columns
industrial_production_df = df_industrial_production.T

# Rename the columns from the original row indices (3 and 4) to 'Date' and 'Industrial Production'
industrial_production_df.rename(columns={3: 'Date', 4: 'Industrial Production'}, inplace=True)

# Convert 'Date' column to datetime objects
industrial_production_df['Date'] = pd.to_datetime(industrial_production_df['Date'])

# Convert 'Industrial Production' column to numeric, coercing errors to NaN
industrial_production_df['Industrial Production'] = pd.to_numeric(industrial_production_df['Industrial Production'], errors='coerce')

# Drop rows with NaN values in 'Industrial Production' column that might have resulted from conversion errors
industrial_production_df = industrial_production_df.dropna(subset=['Industrial Production'])

# Reset index, as the old column names are no longer relevant as an index
industrial_production_df = industrial_production_df.reset_index(drop=True)

print("DataFrame 'industrial_production_df' created successfully with 'Date' and 'Industrial Production' columns.")
industrial_production_df

DataFrame 'df_industrial_production' modified to include only rows 3 and 4, and exclude the first column.
DataFrame 'industrial_production_df' created successfully with 'Date' and 'Industrial Production' columns.

          Date  Industrial Production
0   2025-11-28             100.048134
1   2025-10-31             102.761719
2   2025-09-30              97.322502
3   2025-08-29             100.351433
4   2025-07-31             101.363564
..         ...                    ...
330 1998-05-29              37.905563
331 1998-04-30              36.526669
332 1998-03-31              41.001041
333 1998-02-27              39.200035
334 1998-01-30              39.200035

[335 rows x 2 columns]

In [18]:
industrial_production_df['Date'] = (industrial_production_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'industrial_production_df' updated to the first day of the next month.")
industrial_production_df

Dates in 'industrial_production_df' updated to the first day of the next month.

          Date  Industrial Production
0   2025-12-01             100.048134
1   2025-11-01             102.761719
2   2025-10-01              97.322502
3   2025-09-01             100.351433
4   2025-08-01             101.363564
..         ...                    ...
330 1998-06-01              37.905563
331 1998-05-01              36.526669
332 1998-04-01              41.001041
333 1998-03-01              39.200035
334 1998-02-01              39.200035

[335 rows x 2 columns]

# International Trade

In [19]:
df_international_trade = pd.read_excel('../00 Original Dataset/econ dataset/international trade [levels _ peso] (1957 onwards).xlsx')
print("DataFrame 'df_international_trade' loaded successfully.")
df_international_trade

DataFrame 'df_international_trade' loaded successfully.

,International Trade - Philippines,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 818,Unnamed: 819,Unnamed: 820,Unnamed: 821,Unnamed: 822,Unnamed: 823,Unnamed: 824,Unnamed: 825,Unnamed: 826,Unnamed: 827
0,Next Rpt Date: 27 Jan '26,Millions of PHP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Philippines National Statistics Office,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,...,10/31/1957,09/30/1957,08/30/1957,07/31/1957,06/28/1957,05/31/1957,04/30/1957,03/29/1957,02/28/1957,01/31/1957
4,Merchandise Exports,406979.75,434670.96875,416821.9375,407190.40625,417984.75,398221.28125,406874.84375,385384.9375,388416.125,...,46.459946,56.559937,69.689919,78.779907,90.899902,79.789902,83.829903,68.679924,77.769913,89.889908
5,Total Agro-Based Products,38.767395,34.957291,36.403126,32.980213,35.009666,33.063004,33.726799,33.82019,33.680981,...,-,-,-,-,-,-,-,-,-,-
6,Agro-Based Products,34.308033,29.991625,32.498081,29.181683,30.927877,29.526373,29.900633,29.982359,29.060038,...,-,-,-,-,-,-,-,-,-,-
7,Other Agro-Based Products,4.459361,4.965667,3.905048,3.798532,4.081789,3.536629,3.826165,3.837832,4.620944,...,-,-,-,-,-,-,-,-,-,-
8,Forest Products,0.953157,1.187217,0.990797,1.005461,1.030481,1.006683,0.974296,0.860394,1.053072,...,-,-,-,-,-,-,-,-,-,-
9,Mineral Products,19.20364,34.232555,40.319332,41.607933,50.455936,40.804333,38.454617,27.322866,28.262423,...,-,-,-,-,-,-,-,-,-,-
10,Petroleum Products,1.52901,1.379792,1.263275,1.301776,1.170201,0.884157,1.388821,1.512734,1.442943,...,-,-,-,-,-,-,-,-,-,-
11,Manufactures,339.158234,351.43335,329.016907,320.534241,322.792786,311.823914,320.099762,310.092438,305.321869,...,-,-,-,-,-,-,-,-,-,-
12,Electronic Products,247.128021,243.975739,230.589523,221.289322,223.195953,219.134521,213.941269,193.682327,208.881348,...,-,-,-,-,-,-,-,-,-,-
13,Other Electronics,16.397207,18.657089,17.950289,17.204729,17.766142,17.710144,18.769569,15.534924,18.495953,...,-,-,-,-,-,-,-,-,-,-
14,Garments,2.863732,3.316683,3.675226,3.762587,4.841889,3.401132,3.35261,2.910637,2.86442,...,-,-,-,-,-,-,-,-,-,-
15,Textile Yarns/Fabrics,1.48944,1.820355,1.566703,1.60582,1.660134,1.295905,1.29023,1.210572,1.356639,...,-,-,-,-,-,-,-,-,-,-
16,Footwear,0.522524,1.112847,0.523466,1.162138,0.780442,0.646079,1.315243,0.562826,0.31385,...,-,-,-,-,-,-,-,-,-,-
17,Travel Goods and Handbags,2.923531,3.16632,2.265491,2.835859,3.458008,2.589133,2.366997,2.480123,2.175512,...,-,-,-,-,-,-,-,-,-,-
18,Wood Manufactures,0.295208,0.359784,0.300757,0.25404,0.253756,0.308873,0.309483,0.258852,0.321562,...,-,-,-,-,-,-,-,-,-,-
19,Furniture & Fixtures,2.351536,2.003347,2.115344,2.099196,1.732446,1.391418,1.160528,1.173259,2.275243,...,-,-,-,-,-,-,-,-,-,-
20,Chemicals,8.197504,8.789334,9.135223,8.692462,8.494653,7.95387,9.891904,10.59715,9.493729,...,-,-,-,-,-,-,-,-,-,-
21,Non-metallic Mineral Manufactures,2.020819,2.464172,2.032197,2.277422,1.868075,1.929193,1.808524,1.488006,1.894392,...,-,-,-,-,-,-,-,-,-,-
22,Machinery & Transport Equipment,18.676359,24.865314,19.044273,20.779119,16.961792,17.093733,15.992776,12.631465,12.350611,...,-,-,-,-,-,-,-,-,-,-
23,Processed Food and Beverages,7.027369,7.552898,7.385726,7.111601,7.463407,5.824203,6.176148,6.517013,6.663319,...,-,-,-,-,-,-,-,-,-,-
24,Iron & Steel,0.334144,0.45652,0.869499,1.096613,0.568229,1.922578,0.752496,0.880832,1.7709,...,-,-,-,-,-,-,-,-,-,-
25,"Baby Carr., Toys, Games and sporting goods",0.873365,1.272949,1.340271,1.651681,1.850027,1.670732,1.273721,0.896332,1.114691,...,-,-,-,-,-,-,-,-,-,-
26,"Basketwork, Wickerwork and Other Articles of P...",0.122373,0.199657,0.161835,0.156717,0.119377,0.12578,0.127015,0.132982,0.176699,...,-,-,-,-,-,-,-,-,-,-
27,"Misc. Manufactured Articles, n.e.s",3.107624,0.364571,3.351944,3.004906,3.838806,3.516071,4.122149,4.009086,3.895917,...,-,-,-,-,-,-,-,-,-,-
28,Other Manufactures,24.827496,27.774624,26.70912,25.550024,27.939655,25.310558,37.449108,55.126057,31.277075,...,-,-,-,-,-,-,-,-,-,-
29,Special Transactions,7.368317,8.199382,7.573718,6.192049,6.749471,8.180247,10.783597,9.709459,8.651526,...,-,-,-,-,-,-,-,-,-,-
30,Re-Export,0.867326,0.973875,1.426494,0.999991,0.172058,0.134106,0.139331,0.076285,0.068887,...,-,-,-,-,-,-,-,-,-,-
31,Merchandise Imports,613973.0625,679404.9375,684380.125,634966.375,669526.125,645985,608916.25,611109.375,647409.5,...,119.179855,124.229858,107.059875,128.269852,127.259865,131.299835,119.179863,111.099876,81.809914,118.169884
32,Capital Goods,185.299667,195.095062,215.744064,185.135666,194.791245,209.387955,164.579956,186.227295,181.381546,...,-,-,-,-,-,-,-,-,-,-
33,Raw Materials & Intermediate Goods,232.385513,243.996979,236.829239,218.408157,238.616928,206.619553,220.838974,208.526398,224.7789,...,-,-,-,-,-,-,-,-,-,-
34,Unprocessed Raw Materials,17.211552,23.504702,20.302738,16.861683,18.97184,14.983668,22.721376,13.992345,19.115288,...,-,-,-,-,-,-,-,-,-,-
35,Semi-processed Raw Materials,215.173965,220.492279,21.652651,201.546478,219.645081,191.635895,198.117599,194.534058,205.66362,...,-,-,-,-,-,-,-,-,-,-
36,"Mineral Fuels, Lubricant & Related Materials",6.242945,7.911544,7.341563,67.393761,75.280045,78.977722,65.140907,61.435295,74.969162,...,-,-,-,-,-,-,-,-,-,-
37,"Coal, Coke",10.007606,11.113941,0.963506,11.462886,9.372374,11.377962,12.493628,12.145379,10.947418,...,-,-,-,-,-,-,-,-,-,-
38,Petroleum Crude,10.304665,15.97123,14.312759,7.282759,8.531246,10.031859,10.233994,8.598335,15.726325,...,-,-,-,-,-,-,-,-,-,-
39,Others,42.11718,52.030273,49.467804,48.648117,57.376427,57.567898,42.413284,40.691578,48.295418,...,-,-,-,-,-,-,-,-,-,-
40,Consumer Goods,130.986588,134.338181,136.213791,131.995087,136.123856,121.206772,135.799057,123.429314,131.82254,...,-,-,-,-,-,-,-,-,-,-
41,Durable,66.437737,70.716583,71.00074,65.698265,70.879303,60.586227,67.746658,59.203342,66.557083,...,-,-,-,-,-,-,-,-,-,-
42,Passenger Cars & Motorized Cycle,33.657265,37.49358,33.49004,33.557102,34.786549,29.069395,36.834499,28.216856,35.094254,...,-,-,-,-,-,-,-,-,-,-
43,Home Appliances,5.590669,4.312653,6.326922,5.863803,6.004975,5.881817,5.628808,6.516794,6.227349,...,-,-,-,-,-,-,-,-,-,-
44,Miscellaneous Manufactures,27.1898,28.910349,31.183779,26.277357,30.087784,25.635015,25.283352,24.46969,25.235476,...,-,-,-,-,-,-,-,-,-,-
45,Non-durable,64.548851,63.621601,65.213058,66.296822,65.244545,60.620544,68.052399,64.225967,65.265465,...,-,-,-,-,-,-,-,-,-,-
46,Food & Live Animals Chiefly For Food,55.567848,5.600452,57.76104,59.689293,57.981472,53.856209,61.645802,58.131344,59.514137,...,-,-,-,-,-,-,-,-,-,-
47,Beverages & Tobacco Mfture.,3.590288,3.322658,3.470198,2.8307,2.819349,2.573246,2.596502,2.400032,2.005407,...,-,-,-,-,-,-,-,-,-,-
48,"Articles of Apparel, Accessories",0.539071,4.294417,3.981821,3.776826,4.443725,4.19109,3.810098,3.694593,3.745918,...,-,-,-,-,-,-,-,-,-,-
49,Special Transactions,2.872092,2.230613,2.722884,3.01189,2.648027,2.443506,2.094317,2.284496,2.346786,...,-,-,-,-,-,-,-,-,-,-
50,Articles Temporarily Imported & Exported,-,-,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
51,Others,2.872092,2.230613,2.722884,3.01189,2.648027,2.443506,2.094317,2.284496,2.346786,...,-,-,-,-,-,-,-,-,-,-
52,Merchandise Trade Balance,-0.207015,-0.24476,-0.26758,-0.227765,-0.251545,-0.247785,-0.202031,-0.225747,-0.259011,...,-,-,-,-,-,-,-,-,-,-
53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,Notes: Data not seasonally adjusted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,Classification by SITC Commodity Groups,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_international_trade = df_international_trade.iloc[[3, 4, 31], 1:]
print("DataFrame 'df_international_trade' modified to include only rows 3, 4, and 31, and exclude the first column.")
df_international_trade.head()

DataFrame 'df_international_trade' modified to include only rows 3, 4, and 31, and exclude the first column.

,FactSet,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 818,Unnamed: 819,Unnamed: 820,Unnamed: 821,Unnamed: 822,Unnamed: 823,Unnamed: 824,Unnamed: 825,Unnamed: 826,Unnamed: 827
3,11/28/2025,10/31/2025,09/30/2025,08/29/2025,07/31/2025,06/30/2025,05/30/2025,04/30/2025,03/31/2025,02/28/2025,...,10/31/1957,09/30/1957,08/30/1957,07/31/1957,06/28/1957,05/31/1957,04/30/1957,03/29/1957,02/28/1957,01/31/1957
4,406979.75,434670.96875,416821.9375,407190.40625,417984.75,398221.28125,406874.84375,385384.9375,388416.125,394115.84375,...,46.459946,56.559937,69.689919,78.779907,90.899902,79.789902,83.829903,68.679924,77.769913,89.889908
31,613973.0625,679404.9375,684380.125,634966.375,669526.125,645985,608916.25,611109.375,647409.5,566823,...,119.179855,124.229858,107.059875,128.269852,127.259865,131.299835,119.179863,111.099876,81.809914,118.169884

In [21]:
international_trade_df = df_international_trade.T
international_trade_df.rename(columns={3: 'Date', 4: 'Intl Trade Merch Exports', 31: 'Intl Trade Merch Imports'}, inplace=True)

international_trade_df['Date'] = pd.to_datetime(international_trade_df['Date'])
international_trade_df['Intl Trade Merch Exports'] = pd.to_numeric(international_trade_df['Intl Trade Merch Exports'], errors='coerce')
international_trade_df['Intl Trade Merch Imports'] = pd.to_numeric(international_trade_df['Intl Trade Merch Imports'], errors='coerce')

international_trade_df.dropna(subset=['Intl Trade Merch Exports', 'Intl Trade Merch Imports'], inplace=True)
international_trade_df = international_trade_df.reset_index(drop=True)

print("DataFrame 'international_trade_df' processed successfully with 'Date', 'Intl Trade Merch Exports', and 'Intl Trade Merch Imports' columns.")
international_trade_df.head()

DataFrame 'international_trade_df' processed successfully with 'Date', 'Intl Trade Merch Exports', and 'Intl Trade Merch Imports' columns.

        Date  Intl Trade Merch Exports  Intl Trade Merch Imports
0 2025-11-28              406979.75000               613973.0625
1 2025-10-31              434670.96875               679404.9375
2 2025-09-30              416821.93750               684380.1250
3 2025-08-29              407190.40625               634966.3750
4 2025-07-31              417984.75000               669526.1250

In [22]:
international_trade_df['Date'] = (international_trade_df['Date'].dt.to_period('M') + 1).dt.to_timestamp()

print("Dates in 'international_trade_df' updated to the first day of the next month.")
international_trade_df

Dates in 'international_trade_df' updated to the first day of the next month.

          Date  Intl Trade Merch Exports  Intl Trade Merch Imports
0   2025-12-01             406979.750000             613973.062500
1   2025-11-01             434670.968750             679404.937500
2   2025-10-01             416821.937500             684380.125000
3   2025-09-01             407190.406250             634966.375000
4   2025-08-01             417984.750000             669526.125000
..         ...                       ...                       ...
822 1957-06-01                 79.789902                131.299835
823 1957-05-01                 83.829903                119.179863
824 1957-04-01                 68.679924                111.099876
825 1957-03-01                 77.769913                 81.809914
826 1957-02-01                 89.889908                118.169884

[827 rows x 3 columns]

# FX Rate

In [23]:
df_fx_rate = pd.read_excel('../00 Original Dataset/econ dataset/pesodollar.xlsx', header=None)
print("DataFrame 'df_fx_rate':")
df_fx_rate.head(20)

DataFrame 'df_fx_rate':

,0,1,2,3,4
0,Philippine Peso per US Dollar Rate,NaN,NaN,NaN,NaN
1,for periods indicated,NaN,NaN,NaN,NaN
2,,NaN,,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,Period,NaN,Average,End-of-Period
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN
7,NaN,1945,January,2,n.a.
8,NaN,NaN,February,2,n.a.
9,NaN,NaN,March,2,n.a.
10,NaN,NaN,April,2,n.a.
11,NaN,NaN,May,2,n.a.
12,NaN,NaN,June,2,n.a.
13,NaN,NaN,July,2,n.a.
14,NaN,NaN,August,2,n.a.
15,NaN,NaN,September,2,n.a.
16,NaN,NaN,October,2,n.a.
17,NaN,NaN,November,2,n.a.
18,NaN,NaN,December,2,n.a.
19,NaN,1946,January,2,n.a.

In [24]:
# Data starts from the 8th row (index 7).
# - 2nd column (index 1) contains the year
# - 3rd column (index 2) contains the month
# - 4th column (index 3) contains the FX rate values
df_working = df_fx_rate.iloc[7:, [1, 2, 3]].copy()
df_working.columns = ['Year', 'Month', 'FX Rate']

# The 'Year' column has NaNs that need to be forward-filled.
df_working['Year'] = df_working['Year'].ffill()

# Drop rows where 'Month' or 'FX_Rate' are NaN, as these are not complete data entries.
df_working = df_working.dropna(subset=['Month', 'FX Rate']).copy()

# Convert month names to numerical representation.
month_mapping = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6,
    'July': 7, 'August': 8, 'September': 9, 'October': 10, 'November': 11, 'December': 12
}
df_working['Month_Num'] = df_working['Month'].map(month_mapping)

# Ensure 'Year' is integer type for date creation.
df_working['Year'] = df_working['Year'].astype(int)

# Create the 'Date' column combining 'Year', 'Month_Num', and setting the day to 1.
# Rename columns to 'year' and 'month' as pd.to_datetime expects these lowercase names
# when passed a DataFrame with date components.
df_working['Date'] = pd.to_datetime(
    df_working[['Year', 'Month_Num']].assign(day=1).rename(
        columns={'Year': 'year', 'Month_Num': 'month'}
    )
)

# Select the final desired columns: 'Date' as the 1st and 'FX_Rate' as the 2nd.
df_fx_rate_cleaned = df_working[['Date', 'FX Rate']].copy()

print("Cleaned and processed DataFrame 'df_fx_rate_cleaned'")

print("\nDataFrame Info:")
df_fx_rate_cleaned.info()

Cleaned and processed DataFrame 'df_fx_rate_cleaned'

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 972 entries, 7 to 978
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     972 non-null    datetime64[ns]
 1   FX Rate  972 non-null    object
dtypes: datetime64[ns](1), object(1)
memory usage: 22.8+ KB

In [25]:
df_fx_rate_cleaned

          Date    FX Rate
7   1945-01-01          2
8   1945-02-01          2
9   1945-03-01          2
10  1945-04-01          2
11  1945-05-01          2
..         ...        ...
974 2025-08-01  57.252526
975 2025-09-01  57.250091
976 2025-10-01  58.298409
977 2025-11-01   58.91355
978 2025-12-01  58.848833

[972 rows x 2 columns]

# merge all new df

In [26]:
main_df = gdp_df
main_df = pd.merge(main_df, cpi_df, on='Date', how='outer')
main_df = pd.merge(main_df, wholesale_prices_df, on='Date', how='outer')
main_df = pd.merge(main_df, industrial_production_df, on='Date', how='outer')
main_df = pd.merge(main_df, international_trade_df, on='Date', how='outer')
main_df = pd.merge(main_df, df_fx_rate_cleaned, on='Date', how='outer')

print("Merged DataFrame 'main_df' created successfully.")
main_df

Merged DataFrame 'main_df' created successfully.

,Date,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
0,2025-10-01,5528.834473,128.500000,143.500000,97.322502,416821.93750,684380.125,58.298409
1,2025-09-01,5528.834473,128.500000,142.399994,100.351433,407190.40625,634966.375,57.250091
2,2025-08-01,5528.834473,127.699997,143.300003,101.363564,417984.75000,669526.125,57.252526
3,2025-07-01,5843.036621,127.300003,143.000000,98.934433,398221.28125,645985.000,56.752348
4,2025-06-01,5843.036621,127.199997,143.100006,99.385788,406874.84375,608916.250,56.358579
...,...,...,...,...,...,...,...,...
968,1956-09-01,NaN,NaN,NaN,NaN,NaN,NaN,2
969,1956-10-01,NaN,NaN,NaN,NaN,NaN,NaN,2
970,1956-11-01,NaN,NaN,NaN,NaN,NaN,NaN,2
971,1956-12-01,NaN,NaN,NaN,NaN,NaN,NaN,2
972,1957-01-01,NaN,NaN,NaN,NaN,NaN,NaN,2

In [27]:
#Saving df for EDA
main_df.to_csv('../00 Cleaned Dataset/03 economic dataset/others/withGDP_Macrovars_raw.csv', index=False)
print("DataFrame 'main_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withGDP_Macrovars_raw.csv'.")

DataFrame 'main_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withGDP_Macrovars_raw.csv'.

# merge all new df (without Real GDP)

In [28]:
main2_df = cpi_df
main2_df = pd.merge(main2_df, wholesale_prices_df, on='Date', how='outer')
main2_df = pd.merge(main2_df, industrial_production_df, on='Date', how='outer')
main2_df = pd.merge(main2_df, international_trade_df, on='Date', how='outer')
main2_df = pd.merge(main2_df, df_fx_rate_cleaned, on='Date', how='outer')

print("Merged DataFrame 'main2_df' created successfully.")
main2_df

Merged DataFrame 'main2_df' created successfully.

,Date,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
0,2026-01-01,130.000000,NaN,NaN,NaN,NaN,NaN
1,2025-12-01,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833
2,2025-11-01,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355
3,2025-10-01,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409
4,2025-09-01,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091
...,...,...,...,...,...,...,...
968,1956-09-01,NaN,NaN,NaN,NaN,NaN,2
969,1956-10-01,NaN,NaN,NaN,NaN,NaN,2
970,1956-11-01,NaN,NaN,NaN,NaN,NaN,2
971,1956-12-01,NaN,NaN,NaN,NaN,NaN,2
972,1957-01-01,NaN,NaN,NaN,NaN,NaN,2

In [29]:
#Saving df for EDA
main2_df.to_csv('../00 Cleaned Dataset/03 economic dataset/others/withoutGDP_Macrovars_raw.csv', index=False)
print("DataFrame 'main2_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withoutGDP_Macrovars_raw.csv'.")

DataFrame 'main2_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withoutGDP_Macrovars_raw.csv'.

# transform Yoy

In [30]:
main_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      973 non-null    datetime64[ns]
 1   Real GDP                  307 non-null    float64
 2   CPI                       540 non-null    float64
 3   Wholesale Price           335 non-null    float64
 4   Industrial Production     335 non-null    float64
 5   Intl Trade Merch Exports  827 non-null    float64
 6   Intl Trade Merch Imports  827 non-null    float64
 7   FX Rate                   972 non-null    object
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 60.9+ KB

In [31]:
cols_to_transform = [
    "Real GDP", "CPI", "Wholesale Price", "Industrial Production",
    "Intl Trade Merch Exports", "Intl Trade Merch Imports", "FX Rate"
]

for c in cols_to_transform:
    # Check if strictly positive (needed for logs)
    if (main_df[c] > 0).all():
        main_df[f"{c}_yoy_log"] = 100 * (np.log(main_df[c]) - np.log(main_df[c].shift(12)))
    else:
        main_df[f"{c}_yoy_pct"] = 100 * (main_df[c] / main_df[c].shift(12) - 1)

In [32]:
main_df

,Date,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,2025-10-01,5528.834473,128.500000,143.500000,97.322502,416821.93750,684380.125,58.298409,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-09-01,5528.834473,128.500000,142.399994,100.351433,407190.40625,634966.375,57.250091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-08-01,5528.834473,127.699997,143.300003,101.363564,417984.75000,669526.125,57.252526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-01,5843.036621,127.300003,143.000000,98.934433,398221.28125,645985.000,56.752348,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-06-01,5843.036621,127.199997,143.100006,99.385788,406874.84375,608916.250,56.358579,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,1956-09-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
969,1956-10-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
970,1956-11-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
971,1956-12-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
972,1957-01-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [33]:
main_df.info()
main_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   Real GDP                          307 non-null    float64
 2   CPI                               540 non-null    float64
 3   Wholesale Price                   335 non-null    float64
 4   Industrial Production             335 non-null    float64
 5   Intl Trade Merch Exports          827 non-null    float64
 6   Intl Trade Merch Imports          827 non-null    float64
 7   FX Rate                           972 non-null    object
 8   Real GDP_yoy_pct                  295 non-null    float64
 9   CPI_yoy_pct                       528 non-null    float64
 10  Wholesale Price_yoy_pct           322 non-null    float64
 11  Industrial Production_yoy_pct     322 non-null    float64
 12  Intl Trade Merch Exports_yoy_pct  814 non-null    float64
 13  Intl Trade Merch Imports_yoy_pct  814 non-null    float64
 14  FX Rate_yoy_pct                   959 non-null    object
dtypes: datetime64[ns](1), float64(12), object(2)
memory usage: 114.2+ KB

,Date,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,973,307.000000,540.000000,335.000000,335.000000,827.000000,827.000000,295.000000,528.000000,322.000000,322.000000,814.000000,814.000000
mean,1985-07-01 13:19:10.668036992,3419.298446,59.259109,93.189740,74.139310,95519.991259,128884.015392,-4.651027,-5.787533,-3.365325,2.846880,-9.779226,-9.338104
min,1945-01-01 00:00:00,1653.296021,6.129395,43.191925,13.077386,46.459946,75.749916,-10.747527,-65.168078,-67.369412,-84.172084,-77.942845,-84.794200
25%,1965-04-01 00:00:00,2325.314209,27.059615,67.277145,61.936256,1196.188538,1643.216126,-6.404029,-7.797039,-6.213616,-9.652854,-21.263554,-21.951108
50%,1985-07-01 00:00:00,3150.174561,54.261774,99.800003,76.853607,18641.226562,28496.814453,-5.588301,-4.972995,-3.585136,-4.647187,-10.432177,-11.522983
75%,2005-10-01 00:00:00,4437.331055,91.102268,112.649997,87.159279,184366.007812,211525.804688,-4.307985,-2.968789,-2.016958,2.454655,0.000000,-0.424954
max,2026-01-01 00:00:00,6193.631348,130.000000,144.000000,108.341713,454896.562500,694898.812500,20.347393,160.744849,179.184302,491.715967,177.968730,508.059085
std,NaN,1242.548460,36.278571,28.549285,18.776608,118155.582241,178227.869211,3.915941,14.484806,15.551911,51.397899,19.809088,28.278957

# YoY for df w/o GDP

In [34]:
# for df without Real GDP
cols_to_transform = [
    "CPI", "Wholesale Price", "Industrial Production",
    "Intl Trade Merch Exports", "Intl Trade Merch Imports", "FX Rate"
]

for c in cols_to_transform:
    # Check if strictly positive (needed for logs)
    if (main2_df[c] > 0).all():
        main2_df[f"{c}_yoy_log"] = 100 * (np.log(main2_df[c]) - np.log(main2_df[c].shift(12)))
    else:
        main2_df[f"{c}_yoy_pct"] = 100 * (main2_df[c] / main2_df[c].shift(12) - 1)

In [35]:
main2_df

,Date,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,2026-01-01,130.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-12-01,128.899994,144.000000,100.048134,406979.75000,613973.0625,58.848833,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-11-01,128.600006,143.500000,102.761719,434670.96875,679404.9375,58.91355,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-10-01,128.500000,143.500000,97.322502,416821.93750,684380.1250,58.298409,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-09-01,128.500000,142.399994,100.351433,407190.40625,634966.3750,57.250091,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,1956-09-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
969,1956-10-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
970,1956-11-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
971,1956-12-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
972,1957-01-01,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0

In [36]:
main2_df.info()
main2_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   CPI                               540 non-null    float64
 2   Wholesale Price                   335 non-null    float64
 3   Industrial Production             335 non-null    float64
 4   Intl Trade Merch Exports          827 non-null    float64
 5   Intl Trade Merch Imports          827 non-null    float64
 6   FX Rate                           972 non-null    object
 7   CPI_yoy_pct                       528 non-null    float64
 8   Wholesale Price_yoy_pct           323 non-null    float64
 9   Industrial Production_yoy_pct     323 non-null    float64
 10  Intl Trade Merch Exports_yoy_pct  815 non-null    float64
 11  Intl Trade Merch Imports_yoy_pct  815 non-null    float64
 12  FX Rate_yoy_pct                   960 non-null    object
dtypes: datetime64[ns](1), float64(10), object(2)
memory usage: 98.9+ KB

,Date,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,973,540.000000,335.000000,335.000000,827.000000,827.000000,528.000000,323.000000,323.000000,815.000000,815.000000
mean,1985-07-01 13:19:10.668036992,59.259109,93.189740,74.139310,95519.991259,128884.015392,-6.386612,-4.144064,2.454928,-10.165450,-10.186680
min,1945-01-01 00:00:00,6.129395,43.191925,13.077386,46.459946,75.749916,-38.576774,-17.405356,-84.172084,-62.559198,-59.338350
25%,1965-04-01 00:00:00,27.059615,67.277145,61.936256,1196.188538,1643.216126,-7.775391,-6.312636,-9.711129,-21.243155,-21.940118
50%,1985-07-01 00:00:00,54.261774,99.800003,76.853607,18641.226562,28496.814453,-4.998736,-3.624905,-4.714478,-10.585193,-11.433562
75%,2005-10-01 00:00:00,91.102268,112.649997,87.159279,184366.007812,211525.804688,-3.010143,-2.027885,2.196468,-0.288654,-0.523833
max,2026-01-01 00:00:00,130.000000,144.000000,108.341713,454896.562500,694898.812500,1.006711,12.577958,491.715967,74.745872,176.607099
std,NaN,36.278571,28.549285,18.776608,118155.582241,178227.869211,5.809873,3.589190,50.678645,17.507950,18.406185

# ICLR

In [38]:
# Load the Interbank Call Loan Rate dataset raw to inspect contents
df_interest_rate_raw = pd.read_csv('../00 Original Dataset/econ dataset/Interbank Call Loan Rate.csv', header=None)
print("DataFrame 'df_interest_rate_raw':")
df_interest_rate_raw.head(35)

DataFrame 'df_interest_rate_raw':

                        0                                                  1
0                     NaN                           Interbank Call Loan Rate
1                  Region                                        Philippines
2             Subnational                                                NaN
3               Frequency                             Daily, "5 observation"
4                    Unit                                               % pa
5                  Source                        Bangko Sentral ng Pilipinas
6                  Status                                             Active
7               Series ID                                    34005501 (PDOA)
8                 SR Code                                        SR143555627
9              Trade Code                                                NaN
10               Mnemonic                                                NaN
11   Function Description                                                NaN
12        First Obs. Date                                         01/02/1995
13         Last Obs. Date                                         03/27/2025
14       Last Update Time                                         28/03/2025
15         Series Remarks  Interbank Call Loan Rate contains the interest...
16            Suggestions                                                NaN
17                   Mean                                  6.823833634583581
18               Variance                                 20.819644708422725
19     Standard Deviation                                  4.562854885751104
20               Skewness                                  4.512214153267406
21               Kurtosis                                   57.0534883832527
22  Coefficient Variation                                  0.668664438509505
23                    Min                                                  0
24                    Max                                            102.625
25                 Median                                             6.4063
26                    Sum                                 45303.431500000326
27               Subtract                                           -102.625
28             No. of Obs                                               6639
29             01/02/1995                                            13.4375
30             01/03/1995                                              9.375
31             01/04/1995                                               8.75
32             01/05/1995                                             8.3125
33             01/06/1995                                               8.75
34             01/09/1995                                              8.125

In [39]:
# Extract the actual data rows (starting from index 29)
df_interest_rate = df_interest_rate_raw.iloc[29:].copy()
df_interest_rate.columns = ['Date', 'Interbank Call Loan Rate']

# Clean and convert to datetime
df_interest_rate['Date'] = pd.to_datetime(df_interest_rate['Date'], errors='coerce')
df_interest_rate.dropna(subset=['Date'], inplace=True)

# Ensure rate is numeric
df_interest_rate['Interbank Call Loan Rate'] = pd.to_numeric(df_interest_rate['Interbank Call Loan Rate'], errors='coerce')
df_interest_rate.dropna(subset=['Interbank Call Loan Rate'], inplace=True)

# Transform daily data to monthly data (averaging per month)
df_interest_rate['Month_Period'] = df_interest_rate['Date'].dt.to_period('M')
df_interest_rate_monthly = df_interest_rate.groupby('Month_Period')['Interbank Call Loan Rate'].mean().reset_index()

# Align the Date to the first day of the next month to match macroeconomic variables alignment       
df_interest_rate_monthly['Date'] = (df_interest_rate_monthly['Month_Period'] + 1).dt.to_timestamp()  
df_interest_rate = df_interest_rate_monthly[['Date', 'Interbank Call Loan Rate']]

print("Transformed ICLR to Monthly:")
print(df_interest_rate.head())

Transformed ICLR to Monthly:
        Date  Interbank Call Loan Rate
0 1995-02-01                  9.119048
1 1995-03-01                 13.328125
2 1995-04-01                 19.073370
3 1995-05-01                 20.375000
4 1995-06-01                 11.413690

# merge macrovars with ICLR

In [40]:
main_df = pd.merge(df_interest_rate, main_df, on='Date', how='outer')

print("Merged DataFrames successfully.")
main_df.info()
main_df

Merged DataFrames successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   Interbank Call Loan Rate          362 non-null    float64
 2   Real GDP                          307 non-null    float64
 3   CPI                               540 non-null    float64
 4   Wholesale Price                   335 non-null    float64
 5   Industrial Production             335 non-null    float64
 6   Intl Trade Merch Exports          827 non-null    float64
 7   Intl Trade Merch Imports          827 non-null    float64
 8   FX Rate                           972 non-null    object
 9   Real GDP_yoy_pct                  295 non-null    float64
 10  CPI_yoy_pct                       528 non-null    float64
 11  Wholesale Price_yoy_pct           322 non-null    float64
 12  Industrial Production_yoy_pct     322 non-null    float64
 13  Intl Trade Merch Exports_yoy_pct  814 non-null    float64
 14  Intl Trade Merch Imports_yoy_pct  814 non-null    float64
 15  FX Rate_yoy_pct                   959 non-null    object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 121.8+ KB

,Date,Interbank Call Loan Rate,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,1995-02-01,9.119048,NaN,33.687916,NaN,NaN,28527.265625,45604.312500,25.028158,NaN,-7.802334,NaN,NaN,-23.354293,-22.187367,-4.322085
1,1995-03-01,13.328125,NaN,33.830460,NaN,NaN,31663.976562,40481.792969,25.858957,NaN,-8.010326,NaN,NaN,-24.058154,-34.422968,-1.285366
2,1995-04-01,19.073370,NaN,33.973003,NaN,NaN,33494.789062,55257.375000,26.007722,NaN,-7.979401,NaN,NaN,-23.438302,-23.529846,-0.694785
3,1995-05-01,20.375000,NaN,34.068031,NaN,NaN,35827.980469,58022.070312,25.849286,NaN,-8.194622,NaN,NaN,-8.252690,-21.137195,-1.247605
4,1995-06-01,11.413690,NaN,34.400635,NaN,NaN,36243.531250,55464.761719,25.674238,NaN,-7.416880,NaN,NaN,-14.049281,-21.817145,-1.985854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,1956-09-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
969,1956-10-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
970,1956-11-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
971,1956-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0
972,1957-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [41]:
main2_df = pd.merge(df_interest_rate, main2_df, on='Date', how='outer')

print("Merged DataFrames successfully.")
main2_df.info()
main2_df

Merged DataFrames successfully.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 973 entries, 0 to 972
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              973 non-null    datetime64[ns]
 1   Interbank Call Loan Rate          362 non-null    float64
 2   CPI                               540 non-null    float64
 3   Wholesale Price                   335 non-null    float64
 4   Industrial Production             335 non-null    float64
 5   Intl Trade Merch Exports          827 non-null    float64
 6   Intl Trade Merch Imports          827 non-null    float64
 7   FX Rate                           972 non-null    object
 8   CPI_yoy_pct                       528 non-null    float64
 9   Wholesale Price_yoy_pct           323 non-null    float64
 10  Industrial Production_yoy_pct     323 non-null    float64
 11  Intl Trade Merch Exports_yoy_pct  815 non-null    float64
 12  Intl Trade Merch Imports_yoy_pct  815 non-null    float64
 13  FX Rate_yoy_pct                   960 non-null    object
dtypes: datetime64[ns](1), float64(11), object(2)
memory usage: 106.6+ KB

,Date,Interbank Call Loan Rate,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
0,1995-02-01,9.119048,33.687916,NaN,NaN,28527.265625,45604.312500,25.028158,-7.802334,NaN,NaN,-23.354293,-22.187367,-4.322085
1,1995-03-01,13.328125,33.830460,NaN,NaN,31663.976562,40481.792969,25.858957,-8.010326,NaN,NaN,-24.058154,-34.422968,-1.285366
2,1995-04-01,19.073370,33.973003,NaN,NaN,33494.789062,55257.375000,26.007722,-7.979401,NaN,NaN,-23.438302,-23.529846,-0.694785
3,1995-05-01,20.375000,34.068031,NaN,NaN,35827.980469,58022.070312,25.849286,-8.194622,NaN,NaN,-8.252690,-21.137195,-1.247605
4,1995-06-01,11.413690,34.400635,NaN,NaN,36243.531250,55464.761719,25.674238,-7.416880,NaN,NaN,-14.049281,-21.817145,-1.985854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
968,1956-09-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
969,1956-10-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
970,1956-11-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
971,1956-12-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0
972,1957-01-01,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,0.0

# Data Availability (start and end dates)

In [42]:
print("Starting and Ending Dates for Each Variable (Raw Data Availability):\n")
for col in main_df.columns:
    if col != 'Date':
        first_valid_idx = main_df[col].first_valid_index()
        last_valid_idx = main_df[col].last_valid_index()
        if pd.notna(first_valid_idx) and pd.notna(last_valid_idx):
            start_date = main_df.loc[first_valid_idx, 'Date'].strftime('%Y-%m-%d')
            end_date = main_df.loc[last_valid_idx, 'Date'].strftime('%Y-%m-%d')
            print(f"  {col}: Start Date = {start_date}, End Date = {end_date}")
        else:
            print(f"  {col}: No valid data found for this column.")

Starting and Ending Dates for Each Variable (Raw Data Availability):

  Interbank Call Loan Rate: Start Date = 1995-02-01, End Date = 2025-04-01
  Real GDP: Start Date = 2000-04-01, End Date = 2022-02-01
  CPI: Start Date = 1995-02-01, End Date = 1981-02-01
  Wholesale Price: Start Date = 1998-02-01, End Date = 2025-11-01
  Industrial Production: Start Date = 1998-02-01, End Date = 2025-11-01
  Intl Trade Merch Exports: Start Date = 1995-02-01, End Date = 1957-02-01
  Intl Trade Merch Imports: Start Date = 1995-02-01, End Date = 1957-02-01
  FX Rate: Start Date = 1995-02-01, End Date = 1957-01-01
  Real GDP_yoy_pct: Start Date = 2000-04-01, End Date = 2022-02-01
  CPI_yoy_pct: Start Date = 1995-02-01, End Date = 1981-02-01
  Wholesale Price_yoy_pct: Start Date = 1998-02-01, End Date = 2025-11-01
  Industrial Production_yoy_pct: Start Date = 1998-02-01, End Date = 2025-11-01
  Intl Trade Merch Exports_yoy_pct: Start Date = 1995-02-01, End Date = 1957-02-01
  Intl Trade Merch Imports_yoy_pct: Start Date = 1995-02-01, End Date = 1957-02-01
  FX Rate_yoy_pct: Start Date = 1995-02-01, End Date = 1957-01-01

# drop nulls for df w/ GDP

In [43]:
print(f"Original shape of main_df: {main_df.shape}")
main_df.dropna(inplace=True)
print(f"New shape of main_df after dropping rows with missing values: {main_df.shape}")
print("Number of nulls per column after dropping rows:")
print(main_df.isna().sum())

Original shape of main_df: (973, 16)
New shape of main_df after dropping rows with missing values: (294, 16)
Number of nulls per column after dropping rows:
Date                                0
Interbank Call Loan Rate            0
Real GDP                            0
CPI                                 0
Wholesale Price                     0
Industrial Production               0
Intl Trade Merch Exports            0
Intl Trade Merch Imports            0
FX Rate                             0
Real GDP_yoy_pct                    0
CPI_yoy_pct                         0
Wholesale Price_yoy_pct             0
Industrial Production_yoy_pct       0
Intl Trade Merch Exports_yoy_pct    0
Intl Trade Merch Imports_yoy_pct    0
FX Rate_yoy_pct                     0
dtype: int64

In [44]:
main_df.info()
main_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 294 entries, 62 to 355
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              294 non-null    datetime64[ns]
 1   Interbank Call Loan Rate          294 non-null    float64
 2   Real GDP                          294 non-null    float64
 3   CPI                               294 non-null    float64
 4   Wholesale Price                   294 non-null    float64
 5   Industrial Production             294 non-null    float64
 6   Intl Trade Merch Exports          294 non-null    float64
 7   Intl Trade Merch Imports          294 non-null    float64
 8   FX Rate                           294 non-null    object
 9   Real GDP_yoy_pct                  294 non-null    float64
 10  CPI_yoy_pct                       294 non-null    float64
 11  Wholesale Price_yoy_pct           294 non-null    float64
 12  Industrial Production_yoy_pct     294 non-null    float64
 13  Intl Trade Merch Exports_yoy_pct  294 non-null    float64
 14  Intl Trade Merch Imports_yoy_pct  294 non-null    float64
 15  FX Rate_yoy_pct                   294 non-null    object
dtypes: datetime64[ns](1), float64(13), object(2)
memory usage: 39.0+ KB

,Date,Interbank Call Loan Rate,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,294,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000,294.000000
mean,2012-06-19 09:28:09.795918336,5.081207,3319.699536,83.292822,94.892819,75.758036,225500.763765,300649.699458,-4.646343,-3.861009,-4.032376,3.678296,-2.904868,-4.942071
min,2000-04-01 00:00:00,1.535188,1653.296021,46.564396,48.932911,13.077386,109947.960938,101988.859375,-10.747527,-9.536313,-17.405356,-84.172084,-39.955694,-58.676202
25%,2006-05-08 18:00:00,2.572710,2297.796875,65.116527,77.222950,66.367443,174104.921875,196544.957031,-6.404029,-4.931217,-6.270426,-9.246092,-12.527501,-16.032165
50%,2012-06-16 00:00:00,4.669373,3129.775635,85.068581,100.000000,77.344486,202880.937500,227564.648438,-5.588301,-3.545698,-3.351201,-4.066569,-3.758911,-6.266908
75%,2018-07-24 06:00:00,7.050462,4384.760620,99.992895,112.099998,86.010918,280154.890625,404724.742188,-4.307985,-2.613334,-1.967705,3.080638,4.058656,2.315739
max,2024-10-01 00:00:00,15.105903,5884.528320,126.599998,139.500000,108.341713,454896.562500,694898.812500,20.347393,0.374180,12.577958,491.715967,74.745872,176.607099
std,NaN,2.519460,1170.398584,21.997096,24.737639,16.575743,70318.170237,152883.523378,3.921790,1.941534,3.717936,52.935662,14.572486,19.181717

In [45]:
main_df

,Date,Interbank Call Loan Rate,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,Real GDP_yoy_pct,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
62,2000-04-01,8.846467,1653.296021,46.564396,49.112316,47.951805,122463.656250,112343.710938,41.1884,-2.357231,-7.020871,-6.729131,-17.399658,-12.036585,-23.742827,-17.927507
63,2000-05-01,8.878472,1729.789429,46.706940,48.932911,42.576923,109947.960938,104178.578125,41.8063,-3.164755,-6.912874,-7.776837,-13.532396,-2.567846,-33.220726,-17.278897
64,2000-06-01,9.765625,1729.789429,46.801968,49.246868,48.261353,122662.843750,101988.859375,42.6489,-3.164755,-6.899814,-7.808568,-9.661012,-6.583343,-31.310551,-17.167382
65,2000-07-01,10.367560,1729.789429,47.277115,49.471127,51.778942,145549.312500,106494.289062,44.355667,-3.164755,-6.747894,-8.993398,-7.965606,9.435560,-27.748429,-16.662567
66,2000-08-01,10.617062,1709.412964,47.514687,49.964493,49.274418,143163.296875,119013.664062,44.897652,-3.016611,-6.890136,-8.912509,-6.984505,3.627590,-22.218756,-13.637926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,2024-06-01,6.508536,5539.082520,125.599998,138.300003,99.541405,366273.812500,639752.375000,58.696278,-5.201989,-1.257861,-3.354300,0.156579,-9.978752,5.064100,4.147902
352,2024-07-01,6.515650,5539.082520,125.599998,138.800003,96.161621,326938.343750,581487.062500,58.484478,-5.201989,-1.335432,-2.937061,-2.802676,-17.900334,-9.984433,3.052086
353,2024-08-01,6.511924,5316.054199,126.500000,139.000000,102.081268,365493.531250,650692.000000,57.19345,-3.848556,-0.939700,-3.000700,0.708049,-12.558166,-2.813053,-0.103186
354,2024-09-01,6.471885,5316.054199,126.599998,139.100006,98.493027,384723.031250,635113.187500,56.071286,-3.848556,-1.478601,-2.317407,-1.851898,-5.517658,0.023121,-2.059045
355,2024-10-01,6.351580,5316.054199,126.300003,139.500000,96.384209,350995.625000,637103.750000,57.30087,-3.848556,-1.712060,-2.787456,-0.964107,-15.792430,-6.907912,-1.711092

# save merged econ data with GDP, with orig and yoy values

In [46]:
main_df['FX Rate_yoy_pct'] = pd.to_numeric(main_df['FX Rate_yoy_pct'], errors='coerce')

main_df.to_csv('../00 Cleaned Dataset/03 economic dataset/others/withGDP_Econ_Dataset_with_orig_and_yoy.csv', index=False)
print("DataFrame 'main_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withGDP_Econ_Dataset_with_orig_and_yoy.csv'.")

DataFrame 'main_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withGDP_Econ_Dataset_with_orig_and_yoy.csv'.

# drop orig values to keep only the YoY data

In [47]:
columns_to_drop = [
    'Real GDP',
    'CPI',
    'Wholesale Price',
    'Industrial Production',
    'Intl Trade Merch Exports',
    'Intl Trade Merch Imports',
    'FX Rate'
]

# Drop the specified columns, ignoring errors if a column is already absent
main_df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("Specified columns dropped successfully.")
main_df.info()

Specified columns dropped successfully.
<class 'pandas.core.frame.DataFrame'>
Index: 294 entries, 62 to 355
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              294 non-null    datetime64[ns]
 1   Interbank Call Loan Rate          294 non-null    float64
 2   Real GDP_yoy_pct                  294 non-null    float64
 3   CPI_yoy_pct                       294 non-null    float64
 4   Wholesale Price_yoy_pct           294 non-null    float64
 5   Industrial Production_yoy_pct     294 non-null    float64
 6   Intl Trade Merch Exports_yoy_pct  294 non-null    float64
 7   Intl Trade Merch Imports_yoy_pct  294 non-null    float64
 8   FX Rate_yoy_pct                   294 non-null    float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 23.0 KB

In [48]:
new_columns = {}
for col in main_df.columns:
    # Only rename columns that are numeric (float or int) and end with '_yoy_pct'
    if col.endswith('_yoy_pct') and pd.api.types.is_numeric_dtype(main_df[col]):
        new_columns[col] = col.replace('_yoy_pct', '')
main_df.rename(columns=new_columns, inplace=True)

print("Columns renamed successfully by removing '_yoy_pct' suffix.")
main_df.info()
main_df

Columns renamed successfully by removing '_yoy_pct' suffix.
<class 'pandas.core.frame.DataFrame'>
Index: 294 entries, 62 to 355
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      294 non-null    datetime64[ns]
 1   Interbank Call Loan Rate  294 non-null    float64
 2   Real GDP                  294 non-null    float64
 3   CPI                       294 non-null    float64
 4   Wholesale Price           294 non-null    float64
 5   Industrial Production     294 non-null    float64
 6   Intl Trade Merch Exports  294 non-null    float64
 7   Intl Trade Merch Imports  294 non-null    float64
 8   FX Rate                   294 non-null    float64
dtypes: datetime64[ns](1), float64(8)
memory usage: 23.0 KB

,Date,Interbank Call Loan Rate,Real GDP,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
62,2000-04-01,8.846467,-2.357231,-7.020871,-6.729131,-17.399658,-12.036585,-23.742827,-17.927507
63,2000-05-01,8.878472,-3.164755,-6.912874,-7.776837,-13.532396,-2.567846,-33.220726,-17.278897
64,2000-06-01,9.765625,-3.164755,-6.899814,-7.808568,-9.661012,-6.583343,-31.310551,-17.167382
65,2000-07-01,10.367560,-3.164755,-6.747894,-8.993398,-7.965606,9.435560,-27.748429,-16.662567
66,2000-08-01,10.617062,-3.016611,-6.890136,-8.912509,-6.984505,3.627590,-22.218756,-13.637926
...,...,...,...,...,...,...,...,...,...
351,2024-06-01,6.508536,-5.201989,-1.257861,-3.354300,0.156579,-9.978752,5.064100,4.147902
352,2024-07-01,6.515650,-5.201989,-1.335432,-2.937061,-2.802676,-17.900334,-9.984433,3.052086
353,2024-08-01,6.511924,-3.848556,-0.939700,-3.000700,0.708049,-12.558166,-2.813053,-0.103186
354,2024-09-01,6.471885,-3.848556,-1.478601,-2.317407,-1.851898,-5.517658,0.023121,-2.059045
355,2024-10-01,6.351580,-3.848556,-1.712060,-2.787456,-0.964107,-15.792430,-6.907912,-1.711092

# save merged macrovars with GDP

In [49]:
main_df.to_csv('../00 Cleaned Dataset/03 economic dataset/withGDP_Econ_Dataset.csv', index=False)

# drop nulls for df w/o GDP

In [50]:
print(f"Original shape of main2_df: {main2_df.shape}")
main2_df.dropna(inplace=True)
print(f"New shape of main2_df after dropping rows with missing values: {main2_df.shape}")
print("Number of nulls per column after dropping rows:")
print(main2_df.isna().sum())

Original shape of main2_df: (973, 14)
New shape of main2_df after dropping rows with missing values: (322, 14)
Number of nulls per column after dropping rows:
Date                                0
Interbank Call Loan Rate            0
CPI                                 0
Wholesale Price                     0
Industrial Production               0
Intl Trade Merch Exports            0
Intl Trade Merch Imports            0
FX Rate                             0
CPI_yoy_pct                         0
Wholesale Price_yoy_pct             0
Industrial Production_yoy_pct       0
Intl Trade Merch Exports_yoy_pct    0
Intl Trade Merch Imports_yoy_pct    0
FX Rate_yoy_pct                     0
dtype: int64

In [51]:
main2_df.info()
main2_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 322 entries, 36 to 357
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              322 non-null    datetime64[ns]
 1   Interbank Call Loan Rate          322 non-null    float64
 2   CPI                               322 non-null    float64
 3   Wholesale Price                   322 non-null    float64
 4   Industrial Production             322 non-null    float64
 5   Intl Trade Merch Exports          322 non-null    float64
 6   Intl Trade Merch Imports          322 non-null    float64
 7   FX Rate                           322 non-null    object
 8   CPI_yoy_pct                       322 non-null    float64
 9   Wholesale Price_yoy_pct           322 non-null    float64
 10  Industrial Production_yoy_pct     322 non-null    float64
 11  Intl Trade Merch Exports_yoy_pct  322 non-null    float64
 12  Intl Trade Merch Imports_yoy_pct  322 non-null    float64
 13  FX Rate_yoy_pct                   322 non-null    object
dtypes: datetime64[ns](1), float64(11), object(2)
memory usage: 37.7+ KB

,Date,Interbank Call Loan Rate,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct
count,322,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000,322.000000
mean,2011-06-20 00:49:11.552795136,5.630867,80.436546,91.247711,73.173528,216754.973044,286732.404309,-3.928807,-4.136573,2.498620,-3.994882,-5.063153
min,1998-02-01 00:00:00,1.535188,41.100204,43.191925,13.077386,87942.335938,80524.179688,-9.536313,-17.405356,-84.172084,-39.955694,-58.676202
25%,2004-10-08 18:00:00,2.732898,58.502460,65.718559,61.289009,164879.542969,181292.007812,-4.976616,-6.270426,-9.661149,-13.526156,-15.664842
50%,2011-06-16 00:00:00,5.066192,82.714703,98.650719,76.219577,198007.000000,220379.171875,-3.582803,-3.613550,-4.647187,-5.161728,-5.974031
75%,2018-02-22 00:00:00,7.181695,97.818207,111.850000,84.804617,276611.843750,394449.687500,-2.661124,-2.026601,2.206583,3.141404,2.072503
max,2024-12-01 00:00:00,16.275321,127.000000,140.199997,108.341713,454896.562500,694898.812500,0.374180,12.577958,491.715967,74.745872,176.607099
std,NaN,3.103712,23.808827,27.377719,18.497211,75251.146228,158663.071074,1.951860,3.592247,50.751429,14.510510,18.748869

In [52]:
main2_df

,Date,Interbank Call Loan Rate,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate,CPI_yoy_pct,Wholesale Price_yoy_pct,Industrial Production_yoy_pct,Intl Trade Merch Exports_yoy_pct,Intl Trade Merch Imports_yoy_pct,FX Rate_yoy_pct
36,1998-02-01,13.174410,41.100204,43.191925,39.200035,90267.828125,121125.335938,40.4143,-9.518831,-7.581580,-2.587420,-8.879404,31.490785,4.214554
37,1998-03-01,13.459377,41.670383,43.685291,39.200035,89656.335938,104068.984375,39.004045,-8.263595,-6.436122,-5.173596,-10.075986,18.808782,0.239684
38,1998-04-01,13.248584,42.050499,43.774994,41.001041,96095.796875,101533.718750,38.44215,-7.135362,-6.513416,-7.138310,-8.565695,-1.718374,0.524069
39,1998-05-01,13.201562,42.240559,44.133808,36.526669,87942.335938,94562.062500,39.297105,-6.617642,-6.106869,-11.520108,-2.033929,-4.914044,3.854883
40,1998-06-01,13.588816,42.810734,44.627174,37.905563,94816.812500,103022.492188,40.39905,-5.456454,-5.328252,-12.871929,-8.771209,7.498424,6.595717
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353,2024-08-01,6.511924,126.500000,139.000000,102.081268,365493.531250,650692.000000,57.19345,-0.939700,-3.000700,0.708049,-12.558166,-2.813053,-0.103186
354,2024-09-01,6.471885,126.599998,139.100006,98.493027,384723.031250,635113.187500,56.071286,-1.478601,-2.317407,-1.851898,-5.517658,0.023121,-2.059045
355,2024-10-01,6.351580,126.300003,139.500000,96.384209,350995.625000,637103.750000,57.30087,-1.712060,-2.787456,-0.964107,-15.792430,-6.907912,-1.711092
356,2024-11-01,6.244332,126.500000,139.800003,101.213943,355557.750000,689500.812500,58.69465,-1.632975,-2.578395,-1.506180,-18.200714,1.485988,-0.371561
357,2024-12-01,6.159405,127.000000,140.199997,101.454735,334371.937500,624029.750000,58.448,-1.474006,-2.638891,1.405924,-17.840645,1.637969,-0.681124

# save merged macrovars without GDP, with orig and yoy values

In [53]:
main2_df['FX Rate_yoy_pct'] = pd.to_numeric(main2_df['FX Rate_yoy_pct'], errors='coerce')

main2_df.to_csv('../00 Cleaned Dataset/03 economic dataset/others/withoutGDP_Econ_Dataset_with_orig_and_yoy.csv', index=False)
print("DataFrame 'main2_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withoutGDP_Econ_Dataset_with_orig_and_yoy.csv'.")

DataFrame 'main2_df' saved successfully to '../00 Cleaned Dataset/03 economic dataset/others/withoutGDP_Econ_Dataset_with_orig_and_yoy.csv'.

# drop orig values to keep only the yoy data

In [54]:
columns_to_drop = [
    'CPI',
    'Wholesale Price',
    'Industrial Production',
    'Intl Trade Merch Exports',
    'Intl Trade Merch Imports',
    'FX Rate'
]

# Drop the specified columns, ignoring errors if a column is already absent
main2_df.drop(columns=columns_to_drop, inplace=True, errors='ignore')

print("Specified columns dropped successfully.")
main2_df.info()

Specified columns dropped successfully.
<class 'pandas.core.frame.DataFrame'>
Index: 322 entries, 36 to 357
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Date                              322 non-null    datetime64[ns]
 1   Interbank Call Loan Rate          322 non-null    float64
 2   CPI_yoy_pct                       322 non-null    float64
 3   Wholesale Price_yoy_pct           322 non-null    float64
 4   Industrial Production_yoy_pct     322 non-null    float64
 5   Intl Trade Merch Exports_yoy_pct  322 non-null    float64
 6   Intl Trade Merch Imports_yoy_pct  322 non-null    float64
 7   FX Rate_yoy_pct                   322 non-null    float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 22.6 KB

In [55]:
new_columns = {}
for col in main2_df.columns:
    # Only rename columns that are numeric (float or int) and end with '_yoy_pct'
    if col.endswith('_yoy_pct') and pd.api.types.is_numeric_dtype(main2_df[col]):
        new_columns[col] = col.replace('_yoy_pct', '')
main2_df.rename(columns=new_columns, inplace=True)

print("Columns renamed successfully by removing '_yoy_pct' suffix.")
main2_df.info()
main2_df

Columns renamed successfully by removing '_yoy_pct' suffix.
<class 'pandas.core.frame.DataFrame'>
Index: 322 entries, 36 to 357
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Date                      322 non-null    datetime64[ns]
 1   Interbank Call Loan Rate  322 non-null    float64
 2   CPI                       322 non-null    float64
 3   Wholesale Price           322 non-null    float64
 4   Industrial Production     322 non-null    float64
 5   Intl Trade Merch Exports  322 non-null    float64
 6   Intl Trade Merch Imports  322 non-null    float64
 7   FX Rate                   322 non-null    float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 22.6 KB

,Date,Interbank Call Loan Rate,CPI,Wholesale Price,Industrial Production,Intl Trade Merch Exports,Intl Trade Merch Imports,FX Rate
36,1998-02-01,13.174410,-9.518831,-7.581580,-2.587420,-8.879404,31.490785,4.214554
37,1998-03-01,13.459377,-8.263595,-6.436122,-5.173596,-10.075986,18.808782,0.239684
38,1998-04-01,13.248584,-7.135362,-6.513416,-7.138310,-8.565695,-1.718374,0.524069
39,1998-05-01,13.201562,-6.617642,-6.106869,-11.520108,-2.033929,-4.914044,3.854883
40,1998-06-01,13.588816,-5.456454,-5.328252,-12.871929,-8.771209,7.498424,6.595717
...,...,...,...,...,...,...,...,...
353,2024-08-01,6.511924,-0.939700,-3.000700,0.708049,-12.558166,-2.813053,-0.103186
354,2024-09-01,6.471885,-1.478601,-2.317407,-1.851898,-5.517658,0.023121,-2.059045
355,2024-10-01,6.351580,-1.712060,-2.787456,-0.964107,-15.792430,-6.907912,-1.711092
356,2024-11-01,6.244332,-1.632975,-2.578395,-1.506180,-18.200714,1.485988,-0.371561
357,2024-12-01,6.159405,-1.474006,-2.638891,1.405924,-17.840645,1.637969,-0.681124

# save merged macrovars without GDP

In [56]:
main2_df.to_csv('../00 Cleaned Dataset/03 economic dataset/withoutGDP_Econ_Dataset.csv', index=False)