# fine-tuned bert models

In [ ]:
import pandas as pd

file_paths = [
    '../00 Cleaned Dataset/02 fine-tuned bert results/econobert_speeches.csv',
    '../00 Cleaned Dataset/02 fine-tuned bert results/finbert_speeches.csv',
    '../00 Cleaned Dataset/02 fine-tuned bert results/roberta_speeches.csv'
]

dataframes = [pd.read_csv(file) for file in file_paths]

# Display summary statistics
for i, df in enumerate(dataframes):
    print(f"Summary Statistics for BERT Model {i+1}:")
    if 'n_sent' in df.columns:
        display(df['tone_mean'].describe())
    else:
        print("Column 'tone_mean' not found in this DataFrame.")
    print("-" * 30)

Summary Statistics for BERT Model 1:

count    676.000000
mean       0.413424
std        0.158561
min       -0.165149
25%        0.300222
50%        0.425208
75%        0.531712
max        0.789277
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 2:

count    676.000000
mean       0.401666
std        0.151025
min       -0.090047
25%        0.298299
50%        0.412776
75%        0.516337
max        0.777045
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 3:

count    676.000000
mean       0.438555
std        0.158649
min       -0.155322
25%        0.332110
50%        0.448126
75%        0.558567
max        0.787467
Name: tone_mean, dtype: float64

------------------------------

# not fine-tuned

In [ ]:
file_paths = [
    '../00 Cleaned Dataset/05 Exploratory and Baseline Models/Base BERT Baselines/econobert_speeches_agg.csv',
    '../00 Cleaned Dataset/05 Exploratory and Baseline Models/Base BERT Baselines/finbert_speeches_agg.csv',
    '../00 Cleaned Dataset/05 Exploratory and Baseline Models/Base BERT Baselines/roberta_speeches_agg.csv'
]

dataframes = [pd.read_csv(file) for file in file_paths]

# Display summary statistics
for i, df in enumerate(dataframes):
    print(f"Summary Statistics for BERT Model {i+1}:")
    if 'n_sent' in df.columns:
        display(df['tone_mean'].describe())
    else:
        print("Column 'tone_mean' not found in this DataFrame.")
    print("-" * 30)

Summary Statistics for BERT Model 1:

count    676.000000
mean      -0.245937
std        0.030168
min       -0.309654
25%       -0.265135
50%       -0.250728
75%       -0.232857
max       -0.060136
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 2:

count    676.000000
mean       0.042539
std        0.226196
min       -0.537994
25%       -0.137166
50%        0.033195
75%        0.207323
max        0.787607
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 3:

count    676.000000
mean       0.372211
std        0.163862
min       -0.116686
25%        0.260919
50%        0.375379
75%        0.486184
max        0.836723
Name: tone_mean, dtype: float64

------------------------------