In [2]:
import sys
import os

if 'google.colab' in sys.modules:
    print("☁️ Google Colab detected. Setting up GitHub repository...")
    if not os.path.exists('manero-panganiban-serafica'):
        !git clone https://github.com/kricme/manero-panganiban-serafica.git
    if not os.getcwd().endswith('04 Transformer-based Sentiment Analysis'):
        %cd "manero-panganiban-serafica/04 Transformer-based Sentiment Analysis"
else:
    print("💻 Local environment detected. Using local file paths.")

☁️ Google Colab detected. Setting up GitHub repository...
Cloning into 'manero-panganiban-serafica'...
remote: Enumerating objects: 182, done.
remote: Counting objects: 100% (182/182), done.
remote: Compressing objects: 100% (153/153), done.
remote: Total 182 (delta 69), reused 74 (delta 24), pack-reused 0 (from 0)
Receiving objects: 100% (182/182), 27.71 MiB | 11.22 MiB/s, done.
Resolving deltas: 100% (69/69), done.

# fine-tuned bert models

In [3]:
import pandas as pd

file_paths = [
    '../00 Cleaned Dataset/02 fine-tuned bert results/econobert_speeches.csv',
    '../00 Cleaned Dataset/02 fine-tuned bert results/finbert_speeches.csv',
    '../00 Cleaned Dataset/02 fine-tuned bert results/roberta_speeches.csv'
]

dataframes = [pd.read_csv(file) for file in file_paths]

# Display summary statistics
for i, df in enumerate(dataframes):
    print(f"Summary Statistics for BERT Model {i+1}:")
    if 'n_sent' in df.columns:
        display(df['tone_mean'].describe())
    else:
        print("Column 'tone_mean' not found in this DataFrame.")
    print("-" * 30)

Summary Statistics for BERT Model 1:

count    673.000000
mean       0.409306
std        0.159136
min       -0.173937
25%        0.300935
50%        0.420080
75%        0.527174
max        0.785675
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 2:

count    673.000000
mean       0.366610
std        0.116019
min        0.022592
25%        0.281469
50%        0.372830
75%        0.457579
max        0.647292
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 3:

count    673.000000
mean       0.342678
std        0.132697
min       -0.149581
25%        0.246160
50%        0.349129
75%        0.438672
max        0.667261
Name: tone_mean, dtype: float64

------------------------------

# not fine-tuned

In [4]:
file_paths = [
    '../00 Cleaned Dataset/05 Exploratory and Baseline Models/Base BERT Baselines/econobert_speeches_agg.csv',
    '../00 Cleaned Dataset/05 Exploratory and Baseline Models/Base BERT Baselines/finbert_speeches_agg.csv',
    '../00 Cleaned Dataset/05 Exploratory and Baseline Models/Base BERT Baselines/roberta_speeches_agg.csv'
]

dataframes = [pd.read_csv(file) for file in file_paths]

# Display summary statistics
for i, df in enumerate(dataframes):
    print(f"Summary Statistics for BERT Model {i+1}:")
    if 'n_sent' in df.columns:
        display(df['tone_mean'].describe())
    else:
        print("Column 'tone_mean' not found in this DataFrame.")
    print("-" * 30)

Summary Statistics for BERT Model 1:

count    673.000000
mean      -0.515456
std        0.012708
min       -0.553602
25%       -0.523460
50%       -0.516873
75%       -0.507464
max       -0.437622
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 2:

count    673.000000
mean       0.042732
std        0.226009
min       -0.537357
25%       -0.137097
50%        0.035131
75%        0.206877
max        0.787608
Name: tone_mean, dtype: float64

------------------------------
Summary Statistics for BERT Model 3:

count    673.000000
mean       0.372200
std        0.164912
min       -0.116686
25%        0.260076
50%        0.375455
75%        0.486551
max        0.836723
Name: tone_mean, dtype: float64

------------------------------